import { BaseAPI } from '@rbx/clients-core';
import { createClientConfiguration } from './utils/createClientConfiguration';

// ! NOTE(@zwang, 01/28/25): this is a VERY special case where a client cannot be accurately
// ! generated by its swagger schema, DO NOT copy this pattern unless you know what you are doing
class GUACClient extends BaseAPI {
  constructor() {
    super(createClientConfiguration('guac-v2', 'bedev2'));
  }

  async loadBehavior<T>(behavior: string): Promise<T> {
    return this.request({
      path: `/v1/bundles/${behavior}`,
      method: 'GET',
      headers: {},
      // oxlint-disable-next-line no-unsafe-type-assertion -- response.json() returns Promise<any>; caller provides T
    }).then((response) => response.json() as Promise<T>);
  }
}

const guacClient = new GUACClient();

export default guacClient;
