import { Grid, PeopleIcon, ThumbUpIcon, Typography } from '@rbx/ui';
import React, { FC, useMemo } from 'react';
import {
  ChartUnit,
  ChartUnitAggregationType,
  ComparisonChipSpec,
  GenericChartState,
  NumberContext,
  formatDateFromNow,
} from '@modules/charts-generic';
import { ReturnPolicy, Thumbnail2d, ThumbnailTypes } from '@rbx/thumbnails';
import { Link, urls } from '@modules/miscellaneous/common';
import AnalyticsItemTile from '../AnalyticsTile/AnalyticsTile';
import useAnalyticsExperienceTileStyles from './AnalyticsExperienceTile.styles';
import SubtitleStat from '../SubtitleStat/SubtitleStat';
import useRAQIV2TranslationDependencies from '../../hooks/useRAQIV2TranslationDependencies';
import { TTileStyleConfig } from '../../constants/tileConstants';

const {
  creatorHub: { dashboard },
} = urls;
export type MetricValue = {
  value: number | null;
  comparisonChipSpec: ComparisonChipSpec | null;
};

export type AnalyticsExperienceTileSpec = {
  universeId: number;
  title: string;
  ownerName: string | null;
  likeRatio: number | null;
  playing: number | null;
  updatedDate: Date | null;
  actionButton?: React.ReactNode;
  floatingChildren?: React.ReactNode;
  styleConfig: TTileStyleConfig;
  isDragging?: boolean;
} & GenericChartState;

const AnalyticsExperienceTile: FC<React.PropsWithChildren<AnalyticsExperienceTileSpec>> = ({
  universeId,
  title,
  ownerName,
  likeRatio,
  playing,
  updatedDate,
  actionButton,
  isDataLoading,
  isResponseFailed,
  isUserForbidden,
  children,
  floatingChildren,
  styleConfig,
  isDragging = false,
}) => {
  const {
    classes: { thumbnail, thumbnailImage, thumbnailImageCover, disableLinkWhenDragging },
  } = useAnalyticsExperienceTileStyles({
    styleConfig,
    isDragging,
  });
  const { translate } = useRAQIV2TranslationDependencies();

  const experienceOverviewUrl = useMemo(
    () => dashboard.getExperienceOverviewUrl(universeId),
    [universeId],
  );

  return (
    <Link href={experienceOverviewUrl} underline='none' className={disableLinkWhenDragging}>
      <AnalyticsItemTile
        thumbnail={
          <div className={thumbnail}>
            <Thumbnail2d
              alt='alt'
              targetId={universeId}
              containerClass={thumbnailImage}
              imgClassName={thumbnailImageCover}
              type={ThumbnailTypes.universeThumbnail}
              returnPolicy={ReturnPolicy.AutoGenerated}
            />
          </div>
        }
        title={title}
        actionButton={actionButton}
        subtitle={ownerName}
        subtitleStats={
          <Grid container direction='row' spacing={1} wrap='nowrap' overflow='hidden'>
            <Grid item>
              <SubtitleStat
                Icon={ThumbUpIcon}
                value={likeRatio ? likeRatio / 100 : null}
                formattingSpec={{
                  unit: ChartUnit.WholePercentage,
                  type: ChartUnitAggregationType.Ratio,
                  context: NumberContext.CardSummary,
                }}
              />
            </Grid>
            <Grid item>
              <SubtitleStat
                Icon={PeopleIcon}
                value={playing}
                formattingSpec={{
                  unit: ChartUnit.Players,
                  type: ChartUnitAggregationType.Sum,
                  context: NumberContext.CardSummary,
                }}
              />
            </Grid>
            {updatedDate && (
              <React.Fragment>
                <Grid item>
                  <Typography variant='captionHeader' color='secondary'>
                    •
                  </Typography>
                </Grid>
                <Grid item>
                  <Typography variant='captionHeader' color='secondary' noWrap>
                    {formatDateFromNow(updatedDate, translate)}
                  </Typography>
                </Grid>
                {/* NOTE(shumingxu, 10/31/2023): There was a weird issue with this Grid container being a lot taller
              for some experiences for no clear reason. Adding an empty item here seems to fix it for now. */}
                <Grid item />
              </React.Fragment>
            )}
          </Grid>
        }
        isDataLoading={isDataLoading}
        isResponseFailed={isResponseFailed}
        isUserForbidden={isUserForbidden}
        floatingChildren={floatingChildren}
        styleConfig={styleConfig}>
        {children}
      </AnalyticsItemTile>
    </Link>
  );
};

export default AnalyticsExperienceTile;
