import type { FunctionComponent } from 'react';
import React from 'react';
import { Button } from '@rbx/foundation-ui';
import { ReturnPolicy, Thumbnail2d, ThumbnailTypes } from '@rbx/thumbnails';
import { Avatar, ChevronRightIcon, Chip, Grid, makeStyles, Typography } from '@rbx/ui';
import RoleIcon from '../../members/components/common/RoleIcon';
import { DefaultMemberRoleIdNumber } from '../../utils/constants';
import { usePermissionsTranslation } from '../providers/TranslationProvider';
import { usePermissionsUiConfig } from '../providers/UIConfigProvider';
import type { CreatorDetails } from '../utils/types';
import { CreatorTypes } from '../utils/types';

export type CreatorProps = CreatorDetails & {
  selected?: boolean;
  isOwner?: boolean;
  onCreatorSelect?: (creator: CreatorDetails) => void;
};

const useCreatorStyles = makeStyles()((theme) => ({
  clipText: {
    display: 'block',
    width: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  subText: {
    color: theme.palette.content.muted,
  },
  selectedClass: {
    background: theme.palette.states.selected,
  },
  ownerClass: {
    [`&:disabled`]: {
      color: theme.palette.content.standard,
    },
  },
}));

export const Creator: FunctionComponent<CreatorProps> = ({
  onCreatorSelect,
  selected = false,
  isOwner = false,
  ...creatorDetails
}) => {
  const {
    classes: { clipText, ownerClass, selectedClass, subText },
    cx,
  } = useCreatorStyles();
  const { translate } = usePermissionsTranslation();
  const { showMobileView } = usePermissionsUiConfig();

  let startIcon;

  switch (creatorDetails.type) {
    case CreatorTypes.MEMBER_ROLE:
    case CreatorTypes.LEGACY_ROLE:
    case CreatorTypes.GUEST_ROLE:
    case CreatorTypes.ROLE:
      startIcon = (
        <RoleIcon
          roleId={
            creatorDetails.type === CreatorTypes.MEMBER_ROLE
              ? DefaultMemberRoleIdNumber
              : Number(creatorDetails.id)
          }
          color={creatorDetails.color}
          isPrivate={creatorDetails.isPrivate}
          size='Medium'
        />
      );
      break;
    case CreatorTypes.USER:
      startIcon = (
        <Avatar variant='circular' alt={creatorDetails.name} className='size-500'>
          <Thumbnail2d
            type={ThumbnailTypes.avatar}
            targetId={Number(creatorDetails.id)}
            returnPolicy={ReturnPolicy.AutoGenerated}
            includeBackground
            alt={creatorDetails.name}
          />
        </Avatar>
      );
      break;
    case CreatorTypes.GROUP:
      startIcon = (
        <Avatar variant='rounded' alt={creatorDetails.name} className='size-500'>
          <Thumbnail2d
            type={ThumbnailTypes.groupIcon}
            targetId={Number(creatorDetails.id)}
            returnPolicy={ReturnPolicy.AutoGenerated}
            includeBackground
            alt={creatorDetails.name}
          />
        </Avatar>
      );
      break;
    default:
      startIcon = null;
  }

  return (
    <Button
      variant={selected ? 'Standard' : 'Utility'}
      size='Small'
      className={cx(
        'flex width-full !height-fit !grow-1 justify-start text-align-x-left [text-transform:none] [&>span:nth-child(2)]:grow-1 [&>span:nth-child(2)]:max-width-full [&>span:nth-child(2)]:min-width-0 [&>span:nth-child(2)>span:nth-child(1)]:width-full',
        { [selectedClass]: selected, [ownerClass]: isOwner },
      )}
      data-testid={`creator-button-${creatorDetails.id}`}
      aria-selected={selected}
      isDisabled={creatorDetails.disabled === true || isOwner}
      onClick={() => onCreatorSelect?.(creatorDetails)}>
      <Grid
        container
        className='flex width-full max-width-full no-wrap justify-between items-center padding-y-xsmall'>
        <div className='flex grow-1 flex-row items-center width-full'>
          <span className='flex grow-0 shrink-0'>{startIcon}</span>
          <span className='block text-no-wrap clip text-truncate-end grow-1 shrink-1 text-align-x-left padding-left-small'>
            <span className={clipText}>{creatorDetails.name}</span>
            <Typography variant='body2' className={cx(clipText, subText)}>
              {creatorDetails.subtext}
            </Typography>
          </span>
          {isOwner && (
            <span className='flex grow-0 shrink-0' data-testid='owner-chip'>
              <Chip
                color='secondary'
                label={translate('Chip.Owner.Label')}
                size='small'
                variant='filled'
              />
            </span>
          )}
          {showMobileView && !isOwner && (
            <span className='flex grow-0 shrink-0'>
              <ChevronRightIcon />
            </span>
          )}
        </div>
      </Grid>
    </Button>
  );
};
