import type { FunctionComponent } from 'react';
import React from 'react';
import { Icon } from '@rbx/foundation-ui';
import { ReturnPolicy, Thumbnail2d, ThumbnailTypes } from '@rbx/thumbnails';
import {
  Avatar,
  Button,
  buttonClasses,
  ChevronRightIcon,
  Chip,
  Grid,
  makeStyles,
  Typography,
  useTheme,
} from '@rbx/ui';
import { getRoleStyle } from '../../utils/groupUtils';
import { usePermissionsTranslation } from '../providers/TranslationProvider';
import { usePermissionsUiConfig } from '../providers/UIConfigProvider';
import type { CreatorDetails } from '../utils/types';
import { CreatorTypes } from '../utils/types';

export type CreatorProps = CreatorDetails & {
  selected?: boolean;
  isOwner?: boolean;
  onCreatorSelect?: (creator: CreatorDetails) => void;
};

const useCreatorStyles = makeStyles()((theme) => ({
  creatorButton: {
    textAlign: 'left',
    [`& > .${buttonClasses.startIcon}`]: {
      flex: '0 0 auto',
    },
    [`& > span`]: {
      flex: '1 1 0',
      overflow: 'hidden',
    },
    [`& > .${buttonClasses.endIcon}`]: {
      flex: '0 0 auto',
    },
  },
  clipText: {
    display: 'block',
    width: '100%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  subText: {
    color: theme.palette.content.muted,
  },
  selectedClass: {
    background: theme.palette.states.selected,
  },
  ownerClass: {
    [`&:disabled`]: {
      color: theme.palette.content.standard,
    },
  },
  buttonContent: {
    marginRight: theme.spacing(0.5),
    overflow: 'hidden',
  },
}));

export const Creator: FunctionComponent<CreatorProps> = ({
  onCreatorSelect,
  selected = false,
  isOwner = false,
  ...creatorDetails
}) => {
  const {
    classes: { creatorButton, selectedClass, clipText, ownerClass, subText, buttonContent },
    cx,
  } = useCreatorStyles();
  const { translate } = usePermissionsTranslation();
  const { showMobileView } = usePermissionsUiConfig();
  const { palette } = useTheme();

  let startIcon;

  switch (creatorDetails.type) {
    case CreatorTypes.MEMBER_ROLE:
      startIcon = (
        <Icon
          name='icon-filled-square-person'
          style={{
            width: 36,
            height: 36,
            margin: 2,
            ...getRoleStyle(creatorDetails.color, palette.mode, 'color'),
          }}
        />
      );
      break;
    case CreatorTypes.LEGACY_ROLE:
    case CreatorTypes.GUEST_ROLE:
    case CreatorTypes.ROLE:
      startIcon = (
        <Icon
          name='icon-filled-person-rectangle-horizontal-line'
          style={{
            width: 36,
            height: 36,
            margin: 2,
            ...getRoleStyle(creatorDetails.color, palette.mode, 'color'),
          }}
        />
      );
      break;
    case CreatorTypes.USER:
      startIcon = (
        <Avatar variant='circular' alt={creatorDetails.name}>
          <Thumbnail2d
            type={ThumbnailTypes.avatar}
            targetId={Number(creatorDetails.id)}
            returnPolicy={ReturnPolicy.AutoGenerated}
            includeBackground
            alt={creatorDetails.name}
          />
        </Avatar>
      );
      break;
    case CreatorTypes.GROUP:
      startIcon = (
        <Avatar variant='rounded' alt={creatorDetails.name}>
          <Thumbnail2d
            type={ThumbnailTypes.groupIcon}
            targetId={Number(creatorDetails.id)}
            returnPolicy={ReturnPolicy.AutoGenerated}
            includeBackground
            alt={creatorDetails.name}
          />
        </Avatar>
      );
      break;
    default:
      startIcon = null;
  }

  return (
    <Button
      size='large'
      color='primary'
      className={cx(creatorButton, { [selectedClass]: selected, [ownerClass]: isOwner })}
      fullWidth
      variant='text'
      data-testid={`creator-button-${creatorDetails.id}`}
      aria-selected={selected}
      disabled={creatorDetails.disabled === true || isOwner}
      onClick={() => onCreatorSelect?.(creatorDetails)}
      startIcon={startIcon}
      endIcon={showMobileView && !isOwner ? <ChevronRightIcon /> : null}>
      <Grid container direction='row' alignItems='center' wrap='nowrap'>
        <Grid item flex='1 1 0' className={buttonContent}>
          <Typography variant='largeLabel1' className={clipText}>
            {creatorDetails.name}
          </Typography>
          <Typography variant='body2' className={cx(clipText, subText)}>
            {creatorDetails.subtext}
          </Typography>
        </Grid>
        {isOwner && (
          <Grid item flex='0 0 auto' data-testid='owner-chip'>
            <Chip
              color='secondary'
              label={translate('Chip.Owner.Label')}
              size='small'
              variant='filled'
            />
          </Grid>
        )}
      </Grid>
    </Button>
  );
};
