import { FC, useCallback } from 'react';
import { Alert, AutoFixNormalIcon, Button, Tooltip, useSnackbar } from '@rbx/ui';
import { useTranslation } from '@rbx/intl';
import {
  FormattedText,
  useTranslationWrapper,
  translationKey,
} from '@modules/analytics-translations';
import { TranslationNamespace } from '@modules/miscellaneous/localization';
import { AssetType } from '@rbx/clients/assetsUploadApi';
import { useQueryClient } from '@tanstack/react-query';
import { useCurrentGame } from '@modules/providers/game/GameProvider';
import useGetAutoGeneratedThumbnailQuery from '../hooks/useGetAutoGeneratedThumbnailQuery';
import useUploadAssetForPlaceMutation from '../hooks/useUploadAssetForPlaceMutation';
import { getPlaceMediaQueryKey } from '../hooks/useGetPlaceMediaQuery';

type GenerateImageButtonProps = {
  placeId: number;
  userId: number;
  disabled?: boolean;
  tooltip?: FormattedText;
  onUploadStatusChange: (isUploading: boolean) => void;
};

const GenerateImageButton: FC<GenerateImageButtonProps> = ({
  placeId,
  userId,
  disabled,
  tooltip,
  onUploadStatusChange,
}) => {
  const { translate } = useTranslationWrapper(useTranslation());
  const queryClient = useQueryClient();
  const { enqueue } = useSnackbar();
  const { gameDetails } = useCurrentGame();

  // query generated thumbnail beforehand
  const { data, isPending } = useGetAutoGeneratedThumbnailQuery(placeId);
  const autoGeneratedImageUrl = data?.imageUrl;

  const onSuccess = useCallback(() => {
    onUploadStatusChange(false);
    queryClient.invalidateQueries({ queryKey: getPlaceMediaQueryKey(placeId) });
  }, [onUploadStatusChange, placeId, queryClient]);
  const onError = useCallback(
    (msg: string) => {
      onUploadStatusChange(false);
      enqueue({
        children: (
          <Alert variant='standard' color='error'>
            {msg}
          </Alert>
        ),
        anchorOrigin: { vertical: 'bottom', horizontal: 'right' },
      });
    },
    [enqueue, onUploadStatusChange],
  );

  const creatorType = gameDetails?.creator?.type;
  const isGroupUpload = creatorType === 'Group';
  const groupId = gameDetails?.creator?.id;

  const { uploadAssetForPlace, isUploading } = useUploadAssetForPlaceMutation(
    placeId,
    userId,
    groupId,
    isGroupUpload,
    onSuccess,
    onError,
  );

  const generateImage = useCallback(async () => {
    if (!autoGeneratedImageUrl) {
      return;
    }
    const r = await fetch(autoGeneratedImageUrl);
    const blobFile = await r.blob();
    const file = new File([blobFile], 'autoGenIcon', { type: 'image/png' });

    onUploadStatusChange(true);
    uploadAssetForPlace({ file, assetType: AssetType.Image, price: 0 });
  }, [autoGeneratedImageUrl, onUploadStatusChange, uploadAssetForPlace]);

  return (
    <Tooltip title={tooltip} arrow placement='top'>
      {/** Need to wrap Button with a <span> element because
       * Tooltip component does not work on a disabled button with pointer-event: none
       */}
      <span style={{ display: 'inline-block' }}>
        <Button
          onClick={generateImage}
          startIcon={<AutoFixNormalIcon />}
          color='secondary'
          variant='contained'
          disableRipple
          loading={isPending || isUploading}
          disabled={!autoGeneratedImageUrl || disabled}>
          {translate(
            translationKey('Label.AutoGeneratedImage', TranslationNamespace.PlaceThumbnails),
          )}
        </Button>
      </span>
    </Tooltip>
  );
};

export default GenerateImageButton;
