import type { FunctionComponent } from 'react';
import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { useTranslation } from '@rbx/intl';
import { Grid, Skeleton, BrokenImageOutlinedIcon, Typography } from '@rbx/ui';
import assetdeliveryClient from '@modules/clients/assetdelivery';
import { MediaType } from '../types';
import useMediaPreviewStyles from './MediaPreview.styles';

export type TMediaPreviewProps =
  | {
      thumbnailId: number;
      mediaId: number;
      mediaType: MediaType.AutoGeneratedImage | MediaType.Image;
      altText: string;
    }
  | {
      thumbnailId: number;
      mediaId: string;
      mediaType: MediaType.Video;
      altText: string;
    };
const MediaPreview: FunctionComponent<React.PropsWithChildren<TMediaPreviewProps>> = ({
  thumbnailId,
  mediaId,
  mediaType,
  altText,
}) => {
  const { translate } = useTranslation();
  const [error, setError] = useState<boolean>(false);
  const [mediaSrc, setMediaSrc] = useState<string | undefined>(undefined);
  const {
    classes: { previewContainer, previewContents, errorContents },
  } = useMediaPreviewStyles();
  const getMediaData = useCallback(async () => {
    setMediaSrc(undefined);
    setError(false);
    if (mediaType === MediaType.Image || mediaType === MediaType.AutoGeneratedImage) {
      try {
        const response = await assetdeliveryClient.getAssets([
          { assetId: mediaId, requestId: String(mediaId) },
        ]);
        setMediaSrc(response[0].location);
      } catch {
        setError(true);
      }
    } else {
      setMediaSrc(String(mediaId));
    }
  }, [mediaId, mediaType]);

  useEffect(() => {
    getMediaData();
    // NOTE (jcountryman, 2/22/24): Turned off to check in yotube-nocookie fix. Codeowners is
    // responsible for triaging issue.
    // eslint-disable-next-line react-hooks/exhaustive-deps -- see note above; intentional dep list
  }, [thumbnailId]);

  const content = useMemo(() => {
    if (error) {
      return (
        <Grid
          container
          item
          classes={{ root: errorContents }}
          direction='column'
          alignItems='center'
          justifyContent='center'>
          <BrokenImageOutlinedIcon />
          <Typography variant='body2'>{translate('Error.FailToLoadPreview')}</Typography>
        </Grid>
      );
    }

    if (mediaSrc && (mediaType === MediaType.Image || mediaType === MediaType.AutoGeneratedImage)) {
      return <img className={previewContents} src={mediaSrc} alt={altText} />;
    }

    if (mediaSrc && mediaType === MediaType.Video) {
      return (
        <iframe
          className={previewContents}
          src={`https://www.youtube-nocookie.com/embed/${mediaId}`}
          frameBorder='0'
          allow='autoplay; encrypted-media'
          title={`${altText} ${translate('Label.VideoPreview')}`}
        />
      );
    }
    return <Skeleton classes={{ root: previewContents }} variant='rectangular' animate />;
    // NOTE (jcountryman, 2/22/24): Turned off to check in yotube-nocookie fix. Codeowners is
    // responsible for triaging issue.
    // eslint-disable-next-line react-hooks/exhaustive-deps -- see note above; intentional dep list
  }, [mediaId, mediaSrc, mediaType, translate, thumbnailId]);

  return <div className={previewContainer}>{content}</div>;
};

export default MediaPreview;
