export const MAX_IP_LISTING_NAME_LENGTH = 255;
export const MAX_IP_LISTING_DESCRIPTION_LENGTH = 1000;
export const MAX_LICENSE_NAME_LENGTH = 255;
export const MAX_LICENSE_DESCRIPTION_LENGTH = 1000;
export const MAX_SCOPE_OF_LICENSE_LENGTH = 2000;
export const MAX_IPH_FEEDBACK_LENGTH = 250;
export const MAX_LISTING_THUMBNAIL_COUNT = 5;

export const FALLBACK_CONTENT_STANDARDS_ID = '00000000-0000-0000-0000-000000000000';

export const MS_PER_DAY = 24 * 60 * 60 * 1000;

// MUS-2487 TODO: Offload these constants to the backend
export const DAYS_FOR_CREATOR_TO_COMPLETE_CHANGE_REQUEST = 15;
export const DAYS_FOR_CREATOR_TO_RESPOND_TO_EXPIRED_CHANGE_REQUEST = 7;
export const DAYS_FOR_IPH_TO_RESPOND_TO_COMPLETED_CHANGE_REQUEST = 7;
