import React, { FunctionComponent } from 'react';
import { Grid, TextField, Typography, Avatar, makeStyles } from '@rbx/ui';
import { useTranslation } from '@rbx/intl';
import { Item, itemTypeToThumbnailType } from '@modules/miscellaneous/common';
import { useCurrentGame } from '@modules/providers/game/GameProvider';
import { Thumbnail2d, ReturnPolicy } from '@rbx/thumbnails';

export type ReceiveTransferVerificationContentProps = {
  nameVerificationText: string;
  setNameVerificationText: React.Dispatch<React.SetStateAction<string>>;
};

const useStyles = makeStyles()(() => ({
  select: {
    marginBottom: 24,
  },
  heading: {
    marginBottom: 4,
  },
  description: {
    marginBottom: 24,
  },
  groupDetail: {
    marginBottom: 24,
  },
}));

const ReceiveTransferVerificationContent: FunctionComponent<
  React.PropsWithChildren<ReceiveTransferVerificationContentProps>
> = ({ nameVerificationText, setNameVerificationText }) => {
  const { translate } = useTranslation();

  const { gameDetails, canConfigure } = useCurrentGame();

  const {
    classes: { heading, description, groupDetail },
  } = useStyles();

  return (
    <Grid container>
      <Grid container>
        <Grid item XSmall>
          <Grid container>
            <Typography variant='h6' className={heading}>
              {translate('Heading.Verification')}
            </Typography>
            <Typography variant='captionBody' color='secondary' className={description}>
              {translate('Description.VerificationAcceptance')}
            </Typography>
          </Grid>
          <Grid container alignItems='center' className={groupDetail}>
            <Avatar variant='rounded' alt='icon'>
              <Thumbnail2d
                targetId={gameDetails?.id ?? 0}
                type={itemTypeToThumbnailType[Item.Game]}
                alt={gameDetails?.name ?? ''}
                returnPolicy={canConfigure ? ReturnPolicy.AutoGenerated : ReturnPolicy.PlaceHolder}
              />
            </Avatar>
            <Typography style={{ paddingLeft: 8 }}>{gameDetails?.name}</Typography>
          </Grid>
          <TextField
            size='small'
            fullWidth
            id='verification-input'
            label={translate('Action.ExperienceName')}
            value={nameVerificationText}
            onChange={(e) => setNameVerificationText(e.target.value)}
          />
        </Grid>
      </Grid>
    </Grid>
  );
};

export default ReceiveTransferVerificationContent;
