enum RAQIV2PredefinedTabbedChartKey {
  TopSourcesAndSinksMigration = 'PREDEFINED_TABBED_CHART_TOP_SOURCES_AND_SINKS_MIGRATION',

  ImpressionsPerSource = 'PREDEFINED_TABBED_CHART_IMPRESSIONS_PER_SOURCE',
  ImpressionsPerSourceMigration = 'PREDEFINED_TABBED_CHART_IMPRESSIONS_PER_SOURCE_MIGRATION',
  PlaysPerSource = 'PREDEFINED_TABBED_CHART_PLAYS_PER_SOURCE',
  PlaysPerSourceMigration = 'PREDEFINED_TABBED_CHART_PLAYS_PER_SOURCE_MIGRATION',

  DailyActiveUsers = 'PREDEFINED_TABBED_CHART_DAILY_ACTIVE_USERS',
  EngagementSessionTime = 'PREDEFINED_TABBED_CHART_ENGAGEMENT_SESSION_TIME',

  ExperienceAnalyticsSummaryV3 = 'PREDEFINED_TABBED_CHART_EXPERIENCE_ANALYTICS_SUMMARY_V3',
  ItemRevenueAndSales = 'PREDEFINED_TABBED_CHART_ITEM_REVENUE_AND_SALES',

  StoreAssetMonetization = 'PREDEFINED_TABBED_CHART_STORE_ASSET_MONETIZATION',
}

export default RAQIV2PredefinedTabbedChartKey;
