import type { Ref } from 'react';
import React, { forwardRef } from 'react';
import type { ThumbnailRefreshRef } from '@rbx/thumbnails';
import { ReturnPolicy, Thumbnail2d, ThumbnailTypes } from '@rbx/thumbnails';
import { Grid } from '@rbx/ui';
import useOverviewContainerStyles from './OverviewContainer.styles';

export interface OverviewThumbnailContainerProps {
  type: ThumbnailTypes; // thumbnail container will style game/universe thumbnails different than other item types
  targetId?: number; // target id of entity to load thumbnail for
  alt: string; // alt string to display for thumbnail load failure
}

function OverviewThumbnailContainer(
  props: OverviewThumbnailContainerProps,
  ref: Ref<ThumbnailRefreshRef>,
) {
  const { type, targetId, alt } = props;
  const {
    classes: { overviewImgSquareContainer, overviewImgContainer, overviewImg },
  } = useOverviewContainerStyles();

  const isGameIcon =
    type === ThumbnailTypes.gameThumbnail || type === ThumbnailTypes.universeThumbnail;
  let innerThumbnailContainer = null;

  const thumbnail = (
    <Thumbnail2d
      ref={ref}
      containerClass={overviewImg}
      targetId={targetId ?? 0}
      type={type}
      alt={alt ?? ''}
      returnPolicy={ReturnPolicy.AutoGenerated}
      includeBackground
    />
  );

  if (isGameIcon) {
    innerThumbnailContainer = thumbnail;
  } else {
    innerThumbnailContainer = (
      <Grid container justifyContent='center'>
        <Grid item XSmall={8} Medium={6} Large={12}>
          {thumbnail}
        </Grid>
      </Grid>
    );
  }

  return (
    <Grid
      item
      XSmall={12}
      Large={4}
      className={isGameIcon ? overviewImgContainer : overviewImgSquareContainer}>
      {innerThumbnailContainer}
    </Grid>
  );
}
const OverviewThumbnailContainerWithRef = forwardRef(OverviewThumbnailContainer);
export default OverviewThumbnailContainerWithRef;
