import React, { forwardRef, Ref } from 'react';
import { ReturnPolicy, Thumbnail2d, ThumbnailTypes, ThumbnailRefreshRef } from '@rbx/thumbnails';
import useUniverseOverviewThumbnailStyles from './UniverseOverviewThumbnail.styles';

export type UniverseOverviewThumbnailProps = {
  universeId: number;
  universeName: string;
};

const UniverseOverviewThumbnail = (
  props: UniverseOverviewThumbnailProps,
  ref: Ref<ThumbnailRefreshRef>,
) => {
  const { classes: styles } = useUniverseOverviewThumbnailStyles();
  const { universeId, universeName } = props;
  return (
    <Thumbnail2d
      ref={ref}
      targetId={universeId}
      containerClass={styles.container}
      type={ThumbnailTypes.placeIcon}
      alt={universeName}
      returnPolicy={ReturnPolicy.AutoGenerated}
      includeBackground
    />
  );
};
const UniverseOverviewThumbnailWithRef = forwardRef(UniverseOverviewThumbnail);
export default UniverseOverviewThumbnailWithRef;
