import { resolveUrl } from '@rbx/env-utils';

/**
 * This registry is the single source of truth for all frontend client settings managed by admin site.
 * keep consistent with Roblox.Platform.ClientSettings.Properties.ClientApplications value for CreatorDashboard
 *   Prod: https://admin.simulprod.com/application-settings?groupName=Roblox.Platform.ClientSettings.Properties.ClientApplications&namePattern=CreatorDashboard
 *   Sitetest1: https://admin.sitetest1.simulpong.com/application-settings?groupName=Roblox.Platform.ClientSettings.Properties.ClientApplications&namePattern=CreatorDashboard&valuePattern=
 */
export enum FeatureFlagName {
  enableExample = 'enableExample',
  enableActivityFeedLocation = 'enableActivityFeedLocation',
  enableDeveloperSubscriptionUpdateRevShareDemo = 'enableDeveloperSubscriptionUpdateRevShareDemo',
  enableAutomaticTranslationUpdates = 'enableAutomaticTranslationUpdates',
  enableBundlePaginationOffset = 'enableBundlePaginationOffset',
  enableLocalizationCsvManagement = 'enableLocalizationCsvManagement',
  enableUENSocialMentions = 'enableUENSocialMentions',
  useNewShutdownAllInstancesEndpoint = 'useNewShutdownAllInstancesEndpoint',
  personalizationBannerWhitelist = 'personalizationBannerWhitelist',
  enableShowOnlyPublishedPlaceVersions = 'enableShowOnlyPublishedPlaceVersions',
  isOldAutomaticTextCaptureDisabled = 'isOldAutomaticTextCaptureDisabled',
  enableMeshTextureApisToggle = 'enableMeshTextureApisToggle',
  meshTextureApisUsagePolicyUrl = 'meshTextureApisUsagePolicyUrl',
  enableDevexMaintenanceBanner = 'enableDevexMaintenanceBanner',
  enablePlaceSelectForEvent = 'enablePlaceSelectForEvent',
  enableItemDelisting = 'enableItemDelisting',
  ownershipTransferCompletedTimeout = 'ownershipTransferCompletedTimeout',
  affiliateProgramAllowlist = 'affiliateProgramAllowlist',
  isAffiliateProgramEnabled = 'isAffiliateProgramEnabled',
  enablePlayerFeedback = 'enablePlayerFeedback',
  enablePlayerFeedbackUnrated = 'enablePlayerFeedbackUnrated',
  enablePlayerFeedbackCategoryResetBeforeResponse = 'enablePlayerFeedbackCategoryResetBeforeResponse',
  affiliateProgramTermsKey = 'affiliateProgramTermsKey',
  migrateAssetPermissionsParams = 'migrateAssetPermissionsParams',
  affiliateLinkGADataAllowlist = 'affiliateLinkGADataAllowlist',
  enableUseStudioEditPlaceLauncherWithPrelaunch = 'enableUseStudioEditPlaceLauncherWithPrelaunch',
  allowUpdatingBundleName = 'allowUpdatingBundleName',
  disableJuneNinthLaunchAnnouncementRegionalPricing = 'disableJuneNinthLaunchAnnouncementRegionalPricing',
  enableEnvironments = 'enableEnvironments',
  enableYourPlaceCreation = 'enableYourPlaceCreation',
  enableYourPlaceCreationExperimentDate = 'enableYourPlaceCreationExperimentDate',
  enableScopeSelectionCategoryWarning = 'enableScopeSelectionCategoryWarning',
  enableGroupOwnershipTransferV2 = 'enableGroupOwnershipTransferV2',
  enableCreatorControlsAgeGate = 'enableCreatorControlsAgeGate',
  enableCreatorControlsGeoGate = 'enableCreatorControlsGeoGate',
  enableCreatorRewards = 'enableCreatorRewards',
  creatorRewardsAllowlist = 'creatorRewardsAllowlist',
  enableGroupInvitationsTelemetry = 'enableGroupInvitationsTelemetry',
  unratedExperienceBannerLink = 'unratedExperienceBannerLink',
  enableTargetPartWildcards = 'enableTargetPartWildcards',
  enableChildLocaleSupport = 'enableChildLocaleSupport',
  enableRentables = 'enableRentables',
  rentablesPostLaunchWhitelist = 'rentablesPostLaunchWhitelist',
  enableContentMaturity18Plus = 'enableContentMaturity18Plus',
  enableMakeupAssets = 'enableMakeupAssets',
  enableFirstPayoutWarning = 'enableFirstPayoutWarning',
  enableQuestionnaireHelpDialog = 'enableQuestionnaireHelpDialog',
  enableAgeVerificationUpsellBanner = 'enableAgeVerificationUpsellBanner',
  ageVerificationUpsellBannerStartDate = 'ageVerificationUpsellBannerStartDate',
  ageVerificationUpsellBannerEndDate = 'ageVerificationUpsellBannerEndDate',
  ageVerificationUpsellBannerHighPriorityDate = 'ageVerificationUpsellBannerHighPriorityDate',
  ageVerificationUpsellGetStartedUrl = 'ageVerificationUpsellGetStartedUrl',
  ageVerificationUpsellViewDetailsUrl = 'ageVerificationUpsellViewDetailsUrl',
  serverManagementDevAllowlist = 'serverManagementDevAllowlist',
  enableGPCFooter = 'enableGPCFooter',
  enableSignalRCrossTab = 'enableSignalRCrossTab',
  enableImageTranslationEnrollment = 'enableImageTranslationEnrollment',
  showTaxonomyOnAvatarItemAnalyticsTab = 'showTaxonomyOnAvatarItemAnalyticsTab',
  enableSecureTeleports = 'enableSecureTeleports',
  serverManagementIncreaseRestartDelay = 'serverManagementIncreaseRestartDelay',
  serverManagementCustomPayloadReady = 'serverManagementCustomPayloadReady',
  serverManagementShowShutdownServers = 'serverManagementShowShutdownServers',
  establishTrustUpsellGetStartedUrl = 'establishTrustUpsellGetStartedUrl',
  establishTrustUpsellViewDetailsUrl = 'establishTrustUpsellViewDetailsUrl',
  starterPlaceTemplateId = 'starterPlaceTemplateId',
  enableTalentHubV2 = 'enableTalentHubV2',
  enableTalentHubV2M2 = 'enableTalentHubV2M2',
  enablePlaceModerationCheckBeforeStudioOpen = 'enablePlaceModerationCheckBeforeStudioOpen',
  enableIpPlatformConditionalOffers = 'enableIpPlatformConditionalOffers',
  impactedBannerScoutMaxPages = 'impactedBannerScoutMaxPages',
  impactedExperiencesDevForumUrl = 'impactedExperiencesDevForumUrl',
  impactedExperiencesAgeLearnMoreUrl = 'impactedExperiencesAgeLearnMoreUrl',
  enableGroupModerationPage = 'enableGroupModerationPage',
  impactedExperiencesMaxUniverseIds = 'impactedExperiencesMaxUniverseIds',
  isHdEnabled = 'isHdEnabled',
  enableReducedMarketplaceVisibilityBanner = 'enableReducedMarketplaceVisibilityBanner',
  enableCoreContentGatedBanner = 'enableCoreContentGatedBanner',
  publishEligibilityDevForumUrl = 'publishEligibilityDevForumUrl',
  enableAudioUploadRevamp = 'enableAudioUploadRevamp',
  enableRtbfSetting = 'enableRtbfSetting',
  rtbfSettingAllowlist = 'rtbfSettingAllowlist',
  enableAvatarAnimations = 'enableAvatarAnimations',
  enableAvatarBackgrounds = 'enableAvatarBackgrounds',
  freeAvatarDocumentationUrl = 'freeAvatarDocumentationUrl',
  enableIpPlatformDecoupleListingCreationFromLicenseCreation = 'enableIpPlatformDecoupleListingCreationFromLicenseCreation',
  serverManagementShowServerLogs = 'serverManagementShowServerLogs',
  enable2D3DUnificationBanner = 'enable2D3DUnificationBanner',
  unification2D3DBannerLearnMoreUrl = 'unification2D3DBannerLearnMoreUrl',
  enableDemoMode = 'enableDemoMode',
  enableDataStoreRequestSourceAnalytics = 'enableDataStoreRequestSourceAnalytics',
  enableIpPlatformMatchesTableEsIndexImprovements = 'enableIpPlatformMatchesTableEsIndexImprovements',
}

export type FeatureFlagValue = string | number | boolean;

// Helper preserves literal value types per key and enforces all enum keys are present
const defineFeatureFlagDefaults = <T extends { readonly [K in FeatureFlagName]: FeatureFlagValue }>(
  t: T,
) => t;

export const featureFlagDefaults = defineFeatureFlagDefaults({
  [FeatureFlagName.enableExample]: false,
  [FeatureFlagName.enableActivityFeedLocation]: false,
  [FeatureFlagName.enableDeveloperSubscriptionUpdateRevShareDemo]: false,
  [FeatureFlagName.enableAutomaticTranslationUpdates]: false,
  [FeatureFlagName.enableBundlePaginationOffset]: true,
  [FeatureFlagName.enableLocalizationCsvManagement]: false,
  [FeatureFlagName.enableUENSocialMentions]: false,
  [FeatureFlagName.useNewShutdownAllInstancesEndpoint]: false,
  [FeatureFlagName.personalizationBannerWhitelist]: '',
  [FeatureFlagName.enableShowOnlyPublishedPlaceVersions]: false,
  [FeatureFlagName.isOldAutomaticTextCaptureDisabled]: false,
  [FeatureFlagName.enableMeshTextureApisToggle]: false,
  [FeatureFlagName.meshTextureApisUsagePolicyUrl]: resolveUrl(
    'creatorsRestrictionsOnUse',
    process.env.targetEnvironment,
    process.env.buildTarget,
  ),
  [FeatureFlagName.enableDevexMaintenanceBanner]: false,
  [FeatureFlagName.enablePlaceSelectForEvent]: false,
  [FeatureFlagName.enableItemDelisting]: false,
  [FeatureFlagName.ownershipTransferCompletedTimeout]: 60,
  [FeatureFlagName.affiliateProgramAllowlist]: '',
  [FeatureFlagName.isAffiliateProgramEnabled]: false,
  [FeatureFlagName.enablePlayerFeedback]: false,
  [FeatureFlagName.enablePlayerFeedbackUnrated]: false,
  [FeatureFlagName.enablePlayerFeedbackCategoryResetBeforeResponse]: false,
  [FeatureFlagName.affiliateProgramTermsKey]: '',
  [FeatureFlagName.migrateAssetPermissionsParams]: false,
  [FeatureFlagName.affiliateLinkGADataAllowlist]: '',
  [FeatureFlagName.enableUseStudioEditPlaceLauncherWithPrelaunch]: false,
  [FeatureFlagName.allowUpdatingBundleName]: false,
  [FeatureFlagName.disableJuneNinthLaunchAnnouncementRegionalPricing]: false,
  [FeatureFlagName.enableEnvironments]: false,
  [FeatureFlagName.enableYourPlaceCreation]: false,
  [FeatureFlagName.enableYourPlaceCreationExperimentDate]: new Date('2025-09-23').toISOString(),
  [FeatureFlagName.enableScopeSelectionCategoryWarning]: false,
  [FeatureFlagName.enableGroupOwnershipTransferV2]: false,
  [FeatureFlagName.enableCreatorControlsAgeGate]: false,
  [FeatureFlagName.enableCreatorControlsGeoGate]: false,
  [FeatureFlagName.enableCreatorRewards]: false,
  [FeatureFlagName.creatorRewardsAllowlist]: '',
  [FeatureFlagName.enableGroupInvitationsTelemetry]: false,
  [FeatureFlagName.unratedExperienceBannerLink]: '',
  [FeatureFlagName.enableTargetPartWildcards]: false,
  [FeatureFlagName.enableChildLocaleSupport]: false,
  [FeatureFlagName.enableRentables]: false,
  [FeatureFlagName.rentablesPostLaunchWhitelist]: '',
  [FeatureFlagName.enableContentMaturity18Plus]: false,
  [FeatureFlagName.enableMakeupAssets]: false,
  [FeatureFlagName.enableFirstPayoutWarning]: false,
  [FeatureFlagName.enableQuestionnaireHelpDialog]: false,

  [FeatureFlagName.enableAgeVerificationUpsellBanner]: false,
  [FeatureFlagName.ageVerificationUpsellBannerStartDate]: new Date('2025-12-03').toISOString(),
  [FeatureFlagName.ageVerificationUpsellBannerEndDate]: new Date('2026-06-01').toISOString(),
  [FeatureFlagName.ageVerificationUpsellBannerHighPriorityDate]: new Date(
    '2026-01-21',
  ).toISOString(),
  [FeatureFlagName.ageVerificationUpsellGetStartedUrl]:
    'https://www.roblox.com/my/account?creatorCollaboration',
  [FeatureFlagName.ageVerificationUpsellViewDetailsUrl]:
    'https://devforum.roblox.com/t/age-check-notifications-in-studio-and-creator-hub/4117693',
  [FeatureFlagName.serverManagementDevAllowlist]: '',
  [FeatureFlagName.enableGPCFooter]: false,
  [FeatureFlagName.enableSignalRCrossTab]: false,
  [FeatureFlagName.enableImageTranslationEnrollment]: false,
  [FeatureFlagName.showTaxonomyOnAvatarItemAnalyticsTab]: false,
  [FeatureFlagName.enableSecureTeleports]: false,
  [FeatureFlagName.serverManagementIncreaseRestartDelay]: false,
  [FeatureFlagName.serverManagementCustomPayloadReady]: false,
  [FeatureFlagName.serverManagementShowShutdownServers]: false,
  [FeatureFlagName.establishTrustUpsellGetStartedUrl]:
    'https://www.roblox.com/my/account?creatorCollaboration',
  [FeatureFlagName.establishTrustUpsellViewDetailsUrl]:
    'https://devforum.roblox.com/t/age-check-notifications-in-studio-and-creator-hub/4117693',
  [FeatureFlagName.starterPlaceTemplateId]: 102012632106276,
  [FeatureFlagName.enableTalentHubV2]: false,
  [FeatureFlagName.enableTalentHubV2M2]: false,
  [FeatureFlagName.enablePlaceModerationCheckBeforeStudioOpen]: false,
  [FeatureFlagName.enableIpPlatformConditionalOffers]: false,
  [FeatureFlagName.impactedBannerScoutMaxPages]: 8,
  [FeatureFlagName.impactedExperiencesDevForumUrl]: 'https://devforum.roblox.com/',
  [FeatureFlagName.impactedExperiencesAgeLearnMoreUrl]:
    'https://en.help.roblox.com/hc/en-us/articles/39143693116052-Understanding-Age-Checks-on-Roblox',
  [FeatureFlagName.enableGroupModerationPage]: false,
  [FeatureFlagName.impactedExperiencesMaxUniverseIds]: 3,
  [FeatureFlagName.isHdEnabled]: false,
  [FeatureFlagName.enableReducedMarketplaceVisibilityBanner]: false,
  [FeatureFlagName.enableCoreContentGatedBanner]: false,
  [FeatureFlagName.publishEligibilityDevForumUrl]: '',
  [FeatureFlagName.enableAudioUploadRevamp]: false,
  [FeatureFlagName.enableRtbfSetting]: false,
  [FeatureFlagName.rtbfSettingAllowlist]: '',
  [FeatureFlagName.enableAvatarAnimations]: false,
  [FeatureFlagName.enableAvatarBackgrounds]: false,
  [FeatureFlagName.freeAvatarDocumentationUrl]: '#',
  [FeatureFlagName.enableIpPlatformDecoupleListingCreationFromLicenseCreation]: false,
  [FeatureFlagName.serverManagementShowServerLogs]: false,
  [FeatureFlagName.enable2D3DUnificationBanner]: false,
  [FeatureFlagName.unification2D3DBannerLearnMoreUrl]: '',
  [FeatureFlagName.enableDemoMode]: false,
  [FeatureFlagName.enableDataStoreRequestSourceAnalytics]: false,
  [FeatureFlagName.enableIpPlatformMatchesTableEsIndexImprovements]: false,
} as const);
