import { useQuery } from '@tanstack/react-query';
import {
  V1PlacesGameiconsGetFormatEnum as GetPlaceIconFormatEnum,
  V1PlacesGameiconsGetIsCircularEnum as GetPlaceIconIsCircularEnum,
  V1PlacesGameiconsGetReturnPolicyEnum as GetPlaceIconReturnPolicyEnum,
  V1PlacesGameiconsGetSizeEnum as GetPlaceIconSizeEnum,
} from '@rbx/clients/thumbnails';
import { getThumbnailsClient } from '@rbx/thumbnails';

const getAutoGeneratedThumbnailQueryKey = (placeId: number) =>
  ['getAutoGeneratedThumbnail', placeId] as const;

function useGetAutoGeneratedThumbnailQuery(placeId: number) {
  return useQuery({
    queryKey: getAutoGeneratedThumbnailQueryKey(placeId),
    queryFn: async () => {
      const thumbnailsClient = getThumbnailsClient();
      const res = await thumbnailsClient.getPlaceIcons(
        [placeId],
        GetPlaceIconReturnPolicyEnum.ForceAutoGenerated,
        // eslint-disable-next-line no-underscore-dangle -- enum type is specified with an underscore
        GetPlaceIconSizeEnum._512x512,
        GetPlaceIconFormatEnum.Png,
        GetPlaceIconIsCircularEnum.False,
      );
      return res.data?.[0];
    },
  });
}

export default useGetAutoGeneratedThumbnailQuery;
