import { useMutation, useQuery } from '@tanstack/react-query';
import { useMemo } from 'react';
import { useTranslation } from '@rbx/intl';
import { useAuthentication } from '@modules/authentication/providers';
import { SetAutoGeneratedPlaceIconErrorCodes } from '@modules/clients/develop';
import experienceGuidelinesServiceApiClient from '@modules/clients/experienceGuidelinesService';
import { getErrorCode } from '@modules/clients/utils/errorHelpers';
import { CONTENT_RESTRICTED } from '@modules/experience-guidelines/hooks/useCreatorEligibility';
import { PublishError } from '@modules/miscellaneous/common';
import { getEnumKeyByValue } from '@modules/miscellaneous/utils';
import { useCurrentGame } from '@modules/providers/game/GameProvider';
import {
  setDefaultPlaceIcon,
  setAutogeneratedPlaceIcon,
  setUploadedPlaceIconNew,
} from '../../placeThumbnails/utils/placeThumbnailsHelper';

const queryPrefix = 'CreationsPlaceIcon';

export const useIsContentRestrictedExperience = (universeId: number) => {
  return useQuery({
    queryKey: [queryPrefix, 'CheckIsSeventeenPlus', universeId],
    queryFn: async () => {
      return experienceGuidelinesServiceApiClient.getDetailedGuidelines(universeId);
    },
    select(response) {
      return (
        response.ageRecommendationDetails?.ageRecommendationSummary?.ageRecommendation
          ?.contentMaturity === CONTENT_RESTRICTED
      );
    },
    enabled: Boolean(universeId),
  });
};

export const useUploadPlaceIconMutation = (
  placeId: number,
  onSuccess?: () => void,
  onError?: (msg: string) => void,
) => {
  const { gameDetails } = useCurrentGame();
  const creatorType = gameDetails?.creator?.type;
  const isGroupUpload = creatorType === 'Group';
  const groupId = gameDetails?.creator?.id;

  const { translate } = useTranslation();
  const { user } = useAuthentication();
  const {
    mutate: uploadPlaceIcon,
    mutateAsync: uploadPlaceIconAsync,
    isPending: isUploading,
  } = useMutation({
    mutationFn: async (fileBlob: Blob) => {
      await setUploadedPlaceIconNew(placeId, fileBlob, isGroupUpload, user?.id, groupId);
    },
    onSuccess,
    onError(e) {
      const code = getErrorCode(e);
      const nameOfError = getEnumKeyByValue(PublishError, code);
      const errMsg = translate(`Error.${nameOfError}`) || translate('Error.UnknownError');
      onError?.(errMsg);
    },
  });

  return useMemo(
    () => ({
      uploadPlaceIcon,
      uploadPlaceIconAsync,
      isUploading,
    }),
    [isUploading, uploadPlaceIcon, uploadPlaceIconAsync],
  );
};

export const useUploadAutoGeneratedIconMutation = (
  placeId: number,
  onSuccess?: () => void,
  onError?: (msg: string) => void,
) => {
  const { gameDetails } = useCurrentGame();
  const creatorType = gameDetails?.creator?.type;
  const isGroupUpload = creatorType === 'Group';
  const groupId = gameDetails?.creator?.id;

  const { translate } = useTranslation();
  const { user } = useAuthentication();
  const {
    mutate: uploadAutoGeneratedIcon,
    mutateAsync: uploadAutoGeneratedIconAsync,
    isPending: isUploading,
  } = useMutation({
    mutationFn: async (autoGenIconImageUrl: string) => {
      await setAutogeneratedPlaceIcon(
        placeId,
        autoGenIconImageUrl,
        isGroupUpload,
        user?.id,
        groupId,
      );
    },
    onSuccess,
    onError(e) {
      const errorMsgKey =
        getErrorCode(e) === SetAutoGeneratedPlaceIconErrorCodes.UpdatedTooOften
          ? 'Error.UpdatedTooOften'
          : 'Error.UnknownError';
      onError?.(translate(errorMsgKey));
    },
  });

  return useMemo(
    () => ({
      uploadAutoGeneratedIcon,
      uploadAutoGeneratedIconAsync,
      isUploading,
    }),
    [isUploading, uploadAutoGeneratedIcon, uploadAutoGeneratedIconAsync],
  );
};

export const useSetDefaultIconMutation = (
  placeId: number,
  onSuccess?: () => void,
  onError?: (msg: string) => void,
) => {
  const { translate } = useTranslation();
  const {
    mutate: setDefaultIcon,
    mutateAsync: setDefaultIconAsync,
    isPending: isSettingDefault,
  } = useMutation({
    mutationFn: async () => {
      await setDefaultPlaceIcon(placeId);
    },
    onSuccess,
    onError(e) {
      const errorMsgKey =
        getErrorCode(e) === SetAutoGeneratedPlaceIconErrorCodes.UpdatedTooOften
          ? 'Error.UpdatedTooOften'
          : 'Error.UnknownError';
      onError?.(translate(errorMsgKey));
    },
  });

  return useMemo(
    () => ({
      setDefaultIcon,
      setDefaultIconAsync,
      isSettingDefault,
    }),
    [isSettingDefault, setDefaultIcon, setDefaultIconAsync],
  );
};
