import type { FC } from 'react';
import { useState, useCallback, useMemo, useEffect, useRef } from 'react';
import { useTranslation } from '@rbx/intl';
import { ReturnPolicy, ThumbnailTypes } from '@rbx/thumbnails';
import {
  AutoFixNormalIcon,
  Button,
  CollectionsIcon,
  DialogTemplate,
  Grid,
  ImageIcon,
  Typography,
  useDialog,
} from '@rbx/ui';
import emptyFunction from '@modules/experience-analytics-shared/emptyFunction';
import { FileUploadBase } from '@modules/miscellaneous/components';
import { Flex } from '@modules/miscellaneous/components/Flex';
import useThumbnailImage from '@modules/miscellaneous/components/ThumbnailImage/useThumbnailImage';
import { cropImageToSquare } from '@modules/miscellaneous/utils/imageUtils';
import useGetAutoGeneratedThumbnailQuery from '../../placeThumbnails/hooks/useGetAutoGeneratedThumbnailQuery';
import {
  useIsContentRestrictedExperience,
  useSetDefaultIconMutation,
  useUploadAutoGeneratedIconMutation,
  useUploadPlaceIconMutation,
} from '../hooks/usePlaceIconQueries';
import IconCandidateButton from './IconCandidateButton';
import usePlaceIconFormStyles from './PlaceIconForm.styles';
import { PlaceIconImageTypes } from './types';

const acceptMimeTypes = PlaceIconImageTypes.map((type) => `image/${type}`);

enum CandidateType {
  Image = 'image',
  AutoGenerated = 'autoGenerated',
  Placeholder = 'placeholder',
}

type ImageUploadCandidate = {
  type: CandidateType.Image;
  file: File;
};

type AutoGeneratedCandidate = {
  type: CandidateType.AutoGenerated;
  imageUrl: string;
};
type PlaceHolderCandidate = {
  type: CandidateType.Placeholder;
  imageUrl: string;
};

type IconCandidate = {
  type: CandidateType;
} & (ImageUploadCandidate | AutoGeneratedCandidate | PlaceHolderCandidate);

type PlaceIconFormV2Props = { universeId: number; placeId: number };

const PlaceIconFormV2: FC<PlaceIconFormV2Props> = ({ universeId, placeId }) => {
  const {
    classes: { placeIconContainer, iconCandidateImageContainer },
  } = usePlaceIconFormStyles();
  const { translate } = useTranslation();
  const { open, close, configure } = useDialog();
  const { data: isContentRestricted } = useIsContentRestrictedExperience(universeId);
  const { data } = useGetAutoGeneratedThumbnailQuery(placeId);
  const autoGeneratedImageUrl = data?.imageUrl;

  const { thumbnailData: autoGeneratedData } = useThumbnailImage({
    targetId: placeId,
    targetType: ThumbnailTypes.placeIcon,
    returnPolicy: ReturnPolicy.ForceAutoGenerated,
    fontColor: 'dark',
  });
  const { thumbnailData: placeHolderData } = useThumbnailImage({
    targetId: placeId,
    targetType: ThumbnailTypes.placeIcon,
    returnPolicy: ReturnPolicy.ForcePlaceHolder,
    fontColor: 'dark',
  });
  const { thumbnailData: currentIconData, refreshThumbnail } = useThumbnailImage({
    targetId: placeId,
    targetType: ThumbnailTypes.placeIcon,
    returnPolicy: ReturnPolicy.PlaceHolder,
    fontColor: 'dark',
    isStatusTextShown: true,
  });

  const [iconCandidate, setIconCandidate] = useState<IconCandidate | null>(null);
  const setImageUploadCandidate = useCallback((files: FileList | null) => {
    if (files?.length) {
      setIconCandidate({ type: CandidateType.Image, file: files[0] });
    }
  }, []);
  const setAutoGeneratedCandidate = useCallback(() => {
    if (autoGeneratedImageUrl) {
      setIconCandidate({ type: CandidateType.AutoGenerated, imageUrl: autoGeneratedImageUrl });
    }
  }, [autoGeneratedImageUrl]);
  const setPlaceHolderCandidate = useCallback(() => {
    if (placeHolderData?.imageUrl) {
      setIconCandidate({ type: CandidateType.Placeholder, imageUrl: placeHolderData.imageUrl });
    }
  }, [placeHolderData?.imageUrl]);

  const imageUrl = useMemo(() => {
    if (!iconCandidate) {
      return currentIconData?.imageUrl;
    }
    switch (iconCandidate.type) {
      case CandidateType.Image:
        return URL.createObjectURL(iconCandidate.file);
      case CandidateType.AutoGenerated:
      case CandidateType.Placeholder:
        return iconCandidate.imageUrl;
      default: {
        const exhaustiveCheck: never = iconCandidate;
        throw new Error(`Unhandled icon candidate type: ${String(exhaustiveCheck)}`);
      }
    }
  }, [currentIconData?.imageUrl, iconCandidate]);

  // For newly uploaded icon, it might stuck in pending or review state for some time.
  // If that happens, we will refresh the thumbnail every 5 seconds until it's completed.
  const refreshTimer = useRef<NodeJS.Timeout | null>(null);
  useEffect(() => {
    // If currentIconData is not available.
    // It means the icon is either not uploaded or not fetched yet.
    if (!currentIconData) {
      if (refreshTimer.current) {
        clearInterval(refreshTimer.current);
      }
      refreshTimer.current = null;
      return emptyFunction;
    }

    const { state } = currentIconData;
    if (state === 'InReview' || state === 'Pending') {
      refreshTimer.current ??= setInterval(() => {
        void refreshThumbnail();
      }, 5000);
    } else if (refreshTimer.current) {
      clearInterval(refreshTimer.current);
      refreshTimer.current = null;
    }
    return () => {
      if (refreshTimer.current) {
        clearInterval(refreshTimer.current);
        refreshTimer.current = null;
      }
    };
  }, [currentIconData, iconCandidate, refreshThumbnail]);

  const onCancel = useCallback(() => {
    setIconCandidate(null);
  }, []);

  const [isRefreshingOnSuccessfulUpload, setIsRefreshingOnSuccessfulUpload] = useState(false);
  const onSuccess = useCallback(() => {
    setIsRefreshingOnSuccessfulUpload(true);
    void refreshThumbnail()
      .then(() => {
        setIconCandidate(null);
      })
      .finally(() => {
        setIsRefreshingOnSuccessfulUpload(false);
      });
  }, [refreshThumbnail]);

  const uploadButtonRef = useRef<HTMLButtonElement>(null);
  const onError = useCallback(() => {
    configure(
      <DialogTemplate
        title={translate('Title.UploadImageFailed' /** PlaceThumbnails */)}
        content={translate('Description.UploadImageFailed', {
          formats: acceptMimeTypes.map((mime) => `*.${mime.split('/')[1]}`).join(', '),
        })}
        confirmText={translate('Action.UploadImage' /** Controls */)}
        cancelText={translate('Action.Cancel' /** Controls */)}
        onConfirm={() => {
          uploadButtonRef.current?.click();
          close();
        }}
        onCancel={close}
      />,
    );
    open();
  }, [close, configure, open, translate]);

  const { uploadPlaceIcon, isUploading: isUploadingPlaceIcon } = useUploadPlaceIconMutation(
    placeId,
    onSuccess,
    onError,
  );
  const { uploadAutoGeneratedIcon, isUploading: isUploadingAutoGeneratedIcon } =
    useUploadAutoGeneratedIconMutation(placeId, onSuccess, undefined);
  const { setDefaultIcon, isSettingDefault } = useSetDefaultIconMutation(
    placeId,
    onSuccess,
    undefined,
  );

  const onSave = useCallback(async () => {
    if (iconCandidate?.type === CandidateType.Image) {
      const square = await cropImageToSquare(iconCandidate.file);
      uploadPlaceIcon(square);
    } else if (iconCandidate?.type === CandidateType.AutoGenerated) {
      uploadAutoGeneratedIcon(iconCandidate.imageUrl);
    } else if (iconCandidate?.type === CandidateType.Placeholder) {
      setDefaultIcon();
    } else {
      /* empty */
    }
  }, [iconCandidate, setDefaultIcon, uploadAutoGeneratedIcon, uploadPlaceIcon]);

  const isUploading = isUploadingPlaceIcon || isUploadingAutoGeneratedIcon || isSettingDefault;
  return (
    <Grid container classes={{ root: placeIconContainer }}>
      <Grid item XSmall={12}>
        <Typography variant='body1' display='block' color='secondary' marginTop='8px'>
          {translate('Description.Icon' /** CreatorDashboard.Places */)}
        </Typography>
      </Grid>
      <Grid item XSmall={12}>
        <Flex gap={8}>
          <FileUploadBase onChange={setImageUploadCandidate} accept={acceptMimeTypes.join(', ')}>
            {(onClick: () => void) => (
              <IconCandidateButton
                ref={uploadButtonRef}
                startIcon={<CollectionsIcon />}
                onClick={onClick}
                disabled={isUploading}
                label={translate('Action.UploadImage' /** Controls */)}
              />
            )}
          </FileUploadBase>
          <IconCandidateButton
            onClick={setAutoGeneratedCandidate}
            label={translate('Label.AutoGenerated')}
            startIcon={<AutoFixNormalIcon />}
            disabled={isContentRestricted === true || !autoGeneratedData?.imageUrl || isUploading}
          />
          <IconCandidateButton
            onClick={setPlaceHolderCandidate}
            label={translate('Label.Placeholder')}
            startIcon={<ImageIcon />}
            disabled={isUploading}
          />
        </Flex>
      </Grid>
      <Grid item XSmall={12}>
        <div
          className={iconCandidateImageContainer}
          style={{
            backgroundImage: `url(${imageUrl})`,
          }}
          role='img'
        />
      </Grid>
      <Grid item XSmall={12}>
        <Flex gap={8}>
          <Button
            data-testid='cancel-button'
            variant='outlined'
            color='primary'
            disabled={!iconCandidate || isUploading || isRefreshingOnSuccessfulUpload}
            onClick={onCancel}>
            {translate('Label.Cancel')}
          </Button>
          <Button
            data-testid='save-icon-button'
            variant='contained'
            disabled={!iconCandidate || isRefreshingOnSuccessfulUpload}
            onClick={onSave}
            loading={isUploading}>
            {translate('Label.Save')}
          </Button>
        </Flex>
      </Grid>
    </Grid>
  );
};

export default PlaceIconFormV2;
