import { FC, useState, useCallback, useMemo, useEffect, useRef } from 'react';
import {
  AutoFixNormalIcon,
  Button,
  CollectionsIcon,
  DialogTemplate,
  Grid,
  ImageIcon,
  Typography,
  useDialog,
} from '@rbx/ui';
import { useTranslation } from '@rbx/intl';
import { Flex } from '@modules/miscellaneous/common/components';
import { FileUploadBase } from '@modules/miscellaneous/common';
import useThumbnailImage from '@modules/miscellaneous/common/components/ThumbnailImage/useThumbnailImage';
import { ReturnPolicy, ThumbnailTypes } from '@rbx/thumbnails';
import { emptyFunction } from '@modules/experience-analytics-shared';
import useGetAutoGeneratedThumbnailQuery from '../../placeThumbnails/hooks/useGetAutoGeneratedThumbnailQuery';
import usePlaceIconFormStyles from './PlaceIconForm.styles';
import {
  useIsContentRestrictedExperience,
  useSetDefaultIconMutation,
  useUploadAutoGeneratedIconMutation,
  useUploadPlaceIconMutation,
} from '../hooks/usePlaceIconQueries';
import IconCandidateButton from './IconCandidateButton';
import { PlaceIconImageTypes } from './types';

// Function to crop the uploaded image to a square
function cropImageToSquare(file: File): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    const reader = new FileReader();

    // Read the file as a data URL
    reader.readAsDataURL(file);

    reader.onload = function readerOnLoad(event) {
      img.src = event.target?.result as string;
    };

    img.onload = function imageOnLoad() {
      const canvas = document.createElement('canvas');
      const ctx = canvas.getContext('2d');

      if (!ctx) {
        reject(new Error('Failed to get canvas 2D context.'));
        return;
      }

      // Calculate the size of the square
      const size = Math.min(img.width, img.height);

      // Set the canvas size to the square size
      canvas.width = size;
      canvas.height = size;

      // Calculate the cropping offsets to center the square
      const offsetX = (img.width - size) / 2;
      const offsetY = (img.height - size) / 2;

      // Draw the square portion of the image onto the canvas
      ctx.drawImage(img, offsetX, offsetY, size, size, 0, 0, size, size);

      // Convert the canvas to a Blob (or use toDataURL if needed)
      canvas.toBlob((blob) => {
        if (blob) {
          resolve(blob); // Return the cropped image as a Blob
        } else {
          reject(new Error('Failed to convert canvas to Blob.'));
        }
      }, 'image/jpeg');
    };

    img.onerror = function imageOnError() {
      reject(new Error('Failed to load image.'));
    };
  });
}

const acceptMimeTypes = PlaceIconImageTypes.map((type) => `image/${type}`);

enum CandidateType {
  Image = 'image',
  AutoGenerated = 'autoGenerated',
  Placeholder = 'placeholder',
}

type ImageUploadCandidate = {
  type: CandidateType.Image;
  file: File;
};

type AutoGeneratedCandidate = {
  type: CandidateType.AutoGenerated;
  imageUrl: string;
};
type PlaceHolderCandidate = {
  type: CandidateType.Placeholder;
  imageUrl: string;
};

type IconCandidate = {
  type: CandidateType;
} & (ImageUploadCandidate | AutoGeneratedCandidate | PlaceHolderCandidate);

type PlaceIconFormV2Props = { universeId: number; placeId: number };

const PlaceIconFormV2: FC<PlaceIconFormV2Props> = ({ universeId, placeId }) => {
  const {
    classes: { placeIconContainer, iconCandidateImageContainer },
  } = usePlaceIconFormStyles();
  const { translate } = useTranslation();
  const { open, close, configure } = useDialog();
  const { data: isContentRestricted } = useIsContentRestrictedExperience(universeId);
  const { data } = useGetAutoGeneratedThumbnailQuery(placeId);
  const autoGeneratedImageUrl = data?.imageUrl;

  const { thumbnailData: autoGeneratedData } = useThumbnailImage({
    targetId: placeId,
    targetType: ThumbnailTypes.placeIcon,
    returnPolicy: ReturnPolicy.ForceAutoGenerated,
    fontColor: 'dark',
  });
  const { thumbnailData: placeHolderData } = useThumbnailImage({
    targetId: placeId,
    targetType: ThumbnailTypes.placeIcon,
    returnPolicy: ReturnPolicy.ForcePlaceHolder,
    fontColor: 'dark',
  });
  const { thumbnailData: currentIconData, refreshThumbnail } = useThumbnailImage({
    targetId: placeId,
    targetType: ThumbnailTypes.placeIcon,
    returnPolicy: ReturnPolicy.PlaceHolder,
    fontColor: 'dark',
    isStatusTextShown: true,
  });

  const [iconCandidate, setIconCandidate] = useState<IconCandidate | null>(null);
  const setImageUploadCandidate = useCallback((files: FileList | null) => {
    if (files?.length) {
      setIconCandidate({ type: CandidateType.Image, file: files[0] });
    }
  }, []);
  const setAutoGeneratedCandidate = useCallback(() => {
    if (autoGeneratedImageUrl) {
      setIconCandidate({ type: CandidateType.AutoGenerated, imageUrl: autoGeneratedImageUrl });
    }
  }, [autoGeneratedImageUrl]);
  const setPlaceHolderCandidate = useCallback(() => {
    if (placeHolderData?.imageUrl) {
      setIconCandidate({ type: CandidateType.Placeholder, imageUrl: placeHolderData.imageUrl });
    }
  }, [placeHolderData?.imageUrl]);

  const imageUrl = useMemo(() => {
    if (!iconCandidate) {
      return currentIconData?.imageUrl;
    }
    switch (iconCandidate.type) {
      case CandidateType.Image:
        return URL.createObjectURL(iconCandidate.file);
      case CandidateType.AutoGenerated:
      case CandidateType.Placeholder:
        return iconCandidate.imageUrl;
      default: {
        const exhaustiveCheck: never = iconCandidate;
        throw new Error(`Unhandled icon candidate type: ${exhaustiveCheck}`);
      }
    }
  }, [currentIconData?.imageUrl, iconCandidate]);

  // For newly uploaded icon, it might stuck in pending or review state for some time.
  // If that happens, we will refresh the thumbnail every 5 seconds until it's completed.
  const refreshTimer = useRef<NodeJS.Timeout | null>(null);
  useEffect(() => {
    // If currentIconData is not available.
    // It means the icon is either not uploaded or not fetched yet.
    if (!currentIconData) {
      if (refreshTimer.current) clearInterval(refreshTimer.current);
      refreshTimer.current = null;
      return emptyFunction;
    }

    const { state } = currentIconData;
    if (state === 'InReview' || state === 'Pending') {
      if (!refreshTimer.current) {
        refreshTimer.current = setInterval(() => {
          refreshThumbnail();
        }, 5000);
      }
    } else if (refreshTimer.current) {
      clearInterval(refreshTimer.current);
      refreshTimer.current = null;
    }
    return () => {
      if (refreshTimer.current) {
        clearInterval(refreshTimer.current);
        refreshTimer.current = null;
      }
    };
  }, [currentIconData, iconCandidate, refreshThumbnail]);

  const onCancel = useCallback(() => {
    setIconCandidate(null);
  }, []);

  const [isRefreshingOnSuccessfulUpload, setIsRefreshingOnSuccessfulUpload] = useState(false);
  const onSuccess = useCallback(() => {
    setIsRefreshingOnSuccessfulUpload(true);
    refreshThumbnail()
      .then(() => {
        setIconCandidate(null);
      })
      .finally(() => {
        setIsRefreshingOnSuccessfulUpload(false);
      });
  }, [refreshThumbnail]);

  const uploadButtonRef = useRef<HTMLButtonElement>(null);
  const onError = useCallback(() => {
    configure(
      <DialogTemplate
        title={translate('Title.UploadImageFailed' /** PlaceThumbnails */)}
        content={translate('Description.UploadImageFailed', {
          formats: acceptMimeTypes.map((mime) => `*.${mime.split('/')[1]}`).join(', '),
        })}
        confirmText={translate('Action.UploadImage' /** Controls */)}
        cancelText={translate('Action.Cancel' /** Controls */)}
        onConfirm={() => {
          uploadButtonRef.current?.click();
          close();
        }}
        onCancel={close}
      />,
    );
    open();
  }, [close, configure, open, translate]);

  const { uploadPlaceIcon, isUploading: isUploadingPlaceIcon } = useUploadPlaceIconMutation(
    placeId,
    onSuccess,
    onError,
  );
  const { uploadAutoGeneratedIcon, isUploading: isUploadingAutoGeneratedIcon } =
    useUploadAutoGeneratedIconMutation(placeId, onSuccess, undefined);
  const { setDefaultIcon, isSettingDefault } = useSetDefaultIconMutation(
    placeId,
    onSuccess,
    undefined,
  );

  const onSave = useCallback(async () => {
    if (iconCandidate?.type === CandidateType.Image) {
      const square = await cropImageToSquare(iconCandidate.file);
      uploadPlaceIcon(square);
    } else if (iconCandidate?.type === CandidateType.AutoGenerated) {
      uploadAutoGeneratedIcon(iconCandidate.imageUrl);
    } else if (iconCandidate?.type === CandidateType.Placeholder) {
      setDefaultIcon();
    } else {
      /* empty */
    }
  }, [iconCandidate, setDefaultIcon, uploadAutoGeneratedIcon, uploadPlaceIcon]);

  const isUploading = isUploadingPlaceIcon || isUploadingAutoGeneratedIcon || isSettingDefault;
  return (
    <Grid container classes={{ root: placeIconContainer }}>
      <Grid item XSmall={12}>
        <Typography variant='body1' display='block' color='secondary' marginTop='8px'>
          {translate('Description.Icon' /** CreatorDashboard.Places */)}
        </Typography>
      </Grid>
      <Grid item XSmall={12}>
        <Flex gap={8}>
          <FileUploadBase onChange={setImageUploadCandidate} accept={acceptMimeTypes.join(', ')}>
            {(onClick: () => void) => (
              <IconCandidateButton
                ref={uploadButtonRef}
                startIcon={<CollectionsIcon />}
                onClick={onClick}
                disabled={isUploading}
                label={translate('Action.UploadImage' /** Controls */)}
              />
            )}
          </FileUploadBase>
          <IconCandidateButton
            onClick={setAutoGeneratedCandidate}
            label={translate('Label.AutoGenerated')}
            startIcon={<AutoFixNormalIcon />}
            disabled={isContentRestricted || !autoGeneratedData?.imageUrl || isUploading}
          />
          <IconCandidateButton
            onClick={setPlaceHolderCandidate}
            label={translate('Label.Placeholder')}
            startIcon={<ImageIcon />}
            disabled={isUploading}
          />
        </Flex>
      </Grid>
      <Grid item XSmall={12}>
        <div
          className={iconCandidateImageContainer}
          style={{
            backgroundImage: `url(${imageUrl})`,
          }}
          role='img'
        />
      </Grid>
      <Grid item XSmall={12}>
        <Flex gap={8}>
          <Button
            data-testid='cancel-button'
            variant='outlined'
            color='primary'
            disabled={!iconCandidate || isUploading || isRefreshingOnSuccessfulUpload}
            onClick={onCancel}>
            {translate('Label.Cancel')}
          </Button>
          <Button
            data-testid='save-icon-button'
            variant='contained'
            disabled={!iconCandidate || isRefreshingOnSuccessfulUpload}
            onClick={onSave}
            loading={isUploading}>
            {translate('Label.Save')}
          </Button>
        </Flex>
      </Grid>
    </Grid>
  );
};

export default PlaceIconFormV2;
