export const PlaceIconRegisterOptions = {
  mediaType: { required: true },
};

export enum PlaceIconMediaType {
  Default = 'Default',
  AutoGenerated = 'AutoGenerated',
  Image = 'Image',
}

export const PlaceIconFormDefaultValue = {
  mediaType: PlaceIconMediaType.Image,
  file: null,
};

export type PlaceIconFormType = {
  mediaType: PlaceIconMediaType;
  file: File | null;
};

export const PlaceIconImageTypes = ['jpg', 'png', 'tga', 'bmp'];
