import { makeStyles } from '@rbx/ui';

const useEstimateEarningModalStyles = makeStyles()((theme) => ({
  dialogPaper: {
    background: 'transparent',
    boxShadow: 'none',
    overflow: 'visible',
    [theme.breakpoints.down('Medium')]: {
      margin: '16px',
      maxWidth: 'calc(100vw - 32px)',
    },
  },
  wrapper: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    isolation: 'isolate',
    position: 'relative',
    width: '500px',
    minWidth: '300px',
    maxWidth: '500px',
    minHeight: '352px',
    height: 'auto',
    background: theme.palette.surface[0],
    border: `1px solid ${theme.palette.surface.outline}`,
    boxShadow: theme.shadows[24],
    borderRadius: '16px',
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
      maxWidth: '100%',
      minWidth: '280px',
    },
  },
  utility: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    padding: '16px 12px 12px',
    position: 'absolute',
    width: '64px',
    height: '68px',
    right: '0px',
    top: '0px',
    zIndex: 2,
  },
  closeButton: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '8px',
    width: '40px',
    height: '40px',
    borderRadius: '8px',
    '&:hover': {
      background: theme.palette.states.hover,
    },
    '& .MuiSvgIcon-root': {
      width: '24px',
      height: '24px',
      color: theme.palette.content.standard,
    },
  },
  // Frame 1547765675 - Most outer content container
  content: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: '24px 16px',
    gap: '4px',
    width: '500px',
    minHeight: '352px',
    height: 'auto',
    flex: 'none',
    order: 1,
    alignSelf: 'stretch',
    flexGrow: 0,
    zIndex: 1,
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
      padding: '24px 12px',
    },
  },
  // Frame 288598 - Inner container
  contentInner: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    gap: '16px',
    width: '468px',
    minHeight: '304px',
    height: 'auto',
    flex: 'none',
    order: 0,
    flexGrow: 1,
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
    },
  },
  // Typography/custom/False - Title container
  titleContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    width: '468px',
    height: '24px',
    flex: 'none',
    order: 0,
    alignSelf: 'stretch',
    flexGrow: 0,
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
      height: 'auto',
      paddingRight: '32px',
    },
  },
  // Title text
  title: {
    width: '387px',
    height: '24px',
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '20px',
    lineHeight: '120%',
    color: theme.palette.content.standard,
    flex: 'none',
    order: 0,
    flexGrow: 0,
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
      height: 'auto',
      wordWrap: 'break-word',
      overflowWrap: 'break-word',
    },
  },
  // Body container
  body: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: '0px',
    gap: '10px',
    width: '468px',
    minHeight: '264px',
    height: 'auto',
    flex: 'none',
    order: 1,
    alignSelf: 'stretch',
    flexGrow: 0,
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
    },
  },
  // Body text
  bodyText: {
    width: '468px',
    minHeight: '264px',
    height: 'auto',
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '16px',
    lineHeight: '140%',
    letterSpacing: '0%',
    color: theme.palette.content.muted,
    flex: 'none',
    order: 0,
    flexGrow: 1,
    overflow: 'visible',
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
      minHeight: 'auto',
    },
  },
}));

export default useEstimateEarningModalStyles;
