import { makeStyles } from '@rbx/ui';

const useEstimateEarningCalculatorStyles = makeStyles()((theme) => ({
  calculatorContainer: {
    width: '100%',
    padding: '24px',
    gap: '24px',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: '8px',
    border: `1px solid ${theme.palette.surface.outline}`,
    boxSizing: 'border-box',
  },
  calculatorTitle: {
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '20px',
    lineHeight: '120%',
    letterSpacing: '-0.01em',
    color: theme.palette.content.standard,
    marginBottom: 0,
  },
  mainFrame: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    gap: '24px',
    flexWrap: 'wrap',
    [theme.breakpoints.down('Medium')]: {
      flexDirection: 'column',
    },
  },
  controlsBlock: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    gap: '24px',
    width: '500px',
    minWidth: '500px',
    height: '232px',
    flex: 'none',
    order: 0,
    flexGrow: 1,
    [theme.breakpoints.down('Large')]: {
      minWidth: '100%',
      width: '100%',
      height: 'auto',
      marginBottom: '8px',
    },
    [theme.breakpoints.down('Medium')]: {
      minWidth: '100%',
      width: '100%',
      height: 'auto',
      marginBottom: '0px',
    },
  },
  earningsContainer: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '0px',
    gap: '16px',
    minWidth: '230px',
    height: '159px',
    flex: 'none',
    order: 0,
    flexGrow: 0,
    [theme.breakpoints.down('Medium')]: {
      minWidth: 'auto',
      height: 'auto',
    },
  },
  earningsLabel: {
    minWidth: '230px',
    height: '40px',
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '16px',
    lineHeight: '100%',
    color: theme.palette.content.standard,
    flex: 'none',
    order: 0,
    flexGrow: 0,
    textAlign: 'center',
    [theme.breakpoints.down('Medium')]: {
      minWidth: 'auto',
      height: 'auto',
    },
  },
  robuxIconAndValue: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0px',
    gap: '4px',
    height: '67px',
    flex: 'none',
    order: 1,
    alignSelf: 'stretch',
    flexGrow: 0,
  },
  robuxIcon: {
    width: '42px',
    height: '42px',
    flex: 'none',
    order: 0,
    flexGrow: 0,
    '& svg': {
      width: '100%',
      height: '100%',
    },
  },
  earningsValue: {
    height: '67px',
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '56px',
    lineHeight: '120%',
    letterSpacing: '-0.01em',
    color: theme.palette.content.standard,
    flex: 'none',
    order: 1,
    flexGrow: 0,
  },
  adViewsLabel: {
    width: '165px',
    height: '20px',
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '140%',
    color: theme.palette.content.muted,
    flex: 'none',
    order: 2,
    flexGrow: 0,
    textAlign: 'center',
    whiteSpace: 'nowrap',
    [theme.breakpoints.down('Medium')]: {
      width: 'auto',
      height: 'auto',
      whiteSpace: 'normal',
    },
  },
  earningsBlock: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '48px',
    gap: '10px',
    width: '326px',
    minWidth: '326px',
    height: '255px',
    background: theme.palette.surface[200],
    borderRadius: '8px',
    flex: 'none',
    order: 1,
    alignSelf: 'stretch',
    flexGrow: 0,
    [theme.breakpoints.down('Medium')]: {
      minWidth: '100%',
      width: '100%',
      padding: '24px',
      height: 'auto',
    },
  },
  dropdownContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    width: '100%',
  },
  selectWrapper: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    gap: '8px',
    width: '100%',
  },
  inputLabel: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '0px',
    gap: '4px',
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '140%',
    color: theme.palette.content.standard,
  },
  selectContainer: {
    width: '100%',
    '& .MuiOutlinedInput-root': {
      borderRadius: '8px',
      border: `1px solid ${theme.palette.surface.outline}`,
      fontFamily: 'Builder Sans',
      fontSize: '16px',
      color: theme.palette.content.muted,
    },
  },
  sliderContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    padding: '0px',
    gap: '24px',
    width: '100%',
    overflow: 'visible',
    [theme.breakpoints.down('Large')]: {
      paddingBottom: '8px',
    },
    [theme.breakpoints.down('Medium')]: {
      paddingBottom: '0px',
    },
  },
  sliderLabelContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    padding: '0px',
    gap: '4px',
  },
  sliderLabel: {
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 700,
    fontSize: '16px',
    lineHeight: '140%',
    color: theme.palette.content.standard,
    whiteSpace: 'nowrap',
  },
  infoIcon: {
    width: '14px',
    height: '14px',
    color: theme.palette.content.muted,
  },
  slider: {
    width: '100%',
    '& .MuiSlider-thumb': {
      width: '20px',
      height: '20px',
      background: theme.palette.content.standard,
      border: `1px solid ${theme.palette.surface.outline}`,
      boxShadow: theme.shadows[2],
      '&:hover': {
        boxShadow: theme.shadows[4],
      },
    },
    '& .MuiSlider-track': {
      background: theme.palette.content.standard,
      border: 'none',
      borderRadius: '9999px',
    },
    '& .MuiSlider-rail': {
      background: theme.palette.surface.outline,
      borderRadius: '9999px',
    },
  },
  helperText: {
    fontFamily: 'Builder Sans',
    fontStyle: 'normal',
    fontWeight: 400,
    fontSize: '14px',
    lineHeight: '140%',
    color: theme.palette.content.muted,
    wordWrap: 'break-word',
    overflowWrap: 'break-word',
    width: '100%',
    maxWidth: '100%',
    [theme.breakpoints.down('Large')]: {
      marginBottom: '0px',
    },
    [theme.breakpoints.down('Medium')]: {
      marginBottom: '0px',
    },
  },
  helperLink: {
    textDecoration: 'underline',
    color: theme.palette.content.muted,
    '&:hover': {
      color: theme.palette.content.standard,
    },
  },
}));

export default useEstimateEarningCalculatorStyles;
