import {
  AdAccountPaymentFailureReasonEnum,
  AdAccountPaymentStatusEnum,
} from '@constants/advertiser';
import {
  AdAccountType,
  defaultTimeZoneMapping,
  OrganizationStatus,
  OrganizationType,
} from '@constants/app';
import { videoMinBidMappingsMicroUsdDefaults } from '@constants/asset';
import { MAX_ALLOWED_CREATIVES } from '@constants/campaignBuilder';
import {
  coreCountryOverrideList,
  euRegionCodeList,
  ServerRegionCode,
} from '@constants/locationAutocomplete';
import { AppDataDefaultsType } from '@type/appStore';
import { PaymentProfileType } from '@type/payment';

export const appDataDefaults: AppDataDefaultsType = {
  accountHasValidName: true,
  adAccountInfo: {
    ad_billing_tier: 5,
    billing_threshold_micro_usd: 0,
    created_timestamp_ms: 0,
    daily_spend_limit_micro_usd: 0,
    id: '',
    name: '',
    organization_id: '',
    type: AdAccountType.AD_ACCOUNT_TYPE_SELF_SERVICE,
    updated_timestamp_ms: 0,
  },
  adAccountIsExternalManaged: () => false,
  adAccountIsInternalManaged: () => false,
  adAccountPrepaidBalance: 0,
  adAccountStatusState: {
    data: {
      hasFailedPayment: false,
      hasTransactionFailure: false,
      hasUnknownPaymentStatus: false,
      profileNotVerified: false,
      reason: AdAccountPaymentFailureReasonEnum.PAYMENT_SERVICE_UNAVAILABLE,
      status: AdAccountPaymentStatusEnum.SUCCEEDED,
    },
    isError: false,
    isLoading: false,
  },
  adCreditActivated: false,
  adCreditBalance: 0,
  adCreditFromRobuxPurchaseRate: 263,
  adCreditMaximumPurchaseAmount: 1000000,
  adCreditMinimumPurchaseAmount: 10,
  adFormats: [],
  adLimit: 0,
  ads: [],
  adSetLimit: 0,
  adSets: [],
  adTogglingShouldBeEnabled: () => ({ disabledTooltip: '', togglingEnabled: false }),
  advertisingShouldBeEnabled: () => ({ advertisingShouldBeEnabled: true }),
  campaignLimit: 1000,
  campaignMaximumDailyBudgetUsd: 2000.0,
  campaignMaximumDailyExpectedPlays: 200_000,
  campaignMinimumDailyBudgetUsd: 10.0,
  campaignMinimumDailyExpectedPlays: 1_000,
  campaigns: [],
  coreCountryOverrideCodeList: coreCountryOverrideList,
  coreRegionCodeList: [
    ServerRegionCode.VALUE_ALL,
    ServerRegionCode.VALUE_US,
    ServerRegionCode.VALUE_CA,
    ServerRegionCode.VALUE_GB,
    ServerRegionCode.VALUE_ANZ,
  ],
  coreRegionFloorPriceUsd: 0.2,
  cpcCeilingPriceUsd: 2.0,
  cpcFloorPriceUsd: 0.01,
  cpmMaximumBidUsd: 100.0,
  cpmMinimumBidUsd: 1.0,
  cptMaximumBidUsd: 100.0,
  cptMinimumBidUsd: 0.1,
  EURegionCodeList: euRegionCodeList,
  filteredAds: [],
  filteredAdSets: [],
  getPaymentProfilesState: {
    data: { data: [] as PaymentProfileType[] },
    isError: false,
    isLoading: false,
  },
  hasNewFlowCampaign: { data: false, isError: false, isLoading: false },
  hasVerifiedEmail: undefined,
  isAdIntegrationRewardedPlacementsEnabled: false,
  isCampaignLimitMax: false,
  isDefaultBillingTier: false,
  maximumAdsPerTrafficDrivingCampaignCount: MAX_ALLOWED_CREATIVES,
  mixedRegionFloorPriceUsd: 0.1,
  opportunisticRegionCodeList: [
    ServerRegionCode.VALUE_BR,
    ServerRegionCode.VALUE_EASTERN_EUROPE,
    ServerRegionCode.VALUE_SOUTHEAST_ASIA,
    ServerRegionCode.VALUE_MIDDLE_EAST,
    ServerRegionCode.VALUE_LATIN_AMERICA,
    ServerRegionCode.VALUE_AFRICA,
    ServerRegionCode.VALUE_ROW,
  ],
  opportunisticRegionFloorPriceUsd: 0.03,
  organizationInfo: {
    address: { city: '', country: '', line_address: '', postal_code: '', state: '' },
    status: OrganizationStatus.ORGANIZATION_STATUS_ACTIVE,
    tax_id: '',
    time_zone: defaultTimeZoneMapping,
    type: OrganizationType.ORGANIZATION_TYPE_BUSINESS,
  },
  paymentFailure: true,
  paymentProfiles: [],
  portalAdsMaximumBidValueUsd: 2.0,
  selectedAds: [],
  selectedAdSets: [],
  selectedCampaigns: [],
  showAudienceEstimate: false,
  showDelete: false,
  statusBannerMessage: '',
  strategicRegionCodeList: [
    ServerRegionCode.VALUE_DE,
    ServerRegionCode.VALUE_FR,
    ServerRegionCode.VALUE_KR,
    ServerRegionCode.VALUE_JP,
    ServerRegionCode.VALUE_WESTERN_EUROPE,
    ServerRegionCode.VALUE_EAST_ASIA,
  ],
  strategicRegionFloorPriceUsd: 0.2,
  tileAdsMaximumBidValueUsd: 2.0,
  tileAdsMinimumBidValueUsd: 0.01,
  videoMinBidMappingsMicroUsd: videoMinBidMappingsMicroUsdDefaults,
};
