const enum ErrorCodes {
  FORBIDDEN_ACTION = '000021',
  AD_ACCOUNT_BLOCKED = 'AD_ACCOUNT_BLOCKED',
  AD_ACCOUNT_NOT_FOUND = 'AD_ACCOUNT_NOT_FOUND',
  AD_LIMIT_REACHED = 'AD_LIMIT_REACHED',
  AD_SET_LIMIT_REACHED = 'AD_SET_LIMIT_REACHED',
  ALREADY_CLAIMED = 'ALREADY_CLAIMED',
  CAMPAIGN_LIMIT_REACHED = 'CAMPAIGN_LIMIT_REACHED',
  INVALID_ARGUMENT = 'INVALID_ARGUMENT',
  MULTIPLE_UNIVERSES = 'MULTIPLE_UNIVERSES',
  OFF_PLATFORM_CAMPAIGN_LIMIT_REACHED = 'OFF_PLATFORM_CAMPAIGN_LIMIT_REACHED',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  RATE_LIMITED = 'RATE_LIMITED',
  VALIDATE_DISPLAY_NAME_FAILED = 'VALIDATE_DISPLAY_NAME_FAILED',
}

export default ErrorCodes;
