const enum ReportingStatType {
  REPORTING_STAT_SPEND = 0,
  REPORTING_STAT_IMPRESSIONS = 1,
  REPORTING_STAT_CLICK_THROUGH_RATE = 2,
  REPORTING_STAT_CLICKS = 3,
  REPORTING_STAT_PLAYS = 4,
  REPORTING_STAT_COST_PER_PLAY = 5,
  REPORTING_STAT_TOTAL_PLAY_TIME_7D = 6,
  REPORTING_STAT_TOTAL_ROBUX_REVENUE_30D = 7,
  REPORTING_STAT_ROAS = 8,
}

export default ReportingStatType;
