import React, { FunctionComponent, useMemo } from 'react';
import { Typography, Grid, Button, Card, CardContent, CardActions, Link } from '@rbx/ui';
import { useTranslation } from '@rbx/intl';
import { FeedbackReasonType } from '@modules/clients';
import { getProductionCreatorHubUrl } from '@rbx/env-utils';
import useFeedbackCardStyles from './FeedbackCard.styles';
import { TranslationFeedback } from '../types';
import ReporterType from '../enums/ReporterType';
import reasonTypeToLabelMap from '../translationFeedbackConstants';
import getTranslation from '../utils/testFeedbackUtils';

export interface FeedbackProps {
  cardLength: number;
  translationFeedback: TranslationFeedback;
  onSave: (currentTranslation: string | null, isTranslationManual: boolean) => void;
}

const FeedbackCard: FunctionComponent<React.PropsWithChildren<FeedbackProps>> = ({
  cardLength,
  translationFeedback,
  onSave,
}) => {
  const {
    classes: { card, button, text },
  } = useFeedbackCardStyles(cardLength)();
  const { translate, translateHTML } = useTranslation();

  const description = useMemo(() => {
    if (translationFeedback.reporterType === ReporterType.Player) {
      const reasonType = translationFeedback.reason;
      const reason = reasonTypeToLabelMap[reasonType as FeedbackReasonType];
      const playerDescriptionLabel = translate('Description.ManualFeedbackReason', {
        playerCount: (translationFeedback.suggestionCount ?? 0).toString(),
        reason,
      });
      const playerDescription = getTranslation(
        playerDescriptionLabel,
        `${translationFeedback.suggestionCount} player(s) suggested that your current translation ${reason}.`,
      );

      return (
        <Typography variant='captionBody' className={text}>
          {playerDescription}
        </Typography>
      );
    }

    // eslint-disable-next-line @typescript-eslint/no-unused-vars -- Replace strings with labels when feature is ready
    const robloxDescriptionLabel = translateHTML('Description.RobloxTranslate', [
      {
        opening: 'startLink',
        closing: 'endLink',
        content(chunks) {
          return (
            <Link
              href={`${getProductionCreatorHubUrl(process.env.buildTarget)}/docs/production/localization/translating-in-experience-content#automatic-translation`}
              target='_blank'
              underline='always'>
              {chunks}
            </Link>
          );
        },
      },
    ]);

    // TODO: Replace strings with labels when feature is ready for launch
    const robloxDescription = `This suggestion was automatically generated by Roblox Translate. Find out more.`;

    return (
      <Typography variant='captionBody' className={text}>
        {robloxDescription}
      </Typography>
    );
  }, [
    translationFeedback.reporterType,
    translationFeedback.reason,
    translationFeedback.suggestionCount,
    translateHTML,
    text,
    translate,
  ]);

  const title = useMemo(() => {
    return translationFeedback.reporterType === ReporterType.Player
      ? getTranslation(translate('Label.PlayersSuggestion'), `Players' Suggestion`)
      : getTranslation(translate('Label.RobloxTranslate'), `Roblox Translate`);
  }, [translate, translationFeedback.reporterType]);

  return (
    <Card classes={{ root: card }}>
      <CardContent>
        <Grid container direction='column'>
          <Typography variant='overline' className={text}>
            {title}
          </Typography>
          <Typography variant='captionHeader' className={text}>
            {translationFeedback.suggestion}
          </Typography>
          {description}
        </Grid>
      </CardContent>
      <CardActions classes={{ root: button }}>
        <Button
          onClick={() => onSave(translationFeedback.suggestion, true)}
          variant='contained'
          size='small'>
          {getTranslation(translate('Label.Save'), ` Save`)}
        </Button>
      </CardActions>
    </Card>
  );
};

export default FeedbackCard;
