import type { FunctionComponent } from 'react';
import React, { Fragment, useCallback, useEffect, useMemo, useState } from 'react';
import type { UseFieldArrayReplace, UseFormGetValues } from 'react-hook-form';
import type { CreationContext } from '@rbx/client-assets-upload-api/v1';
import { AssetType } from '@rbx/client-assets-upload-api/v1';
import { useTranslation } from '@rbx/intl';
import { ReturnPolicy, ThumbnailClient, ThumbnailTypes } from '@rbx/thumbnails';
import {
  BrokenImageOutlinedIcon,
  Button,
  Grid,
  ImageIcon,
  makeStyles,
  Skeleton,
  Tooltip,
  Typography,
} from '@rbx/ui';
import { useAuthentication } from '@modules/authentication/providers';
import assetsUploadApiClient from '@modules/clients/assetsupload';
import { FileUploadBase } from '@modules/miscellaneous/components';
import { useCurrentGroup } from '@modules/providers/groups/GroupsProvider';
import {
  acceptedExperienceThumbnailFormats,
  bytesPerMB,
  maxImageThumbnailSizeMB,
  thumbnailUploadPollingIntervalMS,
  thumbnailUploadPollingMaxRetries,
} from '../../common/constants';
import type { CreateEventFormType } from '../types';

export interface EventThumbnailUploaderM3Props {
  getValues: UseFormGetValues<CreateEventFormType>;
  replace: UseFieldArrayReplace<CreateEventFormType>;
  isUploadingThumbnail: boolean;
  setIsUploadingThumbnail: React.Dispatch<React.SetStateAction<boolean>>;
}

const enum ThumbnailState {
  Loading,
  Loaded,
  Error,
}

const acceptedThumbnailMimeTypes = acceptedExperienceThumbnailFormats.reduce<string[]>(
  (prev, type) => {
    prev.push(`image/${type}`);
    return prev;
  },
  [],
);

const useEventThumbnailUploaderM3Styles = makeStyles()((theme) => ({
  eventThumbnailUploadContainer: {
    display: 'flex',
    gap: '16px',
    alignItems: 'center',
  },
  eventThumbnailUploadPreview: {
    width: '140px',
    minWidth: '140px',
    height: '81px',
    minHeight: '81px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.palette.surface[200],
    ...theme.border.radius.medium,
  },
}));

const EventThumbnailUploaderM3: FunctionComponent<EventThumbnailUploaderM3Props> = ({
  getValues,
  replace,
  isUploadingThumbnail,
  setIsUploadingThumbnail,
}) => {
  const { translate } = useTranslation();
  const { getThumbnailImage } = ThumbnailClient;
  const currentGroup = useCurrentGroup();
  const { user } = useAuthentication();
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [url, setURL] = useState<string | undefined>(getValues('thumbnails')[0]?.url);
  const [state, setState] = useState<ThumbnailState>(
    url ? ThumbnailState.Loaded : ThumbnailState.Loading,
  );
  const {
    classes: { eventThumbnailUploadContainer, eventThumbnailUploadPreview },
  } = useEventThumbnailUploaderM3Styles();

  const loadThumbnail = useCallback(async () => {
    const thumbnail = getValues('thumbnails')[0];
    if (thumbnail) {
      if (!thumbnail.id) {
        return;
      }
      try {
        if (!url) {
          const data = await getThumbnailImage(
            ThumbnailTypes.assetThumbnail,
            thumbnail.id,
            ReturnPolicy.AutoGenerated,
          );
          setURL(data.imageUrl);
          setState(ThumbnailState.Loaded);
        }
      } catch {
        setState(ThumbnailState.Error);
      }
    } else {
      setState(ThumbnailState.Loaded);
    }
  }, [getThumbnailImage, getValues, url]);

  useEffect(() => {
    loadThumbnail();
  }, [loadThumbnail]);

  const uploadErrors = useMemo(() => {
    if (errorMessage) {
      return <Typography color='error'>{errorMessage}</Typography>;
    }
    return null;
  }, [errorMessage]);

  // These errors overlap in error code, so we use the message to localize them
  // Some of these errors should not occur for this uploader, but are valid errors
  // returned by the API
  const localizeThumbnailUploadError = useCallback(
    (msg: string) => {
      if (msg.includes('Invalid image dimensions')) {
        return translate('Message.ItemConfigurationBadRequestError');
      }
      if (msg.includes('Invalid image format')) {
        return translate('Message.InvalidImageFormat');
      }
      if (msg.includes('Image resolution')) {
        return translate('Error.EEThumbnailResolution', { sizeLimit: '8000' });
      }
      if (msg.includes('moderated')) {
        return translate('Message.NameOrDescriptionModeratedError');
      }
      if (msg.includes('InsufficientFunds')) {
        return translate('Message.InsufficientFunds');
      }
      if (msg.includes('IdVerification')) {
        return translate('Message.IdVerification');
      }
      if (msg.includes('Timeout')) {
        return translate('Error.EEUploadThumbnailTimeout');
      }
      return translate('Message.AssetCreationFailed');
    },
    [translate],
  );

  const pollForCompletedThumbnailUploadOperation = useCallback(
    async (
      operationId: string,
      creatorId: number | undefined,
      currentAttempt: number,
    ): Promise<number | undefined> => {
      const operation = await assetsUploadApiClient.getOperationStatus(operationId);
      const isOperationDone = operation?.done ?? false;

      if (currentAttempt > thumbnailUploadPollingMaxRetries) {
        throw new Error('Timeout');
      }
      if (isOperationDone && operation?.error == null) {
        return operation?.response?.assetId;
      }
      if (isOperationDone && operation?.error != null) {
        throw new Error(operation?.error?.message || '');
      }
      await new Promise((r) => setTimeout(r, thumbnailUploadPollingIntervalMS));
      return pollForCompletedThumbnailUploadOperation(operationId, creatorId, currentAttempt + 1);
    },
    [],
  );

  const handleThumbnailUpload = useCallback(
    async (files: FileList | File | null) => {
      let file: File | null = null;
      let uploadUrl: string = '';

      // Local validation
      if (files !== null) {
        // Select image
        if (files instanceof FileList && files.length > 0) {
          file = files.item(0);
          if (file == null) {
            throw new Error(translate('Message.AssetCreationFailed'));
          }
        } else if (files instanceof File) {
          file = files;
        } else {
          throw new Error(translate('Message.AssetCreationFailed'));
        }
        // Validate image
        if (maxImageThumbnailSizeMB && file.size > maxImageThumbnailSizeMB * bytesPerMB) {
          throw new Error(
            translate('Message.MaxSizeExceededError', {
              maxFileSize: `${maxImageThumbnailSizeMB}MB`,
            }),
          );
        }
        if (!acceptedThumbnailMimeTypes.includes(file.type)) {
          throw new Error(translate('Message.WrongFormatError'));
        }
        // Accept image
        uploadUrl = URL.createObjectURL(file);
      }
      if (!file || !uploadUrl) {
        throw new Error(translate('Message.AssetCreationFailed'));
      }

      // Upload
      setState(ThumbnailState.Loading);
      const groupId = currentGroup?.id;
      const creator = groupId
        ? { groupId: parseInt(groupId.toString(), 10) }
        : { userId: user?.id };
      const creationContext: CreationContext = {
        creator,
      };
      const req = {
        displayName: getValues('title') || 'event_thumbnail',
        description: '',
        assetType: AssetType.Image,
        creationContext,
      };
      setIsUploadingThumbnail(true);
      const thumbnailID = await pollForCompletedThumbnailUploadOperation(
        await assetsUploadApiClient.createAssetAndGetOperationId(req, file),
        creator.userId,
        0,
      )
        .catch((e) => {
          setState(ThumbnailState.Error);
          if (e instanceof Error) {
            throw new Error(localizeThumbnailUploadError(e.message));
          }
          throw new Error(translate('Error.EEFailedToUploadThumbnail'));
        })
        .finally(() => {
          setIsUploadingThumbnail(false);
        });
      if (thumbnailID) {
        // We continue to use the original URL so the user can still see the image rather than the moderation placeholder
        // as long as they remain on the page
        replace([{ id: thumbnailID, url: uploadUrl, file }]);
        setURL(uploadUrl);
        setState(ThumbnailState.Loaded);
        return;
      }
      setState(ThumbnailState.Error);
      throw new Error(translate('Error.EEFailedToUploadThumbnail'));
    },
    [
      currentGroup?.id,
      getValues,
      localizeThumbnailUploadError,
      pollForCompletedThumbnailUploadOperation,
      replace,
      setIsUploadingThumbnail,
      translate,
      user?.id,
    ],
  );

  const handleChange = async (files: FileList | File | null) => {
    try {
      await handleThumbnailUpload(files);
      setErrorMessage('');
    } catch (e) {
      if (e instanceof Error) {
        setErrorMessage(e.message);
      } else {
        setErrorMessage(translate('Error.EEFailedToUploadThumbnail'));
      }
      setIsUploadingThumbnail(false);
    }
  };

  const fileTypeHelperText = useMemo(
    () =>
      `${translate('Label.Format')} ${acceptedExperienceThumbnailFormats?.map((type) => `*.${type}`).join(', ')}`,
    [translate],
  );
  // Upload tooltip text is defined as a React component because Tooltip does not respect newlines
  const uploadTooltipText = useMemo(
    () => (
      <>
        <Grid>{fileTypeHelperText}</Grid>
        <Grid>{translate('Label.EEThumbnailSizeRecommendation')}</Grid>
        <Grid>{translate('Label.EEVisibleAfterModeration')}</Grid>
      </>
    ),
    [fileTypeHelperText, translate],
  );

  const thumbnailImage = useMemo(() => {
    switch (state) {
      case ThumbnailState.Loaded:
        return url !== undefined ? (
          <Grid item className={eventThumbnailUploadPreview}>
            <img
              src={url}
              className={eventThumbnailUploadPreview}
              alt={translate('Label.EEThumbnailAltText')}
            />
          </Grid>
        ) : (
          <Grid item className={eventThumbnailUploadPreview}>
            <ImageIcon color='disabled' fontSize='large' />
          </Grid>
        );
      case ThumbnailState.Loading:
        return (
          <Grid item className={eventThumbnailUploadPreview}>
            <Skeleton className={eventThumbnailUploadPreview} />
          </Grid>
        );
      default:
        return (
          <Grid item className={eventThumbnailUploadPreview}>
            <BrokenImageOutlinedIcon color='disabled' fontSize='large' />
          </Grid>
        );
    }
  }, [eventThumbnailUploadPreview, state, translate, url]);

  return (
    <Grid direction='row' className={eventThumbnailUploadContainer}>
      {thumbnailImage}
      <span>
        <Grid direction='row' style={{ display: 'flex', gap: '8px' }}>
          <FileUploadBase
            accept={acceptedExperienceThumbnailFormats?.map((type) => `.${type}`).join(',') ?? ''}
            size={maxImageThumbnailSizeMB ? maxImageThumbnailSizeMB * bytesPerMB : undefined}
            onChange={handleChange}>
            {(onClick: () => void) => (
              <Grid container spacing='2' gap='10px' alignItems='center'>
                <Tooltip arrow placement='right' title={uploadTooltipText}>
                  <Button
                    size='medium'
                    variant='contained'
                    color='secondary'
                    onClick={onClick}
                    loading={isUploadingThumbnail}>
                    {url !== undefined
                      ? translate('Action.EEChange')
                      : translate('Action.EEUploadImage')}
                  </Button>
                </Tooltip>
                {url !== undefined && (
                  <Button
                    size='medium'
                    variant='contained'
                    color='secondary'
                    onClick={() => {
                      replace([]);
                      setURL(undefined);
                    }}
                    loading={isUploadingThumbnail}>
                    {translate('Action.Remove')}
                  </Button>
                )}
              </Grid>
            )}
          </FileUploadBase>
        </Grid>
        <Grid>{uploadErrors}</Grid>
      </span>
    </Grid>
  );
};

export default EventThumbnailUploaderM3;
