// DO NOT MODIFY
// This code is generated by https://github.rbx.com/Roblox/activity-history-event-generation
// Please put in <TODD> and create a new pull request
// DO NOT MODIFY
/* oxlint-disable typescript/no-unsafe-assignment -- pre-existing pattern in this generated file; data is parsed from a trusted internal API with no schema. See modules/data-collection/components/SettingsV2.tsx for precedent. */
/* oxlint-disable typescript/no-unsafe-argument -- pre-existing pattern in this generated file; data is parsed from a trusted internal API with no schema. See pages/dashboard/creations/experiences/[id]/monetization/personalized-shop/index.tsx for precedent. */
/* oxlint-disable typescript/no-unsafe-member-access -- pre-existing pattern in this generated file; data is parsed from a trusted internal API with no schema. See modules/analytics-assistant/markdown/getMarkdownProcessor.ts for precedent. */
/* oxlint-disable typescript/no-unsafe-call -- pre-existing pattern in this generated file; data is parsed from a trusted internal API with no schema. See modules/analytics-assistant/markdown/getMarkdownProcessor.ts for precedent. */
/* oxlint-disable typescript/no-unsafe-type-assertion -- pre-existing pattern in this generated file; data is parsed from a trusted internal API with no schema. See modules/data-collection/components/SettingsV2.tsx for precedent. */
/* oxlint-disable typescript/no-unsafe-return -- pre-existing pattern in this generated file; JSON.parse in stringToBool returns any. */
/* oxlint-disable unicorn/consistent-function-scoping -- pre-existing pattern in this generated file; helper functions are scoped inside the parser by design. */
import { useEffect, useMemo, useState } from 'react';
import { Locale, useLocalization, useTranslation } from '@rbx/intl';
import developClient, { DevicesType } from '@modules/clients/develop';
import gamesClient from '@modules/clients/games';
import usersClient from '@modules/clients/users';
import { devicesTypeTranslationKeys } from '../../access/constants/AccessConstants';
import type { ExperiencePlayability } from '../enums/ActivityFeedEnums';
import {
  EventType,
  ResourceType,
  playabilityTranslationKeys,
  usernameEvents,
} from '../enums/ActivityFeedEnums';
import { formatMemberPayoutsList, parseMemberPayouts } from '../utils/recurringPayoutUtils';

function parseActivityFeedItemInfo(
  response: ActivityFeedEvent,
  usernames: Record<number, string>,
  placeNames: Record<number, string>,
  rootPlaceId: number,
  getDateTime: (createdUtc: number) => string,
  translate: (key: string, args?: Record<string, string>) => string,
) {
  const universePath = `/dashboard/creations/experiences/${response.universeId}`;
  const placePath = `/dashboard/creations/experiences/${response.universeId}/places/${response.placeId}`;
  const badgePath = `/dashboard/creations/experiences/${response.universeId}/badges/${response.resourceId}/overview`;
  const developerProductPath = `/dashboard/creations/experiences/${response.universeId}/developer-products/${response.resourceId}/configure`;
  const gamePassPath = `/dashboard/creations/experiences/${response.universeId}/passes/${response.resourceId}/configure`;
  const wwwPath = `https://${process.env.robloxSiteDomain}`;
  const userPath = `${wwwPath}/users/${response.userId}/profile`;
  const targetUserPath = `${wwwPath}/users/${response.resourceId}/profile`;
  const groupPath = `${wwwPath}/groups/${response.resourceId}`;

  const filters = {
    eventType: response.eventType,
    userId: response.userId,
    placeId: response.placeId,
    createdUtc: response.createdUnixTimeMs,
  };
  let iconId: number;
  let iconType: ResourceType;
  let translationString: string;
  let location = '';
  let changedByLink = response.userId === 1 ? '' : userPath;
  let locationLink: string | undefined;
  let thumbnailLink = '';
  let viewBasicSettingsLink: string | undefined;
  let viewOnRobloxLink: string | undefined;

  const dateTime: string = getDateTime(response.createdUnixTimeMs);

  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- JSON.parse has no type
  let data: any = {};
  try {
    if (typeof response.metaData === 'string' && response.metaData.length > 0) {
      data = JSON.parse(response.metaData);
      if (typeof data === 'string') {
        data = JSON.parse(data);
      }
    }
  } catch (error) {
    console.error('Error occurred during parsing:', error);
  }

  function stringToBool(str: string | boolean): boolean {
    if (typeof str === 'string') {
      return JSON.parse(str.toLowerCase());
    }
    return str;
  }

  function embolden(str: string): string {
    return str;
  }

  function tostring(str: string): string {
    return str;
  }

  function highlightLocation(str: string): string {
    return str;
  }

  function highlightUser(str: string): string {
    return str;
  }

  function getUsername(userId: number | undefined): string {
    return usernames[userId ?? -1];
  }

  function joinStrings(strings: string[]): string {
    return strings.join(', ');
  }

  // add your custom functions here
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- JSON.parse has no type
  function customTranslateMonetizationSettingsPlayableDevices(dataDevice: any): string {
    const playableDevices = JSON.parse(dataDevice.PlayableDevices).map(
      (num: number) => Object.values(DevicesType)[num - 1],
    );
    const playableDevicesTranslated = playableDevices.map((playableDevice: DevicesType) =>
      translate(devicesTypeTranslationKeys[playableDevice]),
    );
    return playableDevicesTranslated.length > 0
      ? translate(`Description.MonetizationSettingsPlayableDevices`, {
          playableDevices: playableDevicesTranslated.join(', '),
        })
      : translate(`Description.MonetizationSettingsPlayableDevicesEmpty`);
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- JSON.parse has no type
  function customTranslatePlayability(dataPlayability: any): string {
    return translate(
      playabilityTranslationKeys[dataPlayability.Playability as ExperiencePlayability],
    );
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars  -- This is generated stub which has meaning on studio side
  function customTranslatePackageAutoUpdate(packageMetadata: any, resourceId: string): string {
    return '';
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars  -- This is generated stub which has meaning on studio side
  function customTranslateDraftCommit(scriptMetadata: any): string {
    return '';
  }

  function customTranslatePermissions(
    metadata: { RoleName: string; UniverseName: string; Permissions: string; GroupName: string },
    translationKey: string,
    emptyTranslationKey: string,
  ): string {
    const permissions = JSON.parse(metadata.Permissions) as string[];

    const permissionsList = permissions.map((permission) => translate(`Permission.${permission}`));

    return translate(permissions.length > 0 ? translationKey : emptyTranslationKey, {
      roleName: metadata.RoleName,
      universeName: metadata.UniverseName,
      groupName: metadata.GroupName,
      permissions: permissionsList.join(', '),
    });
  }

  function customTranslateRecurringPayouts(
    metadata: {
      GroupName: string;
      ExperienceName?: string;
      Permissions: string;
      PayoutPercent: string;
      MemberPayouts?: string;
    },
    translationKey: string,
    experienceTranslationKey: string,
  ): string {
    const memberPayouts = formatMemberPayoutsList(
      parseMemberPayouts(metadata.MemberPayouts),
      translate,
    );
    if (metadata.ExperienceName) {
      return translate(experienceTranslationKey, {
        experienceName: metadata.ExperienceName,
        groupName: metadata.GroupName,
        payoutPercent: metadata.PayoutPercent,
        memberPayouts,
      });
    }
    return translate(translationKey, {
      groupName: metadata.GroupName,
      payoutPercent: metadata.PayoutPercent,
      memberPayouts,
    });
  }

  try {
    // oxlint-disable-next-line typescript/switch-exhaustiveness-check
    switch (response.eventType) {
      // Begin Generated Code 🤖
      case EventType.Init:
        translationString = translate('Description.Init');
        iconType = ResourceType.Universe;
        break;
      case EventType.ArchivedExperience:
        translationString = stringToBool(data.Action)
          ? translate('Description.ArchivedExperience')
          : translate('Description.RestoredExperience');
        iconType = ResourceType.Universe;
        break;
      case EventType.PlayabilityChanged:
        translationString = translate('Description.PlayabilityChanged', {
          playability: customTranslatePlayability(data),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/configure`;
        break;
      case EventType.NotificationStringCreated:
        translationString = translate('Description.NotificationStringCreated', {
          stringName: embolden(data.StringName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/notifications`;
        break;
      case EventType.NotificationStringDeleted:
        translationString = translate('Description.NotificationStringDeleted', {
          stringName: embolden(data.StringName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/notifications`;
        break;
      case EventType.NotificationStringUpdated:
        translationString = translate('Description.NotificationStringUpdated', {
          stringName: embolden(data.StringName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/notifications`;
        break;
      case EventType.AvatarSettingsAvatarType:
        translationString = translate('Description.AvatarSettingsAvatarType', {
          avatarType: embolden(data.AvatarType),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsAnimation:
        translationString = translate('Description.AvatarSettingsAnimation', {
          animation: embolden(data.Animation),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsCollision:
        translationString = translate('Description.AvatarSettingsCollision', {
          collision: embolden(data.Collision),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsScaleHeight:
        translationString = translate('Description.AvatarSettingsScaleHeight', {
          scale: embolden(data.Scale),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsScaleWidth:
        translationString = translate('Description.AvatarSettingsScaleWidth', {
          scale: embolden(data.Scale),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsScaleHead:
        translationString = translate('Description.AvatarSettingsScaleHead', {
          scale: embolden(data.Scale),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsScaleBodyType:
        translationString = translate('Description.AvatarSettingsScaleBodyType', {
          scale: embolden(data.Scale),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsScaleProportions:
        translationString = translate('Description.AvatarSettingsScaleProportions', {
          scale: embolden(data.Scale),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsBodyParts:
        translationString = translate('Description.AvatarSettingsBodyParts');
        iconType = ResourceType.Universe;
        break;
      case EventType.AvatarSettingsClothing:
        translationString = translate('Description.AvatarSettingsClothing');
        iconType = ResourceType.Universe;
        break;
      case EventType.ExperienceName:
        translationString = translate('Description.ExperienceName', {
          newName: highlightLocation(data.NewName),
          oldName: highlightLocation(data.OldName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/configure`;
        break;
      case EventType.ExperienceDescription:
        translationString = translate('Description.ExperienceDescription');
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/configure`;
        break;
      case EventType.ExperienceGenre:
        translationString = translate('Description.ExperienceGenre', {
          genre: embolden(data.Genre),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/configure`;
        break;
      case EventType.SecuritySettingsHTTPRequests:
        translationString = translate('Description.SecuritySettingsHTTPRequests', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.SecuritySettingsStudioAccessToAPI:
        translationString = translate('Description.SecuritySettingsStudioAccessToAPI', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/configure`;
        break;
      case EventType.SecuritySettingsThirdPartySales:
        translationString = translate('Description.SecuritySettingsThirdPartySales', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.SecuritySettingsThirdPartyTeleports:
        translationString = translate('Description.SecuritySettingsThirdPartyTeleports', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.ExperienceShutDown:
        translationString = translate('Description.ExperienceShutDown');
        iconType = ResourceType.Universe;
        break;
      case EventType.SocialLinksAdded:
        translationString = translate('Description.SocialLinksAdded', {
          channel: embolden(data.Channel),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/social-links`;
        break;
      case EventType.SocialLinksRemoved:
        translationString = translate('Description.SocialLinksRemoved', {
          channel: embolden(data.Channel),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/social-links`;
        break;
      case EventType.SocialLinksUpdated:
        translationString = translate('Description.SocialLinksUpdated', {
          channel: embolden(data.Channel),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/social-links`;
        break;
      case EventType.SpatialVoice:
        translationString = translate('Description.SpatialVoice', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.WorldSettingsWorkSpaceGravity:
        translationString = translate('Description.WorldSettingsWorkSpaceGravity', {
          gravity: embolden(data.Gravity),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.WorldSettingsJumpHeight:
        translationString = translate('Description.WorldSettingsJumpHeight', {
          jumpHeight: embolden(data.JumpHeight),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.WorldSettingsJumpPower:
        translationString = translate('Description.WorldSettingsJumpPower', {
          jumpPower: embolden(data.JumpPower),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.WorldSettingsWalkSpeed:
        translationString = translate('Description.WorldSettingsWalkSpeed', {
          walkSpeed: embolden(data.WalkSpeed),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.WorldSettingsMaxSlopeAngle:
        translationString = translate('Description.WorldSettingsMaxSlopeAngle', {
          maxSlopeAngle: embolden(data.MaxSlopeAngle),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.SentUpdate:
        translationString = translate('Description.SentUpdate', { update: embolden(data.Update) });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/updates`;
        break;
      case EventType.SupportedLanguages:
        translationString = translate('Description.SupportedLanguages', {
          language: embolden(data.Language),
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionAdded')
              : translate('Description.ActionRemoved'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization`;
        break;
      case EventType.AutoTranslationExperienceInformation:
        translationString = translate('Description.AutoTranslationExperienceInformation', {
          language: embolden(data.Language),
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization`;
        break;
      case EventType.AutoTranslationExperienceStringsAndProducts:
        translationString = translate('Description.AutoTranslationExperienceStringsAndProducts', {
          language: embolden(data.Language),
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization`;
        break;
      case EventType.LocalizationSettingsAutomaticTextCapture:
        translationString = translate('Description.LocalizationSettingsAutomaticTextCapture', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization`;
        break;
      case EventType.LocalizationSettingsUserTranslatedContent:
        translationString = translate('Description.LocalizationSettingsUserTranslatedContent', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization`;
        break;
      case EventType.ClearUnmodifiedAutoCaptureEntries:
        translationString = '';
        iconType = ResourceType.Universe;
        break;
      case EventType.AnalyticsReport:
        translationString = '';
        iconType = ResourceType.Universe;
        break;
      case EventType.TranslationIconAdded:
        translationString = translate('Description.TranslationIconAdded', {
          language: embolden(data.Language),
          iconName: embolden(data.IconName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/catalog/${response.resourceId}`;
        break;
      case EventType.TranslationIconDeleted:
        translationString = translate('Description.TranslationIconDeleted', {
          language: embolden(data.Language),
          iconName: embolden(data.IconName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/catalog/${response.resourceId}`;
        break;
      case EventType.TranslationExperienceName:
        translationString = translate('Description.TranslationExperienceName', {
          language: embolden(data.Language),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationExperienceDescription:
        translationString = translate('Description.TranslationExperienceDescription', {
          language: embolden(data.Language),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationThumbnailAltText:
        translationString = translate('Description.TranslationThumbnailAltText', {
          language: embolden(data.Language),
          thumbnailName: embolden(data.ThumbnailName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationThumbnailAdded:
        translationString = translate('Description.TranslationThumbnailAdded', {
          language: embolden(data.Language),
          thumbnailName: embolden(data.ThumbnailName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationThumbnailDeleted:
        translationString = translate('Description.TranslationThumbnailDeleted', {
          language: embolden(data.Language),
          thumbnailName: embolden(data.ThumbnailName),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationThumbnailOrder:
        translationString = '';
        iconType = ResourceType.Universe;
        break;
      case EventType.TranslationStringAdded:
        translationString = translate('Description.TranslationStringAdded', {
          stringKey: embolden(data.StringKey),
          language: embolden(data.Language),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationStringDeleted:
        translationString = translate('Description.TranslationStringDeleted', {
          stringKey: embolden(data.StringKey),
          language: embolden(data.Language),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationStringUpdated:
        translationString = translate('Description.TranslationStringUpdated', {
          stringKey: embolden(data.StringKey),
          language: embolden(data.Language),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        break;
      case EventType.TranslationBadgeIconDeleted:
        translationString = translate('Description.TranslationBadgeIconDeleted', {
          language: embolden(data.Language),
          badgeName: embolden(data.BadgeName),
        });
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.TranslationBadgeDescription:
        translationString = translate('Description.TranslationBadgeDescription', {
          language: embolden(data.Language),
          badgeName: embolden(data.BadgeName),
        });
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.TranslationBadgeIconAdded:
        translationString = translate('Description.TranslationBadgeIconAdded', {
          language: embolden(data.Language),
          badgeName: embolden(data.BadgeName),
        });
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.TranslationBadgeName:
        translationString = translate('Description.TranslationBadgeName', {
          language: embolden(data.Language),
          badgeName: embolden(data.BadgeName),
        });
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.TranslationDeveloperProductIconDeleted:
        translationString = translate('Description.TranslationDeveloperProductIconDeleted', {
          language: embolden(data.Language),
          productName: embolden(data.ProductName),
        });
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.TranslationDeveloperProductDescription:
        translationString = translate('Description.TranslationDeveloperProductDescription', {
          language: embolden(data.Language),
          productName: embolden(data.ProductName),
        });
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.TranslationDeveloperProductIconAdded:
        translationString = translate('Description.TranslationDeveloperProductIconAdded', {
          language: embolden(data.Language),
          productName: embolden(data.ProductName),
        });
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.TranslationDeveloperProductName:
        translationString = translate('Description.TranslationDeveloperProductName', {
          language: embolden(data.Language),
          productName: embolden(data.ProductName),
        });
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.TranslationGamePassIconDeleted:
        translationString = translate('Description.TranslationGamePassIconDeleted', {
          language: embolden(data.Language),
          passName: embolden(data.PassName),
        });
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.TranslationGamePassDescription:
        translationString = translate('Description.TranslationGamePassDescription', {
          language: embolden(data.Language),
          passName: embolden(data.PassName),
        });
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.TranslationGamePassIconAdded:
        translationString = translate('Description.TranslationGamePassIconAdded', {
          language: embolden(data.Language),
          passName: embolden(data.PassName),
        });
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.TranslationGamePassName:
        translationString = translate('Description.TranslationGamePassName', {
          language: embolden(data.Language),
          passName: embolden(data.PassName),
        });
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/localization/translation`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.UserTranslator:
        translationString = translate('Description.UserTranslator', {
          userName: highlightUser(getUsername(response.resourceId ? response.resourceId : -1)),
        });
        iconType = ResourceType.User;
        viewBasicSettingsLink = `${universePath}/localization`;
        viewOnRobloxLink = targetUserPath;
        break;
      case EventType.GroupTranslator:
        translationString = translate('Description.GroupTranslator', {
          groupName: embolden(data.GroupName),
        });
        iconType = ResourceType.Group;
        viewBasicSettingsLink = `${universePath}/localization`;
        viewOnRobloxLink = groupPath;
        break;
      case EventType.ExperienceAdvertisement:
        translationString = translate('Description.ExperienceAdvertisement', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionCreated')
              : translate('Description.ActionRemoved'),
          ),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.MonetizationSettingsAccessType:
        translationString = translate('Description.MonetizationSettingsAccessType', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionFriendsTitle')
              : translate('Description.ActionPublic'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/access`;
        break;
      case EventType.MonetizationSettingsRequiresRobux:
        translationString = translate('Description.MonetizationSettingsRequiresRobux', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/access`;
        break;
      case EventType.MonetizationSettingsRobuxPrice:
        translationString = translate('Description.MonetizationSettingsRobuxPrice', {
          price: embolden(data.Price),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/access`;
        break;
      case EventType.MonetizationSettingsPlayableDevices:
        translationString = customTranslateMonetizationSettingsPlayableDevices(data);
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/access`;
        break;
      case EventType.MonetizationSettingsAllowPrivateServers:
        translationString = translate('Description.MonetizationSettingsAllowPrivateServers', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/access`;
        break;
      case EventType.MonetizationSettingsPrivateServerPrice:
        translationString = translate('Description.MonetizationSettingsPrivateServerPrice', {
          price: embolden(data.Price),
        });
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/access`;
        break;
      case EventType.ExperienceSponsor:
        translationString = translate('Description.ExperienceSponsor', {
          adName: embolden(data.AdName),
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionLaunched')
              : translate('Description.ActionDiscontinued'),
          ),
        });
        iconType = ResourceType.Universe;
        viewOnRobloxLink = `${wwwPath}/sponsorships/list?universeId=${response.universeId}`;
        break;
      case EventType.BadgeName:
        translationString = translate('Description.BadgeName', {
          newName: highlightLocation(data.NewName),
          oldName: highlightLocation(data.OldName),
        });
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/badges/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.BadgeDescription:
        translationString = translate('Description.BadgeDescription');
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/badges/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.BadgeIcon:
        translationString = translate('Description.BadgeIcon');
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/badges/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.BadgeCreate:
        translationString = translate('Description.BadgeCreate');
        iconType = ResourceType.Badge;
        viewBasicSettingsLink = `${universePath}/badges/${response.resourceId}/overview`;
        viewOnRobloxLink = `${wwwPath}/badges/${response.resourceId}`;
        break;
      case EventType.DeveloperProductName:
        translationString = translate('Description.DeveloperProductName', {
          newName: highlightLocation(data.NewName),
          oldName: highlightLocation(data.OldName),
        });
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/developer-products/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.DeveloperProductDescription:
        translationString = translate('Description.DeveloperProductDescription');
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/developer-products/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.DeveloperProductIcon:
        translationString = translate('Description.DeveloperProductIcon');
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/developer-products/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.DeveloperProductPrice:
        translationString = translate('Description.DeveloperProductPrice', {
          price: embolden(data.Price),
        });
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/developer-products/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.DeveloperProductCreate:
        translationString = translate('Description.DeveloperProductCreate');
        iconType = ResourceType.DeveloperProduct;
        viewBasicSettingsLink = `${universePath}/developer-products/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/developer-products/${response.resourceId}`;
        break;
      case EventType.GamePassName:
        translationString = translate('Description.GamePassName', {
          newName: highlightLocation(data.NewName),
          oldName: highlightLocation(data.OldName),
        });
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/passes/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.GamePassDescription:
        translationString = translate('Description.GamePassDescription');
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/passes/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.GamePassIcon:
        translationString = translate('Description.GamePassIcon');
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/passes/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.GamePassPrice:
        translationString = translate('Description.GamePassPrice', { price: embolden(data.Price) });
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/passes/${response.resourceId}/sales`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.GamePassCreate:
        translationString = translate('Description.GamePassCreate');
        iconType = ResourceType.GamePass;
        viewBasicSettingsLink = `${universePath}/passes/${response.resourceId}/configure`;
        viewOnRobloxLink = `${wwwPath}/game-pass/${response.resourceId}`;
        break;
      case EventType.PermissionsUserAdded:
        translationString = translate('Description.PermissionsUserAdded', {
          userName: highlightUser(getUsername(response.resourceId)),
          role: embolden(
            data.Action === 'Edit' ? translate('Action.Edit') : translate('Action.Play'),
          ),
        });
        iconType = ResourceType.User;
        viewOnRobloxLink = targetUserPath;
        thumbnailLink = targetUserPath;
        break;
      case EventType.PermissionsGroupAdded:
        translationString = translate('Description.PermissionsGroupAdded', {
          groupRole: embolden(data.RolesetName),
          groupName: embolden(data.GroupName),
          role: embolden(
            data.Action === 'Edit' ? translate('Action.Edit') : translate('Action.Play'),
          ),
        });
        iconType = ResourceType.Group;
        viewOnRobloxLink = `${wwwPath}/groups/${response.resourceId}`;
        break;
      case EventType.PermissionsUserChanged:
        translationString = translate('Description.PermissionsUserChanged', {
          userName: highlightUser(getUsername(response.resourceId)),
          oldRole: embolden(
            data.Action === 'Edit' ? translate('Action.Play') : translate('Action.Edit'),
          ),
          newRole: embolden(
            data.Action === 'Edit' ? translate('Action.Edit') : translate('Action.Play'),
          ),
        });
        iconType = ResourceType.User;
        viewOnRobloxLink = targetUserPath;
        thumbnailLink = targetUserPath;
        break;
      case EventType.PermissionsUserRemoved:
        translationString = translate('Description.PermissionsUserRemoved', {
          userName: highlightUser(getUsername(response.resourceId)),
          role: embolden(
            data.Action === 'Edit'
              ? translate('Description.RoleEditor')
              : translate('Description.RolePlayer'),
          ),
        });
        iconType = ResourceType.User;
        viewOnRobloxLink = targetUserPath;
        thumbnailLink = targetUserPath;
        break;
      case EventType.PermissionsGroupChanged:
        translationString = translate('Description.PermissionsGroupChanged', {
          groupRole: embolden(data.RolesetName),
          groupName: embolden(data.GroupName),
          oldRole: embolden(
            data.Action === 'Edit' ? translate('Action.Play') : translate('Action.Edit'),
          ),
          newRole: embolden(
            data.Action === 'Edit' ? translate('Action.Edit') : translate('Action.Play'),
          ),
        });
        iconType = ResourceType.Group;
        viewOnRobloxLink = `${wwwPath}/groups/${response.resourceId}`;
        break;
      case EventType.PermissionsGroupRemoved:
        translationString = translate('Description.PermissionsGroupRemoved', {
          groupRole: embolden(data.RolesetName),
          groupName: embolden(data.GroupName),
          role: embolden(
            data.Action === 'Edit'
              ? translate('Description.RoleEditor')
              : translate('Description.RolePlayer'),
          ),
        });
        iconType = ResourceType.Group;
        viewOnRobloxLink = `${wwwPath}/groups/${response.resourceId}`;
        break;
      case EventType.TeamCreate:
        translationString = translate('Description.TeamCreate', {
          userName: highlightUser(getUsername(response.resourceId)),
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionJoined')
              : translate('Description.ActionLeft'),
          ),
        });
        iconType = ResourceType.User;
        viewOnRobloxLink = userPath;
        break;
      case EventType.PlaceIconAutoGenerated:
        translationString = translate('Description.PlaceIconAutoGenerated');
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/icon`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceIconChanged:
        translationString = translate('Description.PlaceIconChanged');
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/icon`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceIconRemoved:
        translationString = translate('Description.PlaceIconRemoved');
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/icon`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceGearGenresOnlyAllowFromExperiencesGenre:
        translationString = translate('Description.PlaceGearGenresOnlyAllowFromExperiencesGenre');
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/permissions`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceGearGenresAllowAllGearGenres:
        translationString = translate('Description.PlaceGearGenresAllowAllGearGenres');
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/permissions`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceGearTypes:
        translationString = translate('Description.PlaceGearTypes', {
          gearTypes: embolden(joinStrings(data.GearTypes)),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/permissions`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceDownloadPermission:
        translationString = translate('Description.PlaceDownloadPermission', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
          placeName: highlightLocation(data.PlaceName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/permissions`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceGenre:
        translationString = translate('Description.PlaceGenre', { genre: embolden(data.Genre) });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/configure`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceName:
        translationString = translate('Description.PlaceName', {
          newName: highlightLocation(data.NewName),
          oldName: highlightLocation(data.OldName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/configure`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceDescription:
        translationString = translate('Description.PlaceDescription', {
          placeName: highlightLocation(data.PlaceName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/configure`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceMaxVisitorCount:
        translationString = translate('Description.PlaceMaxVisitorCount', {
          count: embolden(data.Count),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/access`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceSocialSlotsRobloxOptimized:
        translationString = translate('Description.PlaceSocialSlotsRobloxOptimized');
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/access`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceSocialSlotsDisabled:
        translationString = translate('Description.PlaceSocialSlotsDisabled');
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/access`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceSocialSlotsCustomize:
        translationString = translate('Description.PlaceSocialSlotsCustomize', {
          count: embolden(data.Count),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/access`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlacePermissionsCreatePlaceAPI:
        translationString = translate('Description.PlacePermissionsCreatePlaceAPI', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
          placeName: highlightLocation(data.PlaceName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/permissions`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlacePermissionsSavePlaceAPI:
        translationString = translate('Description.PlacePermissionsSavePlaceAPI', {
          action: embolden(
            stringToBool(data.Action)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
          placeName: highlightLocation(data.PlaceName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/permissions`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceRevert:
        translationString = translate('Description.PlaceRevert', {
          placeName: highlightLocation(data.PlaceName),
          oldVersion: embolden(data.OldVersion),
          newVersion: embolden(data.NewVersion),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/version-history`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceShutDown:
        translationString = translate('Description.PlaceShutDown');
        iconType = ResourceType.Place;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceRestart:
        translationString = translate('Description.PlaceRestart');
        iconType = ResourceType.Place;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceThumbnailAltText:
        translationString = translate('Description.PlaceThumbnailAltText', {
          thumbnailName: embolden(data.ThumbnailName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/thumbnails`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceThumbnailAdded:
        translationString = translate('Description.PlaceThumbnailAdded', {
          thumbnailName: embolden(data.ThumbnailName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/thumbnails`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceThumbnailOrder:
        translationString = '';
        iconType = ResourceType.Universe;
        break;
      case EventType.PlaceThumbnailDeleted:
        translationString = translate('Description.PlaceThumbnailDeleted', {
          thumbnailName: embolden(data.ThumbnailName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/${response.placeId}/thumbnails`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceAdded:
        translationString = translate('Description.PlaceAdded', {
          placeName: highlightLocation(data.PlaceName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/manage`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlaceRemoved:
        translationString = translate('Description.PlaceRemoved', {
          placeName: highlightLocation(data.PlaceName),
        });
        iconType = ResourceType.Place;
        viewBasicSettingsLink = `${universePath}/places/manage`;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.PlacePublished:
        translationString = translate('Description.PlacePublished', {
          placeName: highlightLocation(data.PlaceName),
          newVersion: tostring(data.NewVersion),
        });
        iconType = ResourceType.Place;
        viewOnRobloxLink = `${wwwPath}/games/${response.placeId}`;
        break;
      case EventType.CompletedQuestionnaire:
        translationString = translate('Description.CompletedQuestionnaireMaturity');
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/experience-questionnaire`;
        break;
      case EventType.MonetizationSettingsPrivateServerRequiresRobux:
        translationString = translate(
          'Description.MonetizationSettingsPrivateServerRequiresRobux',
          {
            action: embolden(
              stringToBool(data.Action)
                ? translate('Description.ActionEnabled')
                : translate('Description.ActionDisabled'),
            ),
          },
        );
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/access`;
        break;
      case EventType.SecuritySettingsEditableMeshAndTextureAPIAccess:
        translationString = translate(
          'Description.SecuritySettingsEditableMeshAndTextureAPIAccess',
          {
            action: embolden(
              stringToBool(data.Action)
                ? translate('Description.ActionEnabled')
                : translate('Description.ActionDisabled'),
            ),
          },
        );
        iconType = ResourceType.Universe;
        viewBasicSettingsLink = `${universePath}/configure`;
        break;
      case EventType.PackagePublish:
        translationString = translate('Description.PackagePublish', {
          packageName: embolden(data.PackageName),
          versionNumber: data.VersionNumber,
          numberOfPackages: data.NumberOfPackages,
          totalPackages: data.TotalPackages,
        });
        iconType = ResourceType.Place;
        break;
      case EventType.PackageManualUpdate:
        translationString = translate('Description.PackageManualUpdate', {
          packageName: embolden(data.PackageName),
          versionNumber: data.VersionNumber,
          numberOfPackages: data.NumberOfPackages,
          totalPackages: data.TotalPackages,
        });
        iconType = ResourceType.Place;
        break;
      case EventType.PackageAutoUpdate:
        translationString = translate('Description.PackageAutoUpdate', {
          packageName: embolden(data.PackageName),
          versionNumber: data.VersionNumber,
          numberOfPackages: data.NumberOfPackages,
          totalPackages: data.TotalPackages,
          failedPackages: data.FailedPackages,
        });
        iconType = ResourceType.Place;
        break;
      case EventType.PackageAutoUpdateToggle:
        translationString = translate('Description.PackageAutoUpdateToggle', {
          packageName: embolden(data.PackageName),
          versionNumber: data.VersionNumber,
          numberOfPackages: data.NumberOfPackages,
          totalPackages: data.TotalPackages,
          action: embolden(
            stringToBool(data.AutoUpdate)
              ? translate('Description.ActionEnabled')
              : translate('Description.ActionDisabled'),
          ),
        });
        iconType = ResourceType.Place;
        break;
      case EventType.PayoutsConfigured:
        translationString = customTranslateRecurringPayouts(
          data,
          'Description.PayoutsConfiguredWithMembers',
          'Description.ExperiencePayoutsConfiguredWithMembers',
        );
        iconType = ResourceType.Robux;
        break;
      case EventType.ExperiencePermissionsUpdated:
        translationString = customTranslatePermissions(
          data,
          'Description.ExperiencePermissionsUpdated',
          'Description.ExperiencePermissionsRevoked',
        );
        iconType = ResourceType.Universe;
        break;
      case EventType.ExperienceCreated:
        translationString = translate('Description.ExperienceCreated', {
          experienceName: embolden(data.experienceName),
        });
        iconType = ResourceType.Universe;
        break;
      case EventType.AdCreated:
        translationString = translate('Description.AdCreated', {
          experienceName: embolden(data.experienceName),
        });
        iconType = ResourceType.Robux;
        break;
      case EventType.PlaceModerated:
        translationString = translate('Description.PlaceModerated', {
          placeName: embolden(data.placeName),
          experienceName: embolden(data.experienceName),
        });
        iconType = ResourceType.Place;
        break;
      case EventType.AssetModerated:
        translationString = translate('Description.AssetModerated', {
          assetName: embolden(data.assetName),
          infractionType: embolden(data.infractionType),
        });
        iconType = ResourceType.Asset;
        break;
      case EventType.EscapeHatchSaveCopyToCloud:
        translationString = translate('Description.EscapeHatchSaveCopyToCloud', {
          oldName: highlightLocation(data.OldName),
          newName: highlightLocation(data.NewName),
        });
        iconType = ResourceType.Universe;
        break;
      // End of Generated Code 🤖
      // INSERT CODE HERE ☝️
      default:
        iconId = 0;
        iconType = ResourceType.Universe;
        translationString = '';
        changedByLink = '';
        viewBasicSettingsLink = '';
        viewOnRobloxLink = '';
    }
  } catch (error) {
    iconType = ResourceType.Universe;
    translationString = '';
    console.error(
      `Error parsing ${response.eventType}: ${String(error)}\n Metadata was: ${JSON.stringify(data)}`,
    );
  }

  // oxlint-disable-next-line typescript/switch-exhaustiveness-check
  switch (iconType) {
    case ResourceType.Universe:
      iconId = rootPlaceId;
      thumbnailLink = `${universePath}/overview`;
      break;
    case ResourceType.Place:
      iconId = response.placeId ?? 0;
      location = placeNames[iconId];
      locationLink = `${placePath}/configure`;
      thumbnailLink = `${placePath}/configure`;
      break;
    case ResourceType.User:
      iconId = response.resourceId ?? 0;
      thumbnailLink = targetUserPath;
      break;
    case ResourceType.Badge:
      iconId = response.resourceId ?? 0;
      thumbnailLink = badgePath;
      break;
    case ResourceType.DeveloperProduct:
      iconId = response.resourceId ?? 0;
      thumbnailLink = developerProductPath;
      viewOnRobloxLink = '';
      break;
    case ResourceType.GamePass:
      iconId = response.resourceId ?? 0;
      thumbnailLink = gamePassPath;
      break;
    case ResourceType.Group:
      iconId = response.resourceId ?? 0;
      thumbnailLink = groupPath;
      break;
    default:
      iconId = 0;
      thumbnailLink = '';
  }

  return {
    filters,
    id: response.id,
    iconId,
    iconType,
    translationString,
    username: usernames[response.userId],
    location,
    changedByLink,
    locationLink,
    thumbnailLink,
    viewBasicSettingsLink,
    viewOnRobloxLink,
    dateTime,
  };
}

export interface ActivityFeedItemInfo {
  filters: {
    eventType: EventType;
    userId: number;
    placeId?: number;
    createdUtc: number;
  };
  id: number;
  iconId: number;
  iconType: ResourceType;
  translationString: string;
  username: string;
  location: string;
  changedByLink: string;
  locationLink?: string;
  thumbnailLink: string;
  viewBasicSettingsLink?: string;
  viewOnRobloxLink?: string;
  dateTime: string;
}

// Once activity feed service is set up, we can import the service response interface from there
// For now it will be hard coded here
export interface ActivityFeedEvent {
  id: number;
  eventType: EventType;
  userId: number;
  universeId?: number;
  placeId?: number;
  resourceId?: number;
  metaData: string;
  createdUnixTimeMs: number;
  organizationId?: number;
}
export interface ActivityFeedServiceResponse {
  events: ActivityFeedEvent[];
  nextCursor: string | undefined;
  hasMore: boolean | undefined;
}

export function useActivityFeedItemInfo(universeId: number, responses: ActivityFeedEvent[]) {
  const { translate } = useTranslation();
  const { locale } = useLocalization();

  const [usernames, setUsernames] = useState<Record<number, string>>({ '-1': '' });
  const [placeNames, setPlaceNames] = useState<Record<number, string>>({ '-1': '' });
  const [rootPlaceId, setRootPlaceId] = useState<number>(-1);
  const [activityFeedItemInfo, setActivityFeedItemInfo] = useState<ActivityFeedItemInfo[]>([]);
  const [loadingInfo, setLoadingInfo] = useState<Record<string, boolean>>({
    loadingUsernames: true,
    loadingPlaceNames: true,
    loadingRootPlaceId: true,
  });
  const [error, setError] = useState(false);

  const getDateTime = useMemo(() => {
    const formatter = new Intl.DateTimeFormat(locale ?? Locale.English, {
      dateStyle: 'long',
      timeStyle: 'short',
    });
    return (createdUtc: number) => {
      const dateText = new Date(createdUtc);
      return formatter.format(dateText);
    };
  }, [locale]);

  // Fetch usernames associated with all events.
  useEffect(() => {
    const getUsernames = async () => {
      setLoadingInfo((prevInfo) => ({
        ...prevInfo,
        loadingUsernames: true,
      }));

      // Create a set of all unique user ids to make a batched request
      const userIds = new Set<number>();
      responses.forEach((res) => {
        userIds.add(res.userId);
        if (usernameEvents.has(res.eventType) && res.resourceId) {
          userIds.add(res.resourceId);
        }
      });

      // Send request for user data
      if (userIds.size !== 0) {
        try {
          const usersResponse = await usersClient.getUsersByIds(Array.from(userIds));
          if (!usersResponse.data) {
            throw new Error('Data was null in getUsersByIds response');
          }
          const usernameMap = Object.fromEntries(
            usersResponse.data
              .filter((user) => user.id && user.displayName)
              .map((user) => [user.id, user.displayName]),
          );
          setUsernames(usernameMap);
        } catch {
          setError(true);
        }
      }

      setLoadingInfo((prevInfo) => ({
        ...prevInfo,
        loadingUsernames: false,
      }));
    };

    void getUsernames();
  }, [responses]);

  // Fetch up-to-date place names from place ids
  useEffect(() => {
    const placeIds = new Set<number>();
    responses.forEach((res) => {
      if (res.placeId) {
        placeIds.add(res.placeId);
      }
    });
    // Return early if there are no places to fetch.
    if (placeIds.size === 0) {
      setLoadingInfo((prevInfo) => ({
        ...prevInfo,
        loadingPlaceNames: false,
      }));
      return;
    }

    setLoadingInfo((prevInfo) => ({
      ...prevInfo,
      loadingPlaceNames: true,
    }));
    const getPlaceNames = async () => {
      // Send request for place names
      try {
        const placesResponse = await gamesClient.multigetPlaceDetails(Array.from(placeIds));
        const placesMap = Object.fromEntries(
          placesResponse.map((place) => [place.placeId, place.name]),
        );
        setPlaceNames(placesMap);
        setLoadingInfo((prevInfo) => ({
          ...prevInfo,
          loadingPlaceNames: false,
        }));
      } catch {
        setError(true);
      }
    };
    void getPlaceNames();
  }, [responses]);

  // Fetch the root place id for this experience.
  useEffect(() => {
    const getRootPlaceId = async () => {
      setLoadingInfo((prevInfo) => ({
        ...prevInfo,
        loadingRootPlaceId: true,
      }));

      try {
        const universeDetailResponse = await developClient.getUniverseDetails(universeId);
        setRootPlaceId(universeDetailResponse.rootPlaceId ?? -1);
      } catch {
        setError(true);
      }

      setLoadingInfo((prevInfo) => ({
        ...prevInfo,
        loadingRootPlaceId: false,
      }));
    };
    if (universeId !== -1) {
      void getRootPlaceId();
    }
  }, [universeId]);

  // If the pre-requisite metadata (e.g. usernames) is finished loading, parse all activity feed events.
  const loading = Object.values(loadingInfo).some((isLoading) => isLoading);
  useEffect(() => {
    // If any data is still being fetched, return early.
    if (loading) {
      return;
    }
    // Else, parse all the data.
    const newActivityFeedItemInfo = [];
    for (const response of responses) {
      newActivityFeedItemInfo.push(
        parseActivityFeedItemInfo(
          response,
          usernames,
          placeNames,
          rootPlaceId,
          getDateTime,
          translate,
        ),
      );
    }
    setActivityFeedItemInfo(newActivityFeedItemInfo);
  }, [loadingInfo, getDateTime, loading, placeNames, responses, rootPlaceId, translate, usernames]);

  return {
    isLoading: loading,
    error,
    usernames: Object.values(usernames).filter((value) => value !== ''),
    placeNames: Object.values(placeNames).filter((value) => value !== ''),
    activityFeedItemInfo,
  };
}
