/**
 * Foundation's <Tooltip> renders its `title` slot as semibold (text-caption-medium
 * weight). Creative-library tooltips are specced as body-small — same size, regular
 * weight. This arbitrary-property override forces weight 400 on the tooltip content,
 * scoped per-instance via `contentClassName`, so the shared Foundation component is
 * left untouched. (`font-normal` isn't generated by the foundation Tailwind preset,
 * hence the arbitrary `[font-weight:400]`.)
 */
export const FOUNDATION_TOOLTIP_BODY_SMALL_CLASS = '[&_div]:[font-weight:400]';
