export const MAX_PRIMARY_KEYWORD_LENGTH = 100;
export const MAX_SECONDARY_KEYWORD_LENGTH = 50;

export const MAX_IP_CONTENT_IMAGES = 50;
export const MIN_IP_CONTENT_IMAGE_UPLOAD = 10;
export const MAX_IP_FAMILY_NAME_LENGTH = 100;
export const MAX_IP_CONTENT_IMAGE_SIZE_MB = 10;
export const MAX_IP_CONTENT_IMAGE_ASPECT_RATIO = 16 / 9;
export const MIN_IP_CONTENT_IMAGE_ASPECT_RATIO = 9 / 16;
export const MIN_IP_CONTENT_IMAGE_RESOLUTION = [224, 224];
export const MAX_SUPPORTING_DOCUMENT_SIZE_MB = 20;
export const MAX_SUPPORTING_DOCUMENT_COUNT = 3;
export const MAX_CITATION_LENGTH = 100;
