import React, { FunctionComponent, useCallback, useMemo, useState } from 'react';
import { ReturnPolicy, Thumbnail2d, ThumbnailTypes } from '@rbx/thumbnails';
import { Button, CheckIcon, FormHelperText, Grid, Typography } from '@rbx/ui';
import { useTranslation } from '@rbx/intl';
import { CreationData } from '@modules/creations/common';
import GenericBEDEV1Error from '@modules/clients/errors/GenericBEDEV1Error';
// eslint-disable-next-line no-restricted-imports -- deep import into creations module; will be resolved when creations barrel is removed (Phase 5)
import UniverseAPIErrorCodes from '@modules/creations/common/enums/UniverseAPIErrorCodes';
import universesClient from '@modules/clients/universes';
import { useCurrentGame } from '@modules/providers/game/GameProvider';
import PlacesManagementItemCardTitle from './PlacesManagementItemCardTitle';
import usePlacesManagementItemCardStyles from './PlacesManagementItemCard.styles';

export interface PlacesManagementItemCardProps {
  item: CreationData;
  isLoading: boolean;
  updateItem: (item: CreationData) => void;
}

const PlacesManagementItemCard: FunctionComponent<
  React.PropsWithChildren<PlacesManagementItemCardProps>
> = ({ item, isLoading, updateItem }) => {
  const {
    classes: {
      itemCardContainer,
      thumbnailImgStyles,
      itemCardTitle,
      errorMessage,
      button,
      addedInfo,
      divStyle,
    },
  } = usePlacesManagementItemCardStyles();
  const { translate } = useTranslation();
  const { gameDetails } = useCurrentGame();
  const [errorMsg, setErrorMsg] = useState<string>('');
  const [isButtonLoading, setIsButtonLoading] = useState<boolean>(false);

  const isPlaceAdded = useMemo(() => {
    // NOTE (jcountryman, 2/6/24): Turned off to check in @rbx/ui upgrade. Codeowners is
    // responsible for triaging issue.
    // eslint-disable-next-line valid-typeof -- legacy typeof check; triage tracked with @rbx/ui upgrade
    const isAdded = typeof item.universeId !== undefined && item.universeId === gameDetails?.id;
    if (isAdded) {
      setErrorMsg('');
    }
    return isAdded;
  }, [gameDetails?.id, item.universeId]);

  const handleAddPlace = useCallback(async () => {
    setIsButtonLoading(true);
    setErrorMsg('');
    try {
      if (typeof gameDetails?.id === 'undefined' || typeof item.placeId === 'undefined') {
        throw new GenericBEDEV1Error(
          UniverseAPIErrorCodes.UnknownError,
          translate('Response.UnknownError'),
        );
      }

      const request = { universeId: gameDetails?.id, placeId: item.placeId };
      await universesClient.addPlaceToUniverse(request);
      updateItem({ ...item, name: gameDetails?.name, universeId: gameDetails?.id });
    } catch (error) {
      if (
        error instanceof GenericBEDEV1Error &&
        Object.values(UniverseAPIErrorCodes).includes(error.code)
      ) {
        const errorCode = error.code as UniverseAPIErrorCodes;
        const nameOfError = UniverseAPIErrorCodes[errorCode];
        setErrorMsg(translate(`Error.${nameOfError}`));
      } else {
        setErrorMsg(translate('Response.UnknownError'));
      }
    } finally {
      setIsButtonLoading(false);
    }
  }, [gameDetails?.id, gameDetails?.name, item, translate, updateItem]);

  return (
    <Grid
      data-testid='places-management-item-card-testId'
      container
      classes={{ root: itemCardContainer }}
      direction='column'>
      <Thumbnail2d
        containerClass={thumbnailImgStyles}
        type={ThumbnailTypes.placeIcon}
        targetId={item.placeId ?? 0}
        returnPolicy={ReturnPolicy.AutoGenerated}
        alt={item.placeName ?? ''}
        isPendingNewTarget={isLoading}
        includeBackground
      />
      <Grid item classes={{ root: itemCardTitle }}>
        <PlacesManagementItemCardTitle
          placeName={item.placeName ?? ''}
          experienceName={item.name ?? ''}
          isLoading={isLoading}
          isDisabled={item.isStartPlace ?? false}
        />
      </Grid>
      <Grid item>
        {(!isPlaceAdded || item.isStartPlace) && (
          <Button
            data-testid='add-place-button'
            variant='contained'
            color='primary'
            size='small'
            loading={isButtonLoading}
            onClick={handleAddPlace}
            disabled={item.isStartPlace ?? false}
            classes={{ root: button }}>
            {translate('Button.AddPlace')}
          </Button>
        )}
        {item.isStartPlace && (
          <FormHelperText error classes={{ root: errorMessage }}>
            {translate('Error.startPlace')}
          </FormHelperText>
        )}
        {errorMsg && (
          <FormHelperText error classes={{ root: errorMessage }}>
            {errorMsg}
          </FormHelperText>
        )}
      </Grid>
      {!item.isStartPlace && isPlaceAdded && (
        <div data-testid='place-added-div' className={divStyle}>
          <CheckIcon fontSize='small' />
          <Typography variant='body2' color='success' className={addedInfo}>
            {translate('Message.Added')}
          </Typography>
        </div>
      )}
    </Grid>
  );
};

export default PlacesManagementItemCard;
