import { Genres, NewGenres } from '@constants/advancedTargeting';
import { AgeBucketType, DeviceType, Gender } from '@modules/clients/ads/adsClientTypes';
import { AdFormatType } from '@type/ad';
import { TODOFIXANY } from 'app/shared/types';

export interface FormInputObj {
  label?: string;
  title?: string;
  value: string | number;
}

export interface LocationsFormInputObj extends FormInputObj {
  countryCode: string;
}

export interface RegionsFormInputObj extends FormInputObj {
  regionCode: string;
}

export interface RegionsAndLocationsFormInputObj extends FormInputObj {
  countryCode?: string;
  nonEU?: boolean;
  parentRegion?: boolean;
  regionCode: string;
  superGroup?: boolean;
}

export interface LanguageFormInputObj extends FormInputObj {
  langCode: string;
}

export interface GenreFormInputObj extends FormInputObj {
  deprecated: boolean;
  description: string;
  title: string;
  value: number;
}

export const allLocationsObj = {
  countryCode: 'All',
  isAll: true,
  regionCode: 'All',
  title: 'All Regions',
  value: 1,
};

export const allNonEULocationsObj = {
  countryCode: 'AllNonEU',
  regionCode: 'AllNonEU',
  title: 'All Non-EU Regions',
  value: 50,
};

// Mapped to: https://github.rbx.com/Roblox/ads/blob/26dd1ce78fabd5c9272dde4de4cd84622e2cb653/protos/roblox/ads/shared/targeting/v1/targeting_criteria.proto#L84
export const locations: LocationsFormInputObj[] = [
  allLocationsObj,
  { countryCode: 'US', title: 'United States', value: 2 },
  { countryCode: 'GB', title: 'United Kingdom', value: 3 },
  { countryCode: 'CA', title: 'Canada', value: 4 },
  { countryCode: 'AF', title: 'Afghanistan', value: 5 },
  { countryCode: 'AL', title: 'Albania', value: 7 },
  { countryCode: 'DZ', title: 'Algeria', value: 8 },
  { countryCode: 'AD', title: 'Andorra', value: 10 },
  { countryCode: 'AO', title: 'Angola', value: 11 },
  { countryCode: 'AI', title: 'Anguilla', value: 12 },
  { countryCode: 'AQ', title: 'Antarctica', value: 13 },
  { countryCode: 'AG', title: 'Antigua and Barbuda', value: 14 },
  { countryCode: 'AR', title: 'Argentina', value: 15 },
  { countryCode: 'AM', title: 'Armenia', value: 16 },
  { countryCode: 'AW', title: 'Aruba', value: 17 },
  { countryCode: 'AU', title: 'Australia', value: 18 },
  { countryCode: 'AT', title: 'Austria', value: 19 },
  { countryCode: 'AZ', title: 'Azerbaijan', value: 20 },
  { countryCode: 'BS', title: 'Bahamas, The', value: 21 },
  { countryCode: 'BH', title: 'Bahrain', value: 22 },
  { countryCode: 'BD', title: 'Bangladesh', value: 23 },
  { countryCode: 'BB', title: 'Barbados', value: 24 },
  { countryCode: 'BY', title: 'Belarus', value: 25 },
  { countryCode: 'BE', title: 'Belgium', value: 26 },
  { countryCode: 'BZ', title: 'Belize', value: 27 },
  { countryCode: 'BJ', title: 'Benin', value: 28 },
  { countryCode: 'BT', title: 'Bhutan', value: 30 },
  { countryCode: 'BO', title: 'Bolivia', value: 31 },
  { countryCode: 'BA', title: 'Bosnia and Herzegovina', value: 33 },
  { countryCode: 'BW', title: 'Botswana', value: 34 },
  { countryCode: 'BR', title: 'Brazil', value: 36 },
  { countryCode: 'BN', title: 'Brunei Darussalam', value: 38 },
  { countryCode: 'BG', title: 'Bulgaria', value: 39 },
  { countryCode: 'BF', title: 'Burkina Faso', value: 40 },
  { countryCode: 'BI', title: 'Burundi', value: 41 },
  { countryCode: 'KH', title: 'Cambodia', value: 42 },
  { countryCode: 'CM', title: 'Cameroon', value: 43 },
  { countryCode: 'KY', title: 'Cayman Islands', value: 45 },
  { countryCode: 'CF', title: 'Central African Republic', value: 46 },
  { countryCode: 'TD', title: 'Chad', value: 47 },
  { countryCode: 'CL', title: 'Chile', value: 48 },
  { countryCode: 'CN', title: 'China', value: 49 },
  { countryCode: 'CO', title: 'Colombia', value: 52 },
  { countryCode: 'KM', title: 'Comoros', value: 53 },
  { countryCode: 'CG', title: 'Congo', value: 54 },
  { countryCode: 'CD', title: 'Congo, The Democratic Republic of the', value: 55 },
  { countryCode: 'CR', title: 'Costa Rica', value: 57 },
  { countryCode: 'CI', title: "Cote D'ivoire", value: 58 },
  { countryCode: 'HR', title: 'Croatia', value: 59 },
  { countryCode: 'CU', title: 'Cuba', value: 60 },
  { countryCode: 'CY', title: 'Cyprus', value: 62 },
  { countryCode: 'CZ', title: 'Czech Republic', value: 63 },
  { countryCode: 'DK', title: 'Denmark', value: 64 },
  { countryCode: 'DJ', title: 'Djibouti', value: 65 },
  { countryCode: 'DM', title: 'Dominica', value: 66 },
  { countryCode: 'DO', title: 'Dominican Republic', value: 67 },
  { countryCode: 'EC', title: 'Ecuador', value: 68 },
  { countryCode: 'EG', title: 'Egypt', value: 69 },
  { countryCode: 'SV', title: 'El Salvador', value: 70 },
  { countryCode: 'GQ', title: 'Equatorial Guinea', value: 71 },
  { countryCode: 'ER', title: 'Eritrea', value: 72 },
  { countryCode: 'EE', title: 'Estonia', value: 73 },
  { countryCode: 'ET', title: 'Ethiopia', value: 74 },
  { countryCode: 'FJ', title: 'Fiji', value: 77 },
  { countryCode: 'FI', title: 'Finland', value: 78 },
  { countryCode: 'FR', title: 'France', value: 79 },
  { countryCode: 'GA', title: 'Gabon', value: 83 },
  { countryCode: 'GM', title: 'Gambia, The', value: 84 },
  { countryCode: 'GE', title: 'Georgia', value: 85 },
  { countryCode: 'DE', title: 'Germany', value: 86 },
  { countryCode: 'GH', title: 'Ghana', value: 87 },
  { countryCode: 'GR', title: 'Greece', value: 89 },
  { countryCode: 'GD', title: 'Grenada', value: 91 },
  { countryCode: 'GT', title: 'Guatemala', value: 94 },
  { countryCode: 'GN', title: 'Guinea', value: 96 },
  { countryCode: 'GW', title: 'Guinea-Bissau', value: 97 },
  { countryCode: 'GY', title: 'Guyana', value: 98 },
  { countryCode: 'HT', title: 'Haiti', value: 99 },
  { countryCode: 'HN', title: 'Honduras', value: 102 },
  { countryCode: 'HU', title: 'Hungary', value: 104 },
  { countryCode: 'IS', title: 'Iceland', value: 105 },
  { countryCode: 'IN', title: 'India', value: 106 },
  { countryCode: 'ID', title: 'Indonesia', value: 107 },
  { countryCode: 'IQ', title: 'Iraq', value: 108 },
  { countryCode: 'IE', title: 'Ireland', value: 109 },
  { countryCode: 'IL', title: 'Israel', value: 111 },
  { countryCode: 'IT', title: 'Italy', value: 112 },
  { countryCode: 'JM', title: 'Jamaica', value: 113 },
  { countryCode: 'JP', title: 'Japan', value: 114 },
  { countryCode: 'JO', title: 'Jordan', value: 116 },
  { countryCode: 'KZ', title: 'Kazakhstan', value: 117 },
  { countryCode: 'KE', title: 'Kenya', value: 118 },
  { countryCode: 'KI', title: 'Kiribati', value: 119 },
  { countryCode: 'KR', title: 'Korea, Republic of', value: 120 },
  { countryCode: 'KW', title: 'Kuwait', value: 122 },
  { countryCode: 'KG', title: 'Kyrgyzstan', value: 123 },
  { countryCode: 'LA', title: "Lao People's Democratic Republic", value: 124 },
  { countryCode: 'LV', title: 'Latvia', value: 125 },
  { countryCode: 'LB', title: 'Lebanon', value: 126 },
  { countryCode: 'LS', title: 'Lesotho', value: 127 },
  { countryCode: 'LR', title: 'Liberia', value: 128 },
  { countryCode: 'LY', title: 'Libya', value: 129 },
  { countryCode: 'LI', title: 'Liechtenstein', value: 130 },
  { countryCode: 'LT', title: 'Lithuania', value: 131 },
  { countryCode: 'LU', title: 'Luxembourg', value: 132 },
  { countryCode: 'MK', title: 'Macedonia, The Former Yugoslav Republic of', value: 134 },
  { countryCode: 'MG', title: 'Madagascar', value: 135 },
  { countryCode: 'MW', title: 'Malawi', value: 136 },
  { countryCode: 'MY', title: 'Malaysia', value: 137 },
  { countryCode: 'MV', title: 'Maldives', value: 138 },
  { countryCode: 'ML', title: 'Mali', value: 139 },
  { countryCode: 'MT', title: 'Malta', value: 140 },
  { countryCode: 'MH', title: 'Marshall Islands', value: 141 },
  { countryCode: 'MR', title: 'Mauritania', value: 143 },
  { countryCode: 'MU', title: 'Mauritius', value: 144 },
  { countryCode: 'MX', title: 'Mexico', value: 146 },
  { countryCode: 'FM', title: 'Micronesia, Federated States of', value: 147 },
  { countryCode: 'MD', title: 'Moldova, Republic of', value: 148 },
  { countryCode: 'MC', title: 'Monaco', value: 149 },
  { countryCode: 'MN', title: 'Mongolia', value: 150 },
  { countryCode: 'ME', title: 'Montenegro', value: 151 },
  { countryCode: 'MA', title: 'Morocco', value: 153 },
  { countryCode: 'MZ', title: 'Mozambique', value: 154 },
  { countryCode: 'MM', title: 'Myanmar', value: 155 },
  { countryCode: 'NA', title: 'Namibia', value: 156 },
  { countryCode: 'NR', title: 'Nauru', value: 157 },
  { countryCode: 'NP', title: 'Nepal', value: 158 },
  { countryCode: 'NL', title: 'Netherlands', value: 159 },
  { countryCode: 'NZ', title: 'New Zealand', value: 162 },
  { countryCode: 'NI', title: 'Nicaragua', value: 163 },
  { countryCode: 'NE', title: 'Niger', value: 164 },
  { countryCode: 'NG', title: 'Nigeria', value: 165 },
  { countryCode: 'NO', title: 'Norway', value: 169 },
  { countryCode: 'OM', title: 'Oman', value: 170 },
  { countryCode: 'PK', title: 'Pakistan', value: 171 },
  { countryCode: 'PW', title: 'Palau', value: 172 },
  { countryCode: 'PA', title: 'Panama', value: 174 },
  { countryCode: 'PG', title: 'Papua New Guinea', value: 175 },
  { countryCode: 'PY', title: 'Paraguay', value: 176 },
  { countryCode: 'PE', title: 'Peru', value: 177 },
  { countryCode: 'PH', title: 'Philippines', value: 178 },
  { countryCode: 'PL', title: 'Poland', value: 180 },
  { countryCode: 'PT', title: 'Portugal', value: 181 },
  { countryCode: 'QA', title: 'Qatar', value: 183 },
  { countryCode: 'RO', title: 'Romania', value: 185 },
  { countryCode: 'RU', title: 'Russian Federation', value: 186 },
  { countryCode: 'RW', title: 'Rwanda', value: 187 },
  { countryCode: 'KN', title: 'Saint Kitts and Nevis', value: 190 },
  { countryCode: 'LC', title: 'Saint Lucia', value: 191 },
  { countryCode: 'VC', title: 'Saint Vincent and the Grenadines', value: 194 },
  { countryCode: 'WS', title: 'Samoa', value: 195 },
  { countryCode: 'SM', title: 'San Marino', value: 196 },
  { countryCode: 'ST', title: 'Sao Tome and Principe', value: 197 },
  { countryCode: 'SA', title: 'Saudi Arabia', value: 198 },
  { countryCode: 'SN', title: 'Senegal', value: 199 },
  { countryCode: 'RS', title: 'Serbia', value: 200 },
  { countryCode: 'SC', title: 'Seychelles', value: 201 },
  { countryCode: 'SL', title: 'Sierra Leone', value: 202 },
  { countryCode: 'SG', title: 'Singapore', value: 203 },
  { countryCode: 'SK', title: 'Slovakia', value: 205 },
  { countryCode: 'SI', title: 'Slovenia', value: 206 },
  { countryCode: 'SB', title: 'Solomon Islands', value: 207 },
  { countryCode: 'SO', title: 'Somalia', value: 208 },
  { countryCode: 'ZA', title: 'South Africa', value: 209 },
  { countryCode: 'SS', title: 'South Sudan', value: 211 },
  { countryCode: 'ES', title: 'Spain', value: 212 },
  { countryCode: 'LK', title: 'Sri Lanka', value: 213 },
  { countryCode: 'SR', title: 'Suriname', value: 214 },
  { countryCode: 'SE', title: 'Sweden', value: 217 },
  { countryCode: 'CH', title: 'Switzerland', value: 218 },
  { countryCode: 'TW', title: 'Taiwan', value: 219 },
  { countryCode: 'TJ', title: 'Tajikistan', value: 220 },
  { countryCode: 'TZ', title: 'Tanzania, United Republic of', value: 221 },
  { countryCode: 'TH', title: 'Thailand', value: 222 },
  { countryCode: 'TL', title: 'Timor-leste', value: 223 },
  { countryCode: 'TG', title: 'Togo', value: 224 },
  { countryCode: 'TO', title: 'Tonga', value: 226 },
  { countryCode: 'TT', title: 'Trinidad and Tobago', value: 227 },
  { countryCode: 'TN', title: 'Tunisia', value: 228 },
  { countryCode: 'TR', title: 'Turkey', value: 229 },
  { countryCode: 'TM', title: 'Turkmenistan', value: 230 },
  { countryCode: 'TV', title: 'Tuvalu', value: 232 },
  { countryCode: 'UG', title: 'Uganda', value: 233 },
  { countryCode: 'UA', title: 'Ukraine', value: 234 },
  { countryCode: 'AE', title: 'United Arab Emirates', value: 235 },
  { countryCode: 'UY', title: 'Uruguay', value: 237 },
  { countryCode: 'UZ', title: 'Uzbekistan', value: 238 },
  { countryCode: 'VU', title: 'Vanuatu', value: 239 },
  { countryCode: 'VE', title: 'Venezuela', value: 240 },
  { countryCode: 'VN', title: 'Vietnam', value: 241 },
  { countryCode: 'YE', title: 'Yemen', value: 246 },
  { countryCode: 'ZM', title: 'Zambia', value: 247 },
  { countryCode: 'ZW', title: 'Zimbabwe', value: 248 },
  { countryCode: 'IR', title: 'Iran', value: 249 },
  { countryCode: 'SY', title: 'Syria', value: 250 },
];

export const getCountryFromCountryCode = (locationCode: number) => {
  return locations.find((locationObj: TODOFIXANY) => locationObj.value === locationCode);
};

export const firstPriceBidCoreRegionAndCountryOverrideList: TODOFIXANY = {
  countries: {
    162: { countryCode: 'NZ', regionCode: 'ANZ', title: 'New Zealand', value: 162 },
    18: { countryCode: 'AU', regionCode: 'ANZ', title: 'Australia', value: 18 },
    2: { countryCode: 'US', regionCode: 'UAC', title: 'United States', value: 2 },
    3: {
      countryCode: 'GB',
      regionCode: 'WESTERN_EUROPE',
      title: 'United Kingdom',
      value: 3,
    },
    4: { countryCode: 'CA', regionCode: 'UAC', title: 'Canada', value: 4 },
  },
  regions: {
    17: {
      nonEU: true,
      parentRegion: true,
      regionCode: 'ANZ',
      title: 'Australia and New Zealand',
      value: 17,
    },
    19: { nonEU: true, parentRegion: true, regionCode: 'UAC', title: 'US and Canada', value: 19 },
  },
};

export const regionsAndCountriesSortedAlph: RegionsAndLocationsFormInputObj[] = [
  { ...allLocationsObj, superGroup: true },
  { ...allNonEULocationsObj, superGroup: true },
  // US AND CANADA
  { nonEU: true, parentRegion: true, regionCode: 'UAC', title: 'US and Canada', value: 19 },
  { countryCode: 'CA', regionCode: 'UAC', title: 'Canada', value: 4 },
  { countryCode: 'US', regionCode: 'UAC', title: 'United States', value: 2 },
  // AFRICA
  { nonEU: true, parentRegion: true, regionCode: 'AFRICA', title: 'Africa', value: 16 },
  { countryCode: 'DZ', regionCode: 'AFRICA', title: 'Algeria', value: 8 },
  { countryCode: 'AO', regionCode: 'AFRICA', title: 'Angola', value: 11 },
  { countryCode: 'BJ', regionCode: 'AFRICA', title: 'Benin', value: 28 },
  { countryCode: 'BW', regionCode: 'AFRICA', title: 'Botswana', value: 34 },
  { countryCode: 'IO', regionCode: 'AFRICA', title: 'British Indian Ocean Territory', value: 37 },
  { countryCode: 'BF', regionCode: 'AFRICA', title: 'Burkina Faso', value: 40 },
  { countryCode: 'BI', regionCode: 'AFRICA', title: 'Burundi', value: 41 },
  { countryCode: 'CV', regionCode: 'AFRICA', title: 'Cape Verde', value: 44 },
  { countryCode: 'CM', regionCode: 'AFRICA', title: 'Cameroon', value: 43 },
  { countryCode: 'CF', regionCode: 'AFRICA', title: 'Central African Republic', value: 46 },
  { countryCode: 'TD', regionCode: 'AFRICA', title: 'Chad', value: 47 },
  { countryCode: 'KM', regionCode: 'AFRICA', title: 'Comoros', value: 53 },
  { countryCode: 'CG', regionCode: 'AFRICA', title: 'Congo Republic', value: 54 },
  { countryCode: 'CI', regionCode: 'AFRICA', title: "Cote D'ivoire", value: 58 },
  { countryCode: 'CD', regionCode: 'AFRICA', title: 'DR Congo', value: 55 },
  { countryCode: 'DJ', regionCode: 'AFRICA', title: 'Djibouti', value: 65 },
  { countryCode: 'EG', regionCode: 'AFRICA', title: 'Egypt', value: 69 },
  { countryCode: 'GQ', regionCode: 'AFRICA', title: 'Equatorial Guinea', value: 71 },
  { countryCode: 'ER', regionCode: 'AFRICA', title: 'Eritrea', value: 72 },
  { countryCode: 'ET', regionCode: 'AFRICA', title: 'Ethiopia', value: 74 },
  { countryCode: 'GA', regionCode: 'AFRICA', title: 'Gabon', value: 83 },
  { countryCode: 'GM', regionCode: 'AFRICA', title: 'Gambia', value: 84 },
  { countryCode: 'GH', regionCode: 'AFRICA', title: 'Ghana', value: 87 },
  { countryCode: 'GN', regionCode: 'AFRICA', title: 'Guinea', value: 96 },
  { countryCode: 'GW', regionCode: 'AFRICA', title: 'Guinea-Bissau', value: 97 },
  { countryCode: 'KE', regionCode: 'AFRICA', title: 'Kenya', value: 118 },
  { countryCode: 'LS', regionCode: 'AFRICA', title: 'Lesotho', value: 127 },
  { countryCode: 'LR', regionCode: 'AFRICA', title: 'Liberia', value: 128 },
  { countryCode: 'LY', regionCode: 'AFRICA', title: 'Libya', value: 129 },
  { countryCode: 'MG', regionCode: 'AFRICA', title: 'Madagascar', value: 135 },
  { countryCode: 'MW', regionCode: 'AFRICA', title: 'Malawi', value: 136 },
  { countryCode: 'ML', regionCode: 'AFRICA', title: 'Mali', value: 139 },
  { countryCode: 'MR', regionCode: 'AFRICA', title: 'Mauritania', value: 143 },
  { countryCode: 'MU', regionCode: 'AFRICA', title: 'Mauritius', value: 144 },
  { countryCode: 'YT', regionCode: 'AFRICA', title: 'Mayotte', value: 145 },
  { countryCode: 'MA', regionCode: 'AFRICA', title: 'Morocco', value: 153 },
  { countryCode: 'MZ', regionCode: 'AFRICA', title: 'Mozambique', value: 154 },
  { countryCode: 'NA', regionCode: 'AFRICA', title: 'Namibia', value: 156 },
  { countryCode: 'NE', regionCode: 'AFRICA', title: 'Niger', value: 164 },
  { countryCode: 'NG', regionCode: 'AFRICA', title: 'Nigeria', value: 165 },
  { countryCode: 'RW', regionCode: 'AFRICA', title: 'Rwanda', value: 187 },
  { countryCode: 'RE', regionCode: 'AFRICA', title: 'Réunion', value: 184 },
  { countryCode: 'ST', regionCode: 'AFRICA', title: 'São Tomé and Príncipe', value: 197 },
  { countryCode: 'SN', regionCode: 'AFRICA', title: 'Senegal', value: 199 },
  { countryCode: 'SC', regionCode: 'AFRICA', title: 'Seychelles', value: 201 },
  { countryCode: 'SL', regionCode: 'AFRICA', title: 'Sierra Leone', value: 202 },
  { countryCode: 'SO', regionCode: 'AFRICA', title: 'Somalia', value: 208 },
  { countryCode: 'ZA', regionCode: 'AFRICA', title: 'South Africa', value: 209 },
  { countryCode: 'SS', regionCode: 'AFRICA', title: 'South Sudan', value: 211 },
  { countryCode: 'SZ', regionCode: 'AFRICA', title: 'Swaziland', value: 216 },
  { countryCode: 'TZ', regionCode: 'AFRICA', title: 'Tanzania', value: 221 },
  { countryCode: 'TG', regionCode: 'AFRICA', title: 'Togo', value: 224 },
  { countryCode: 'TN', regionCode: 'AFRICA', title: 'Tunisia', value: 228 },
  { countryCode: 'UG', regionCode: 'AFRICA', title: 'Uganda', value: 233 },
  { countryCode: 'EH', regionCode: 'AFRICA', title: 'Western Sahara', value: 245 },
  { countryCode: 'ZM', regionCode: 'AFRICA', title: 'Zambia', value: 247 },
  { countryCode: 'ZW', regionCode: 'AFRICA', title: 'Zimbabwe', value: 248 },
  {
    nonEU: true,
    parentRegion: true,
    regionCode: 'ANZ',
    title: 'Australia and New Zealand',
    value: 17,
  },
  { countryCode: 'AU', regionCode: 'ANZ', title: 'Australia', value: 18 },
  { countryCode: 'NZ', regionCode: 'ANZ', title: 'New Zealand', value: 162 },
  // EASTERN EUROPE
  { parentRegion: true, regionCode: 'EASTERN_EUROPE', title: 'Eastern Europe', value: 11 },
  { countryCode: 'AL', regionCode: 'EASTERN_EUROPE', title: 'Albania', value: 7 },
  { countryCode: 'AM', regionCode: 'EASTERN_EUROPE', title: 'Armenia', value: 16 },
  { countryCode: 'AZ', regionCode: 'EASTERN_EUROPE', title: 'Azerbaijan', value: 20 },
  { countryCode: 'BY', regionCode: 'EASTERN_EUROPE', title: 'Belarus', value: 25 },
  { countryCode: 'BA', regionCode: 'EASTERN_EUROPE', title: 'Bosnia ', value: 33 },
  { countryCode: 'BG', regionCode: 'EASTERN_EUROPE', title: 'Bulgaria', value: 39 },
  { countryCode: 'CZ', regionCode: 'EASTERN_EUROPE', title: 'Czech Republic', value: 63 },
  { countryCode: 'EE', regionCode: 'EASTERN_EUROPE', title: 'Estonia', value: 73 },
  { countryCode: 'GE', regionCode: 'EASTERN_EUROPE', title: 'Georgia', value: 85 },
  { countryCode: 'HU', regionCode: 'EASTERN_EUROPE', title: 'Hungary', value: 104 },
  { countryCode: 'LV', regionCode: 'EASTERN_EUROPE', title: 'Latvia', value: 125 },
  { countryCode: 'ME', regionCode: 'EASTERN_EUROPE', title: 'Montenegro', value: 151 },
  { countryCode: 'PL', regionCode: 'EASTERN_EUROPE', title: 'Poland', value: 180 },
  { countryCode: 'LT', regionCode: 'EASTERN_EUROPE', title: 'Republic of Lithuania', value: 30 },
  { countryCode: 'MD', regionCode: 'EASTERN_EUROPE', title: 'Republic of Moldova', value: 148 },
  { countryCode: 'RO', regionCode: 'EASTERN_EUROPE', title: 'Romania', value: 185 },
  { countryCode: 'RU', regionCode: 'EASTERN_EUROPE', title: 'Russia', value: 186 },
  { countryCode: 'RS', regionCode: 'EASTERN_EUROPE', title: 'Serbia', value: 200 },
  { countryCode: 'SK', regionCode: 'EASTERN_EUROPE', title: 'Slovakia', value: 205 },
  { countryCode: 'SI', regionCode: 'EASTERN_EUROPE', title: 'Slovenia', value: 206 },
  { countryCode: 'TR', regionCode: 'EASTERN_EUROPE', title: 'Turkey', value: 229 },
  { countryCode: 'UA', regionCode: 'EASTERN_EUROPE', title: 'Ukraine', value: 234 },
  // MIDDLE EAST
  { nonEU: true, parentRegion: true, regionCode: 'MIDDLE_EAST', title: 'Middle East', value: 14 },
  { countryCode: 'BH', regionCode: 'MIDDLE_EAST', title: 'Bahrain', value: 22 },
  { countryCode: 'IR', regionCode: 'MIDDLE_EAST', title: 'Iran', value: 249 },
  { countryCode: 'IQ', regionCode: 'MIDDLE_EAST', title: 'Iraq', value: 108 },
  { countryCode: 'IL', regionCode: 'MIDDLE_EAST', title: 'Israel', value: 111 },
  { countryCode: 'KW', regionCode: 'MIDDLE_EAST', title: 'Kuwait', value: 122 },
  { countryCode: 'LB', regionCode: 'MIDDLE_EAST', title: 'Lebanon', value: 126 },
  { countryCode: 'OM', regionCode: 'MIDDLE_EAST', title: 'Oman', value: 170 },
  { countryCode: 'QA', regionCode: 'MIDDLE_EAST', title: 'Qatar', value: 183 },
  { countryCode: 'SA', regionCode: 'MIDDLE_EAST', title: 'Saudi Arabia', value: 198 },
  { countryCode: 'SY', regionCode: 'MIDDLE_EAST', title: 'Syria', value: 250 },
  { countryCode: 'AE', regionCode: 'MIDDLE_EAST', title: 'United Arab Emirates', value: 235 },
  { countryCode: 'YE', regionCode: 'MIDDLE_EAST', title: 'Yemen', value: 246 },
  // EAST ASIA
  { nonEU: true, parentRegion: true, regionCode: 'EAST_ASIA', title: 'East Asia', value: 12 },
  { countryCode: 'HK', regionCode: 'EAST_ASIA', title: 'Hong Kong', value: 103 },
  { countryCode: 'JP', regionCode: 'EAST_ASIA', title: 'Japan', value: 114 },
  { countryCode: 'MN', regionCode: 'EAST_ASIA', title: 'Mongolia', value: 150 },
  { countryCode: 'KP', regionCode: 'EAST_ASIA', title: 'North Korea', value: 251 },
  { countryCode: 'KR', regionCode: 'EAST_ASIA', title: 'South Korea', value: 120 },
  { countryCode: 'TW', regionCode: 'EAST_ASIA', title: 'Taiwan', value: 219 },
  // LATIN AMERICA
  {
    nonEU: true,
    parentRegion: true,
    regionCode: 'LATIN_AMERICA',
    title: 'Latin America',
    value: 15,
  },
  { countryCode: 'AI', regionCode: 'LATIN_AMERICA', title: 'Anguilla', value: 12 },
  { countryCode: 'AG', regionCode: 'LATIN_AMERICA', title: 'Antigua and Barbuda', value: 14 },
  { countryCode: 'AR', regionCode: 'LATIN_AMERICA', title: 'Argentina', value: 15 },
  { countryCode: 'AW', regionCode: 'LATIN_AMERICA', title: 'Aruba', value: 17 },
  { countryCode: 'BS', regionCode: 'LATIN_AMERICA', title: 'Bahamas', value: 21 },
  { countryCode: 'BB', regionCode: 'LATIN_AMERICA', title: 'Barbados', value: 24 },
  { countryCode: 'BZ', regionCode: 'LATIN_AMERICA', title: 'Belize', value: 27 },
  { countryCode: 'BM', regionCode: 'LATIN_AMERICA', title: 'Bermuda', value: 29 },
  { countryCode: 'BO', regionCode: 'LATIN_AMERICA', title: 'Bolivia', value: 31 },
  {
    countryCode: 'BQ',
    regionCode: 'LATIN_AMERICA',
    title: 'Bonaire, Saint Eustatius, and Saba',
    value: 32,
  },
  { countryCode: 'BV', regionCode: 'LATIN_AMERICA', title: 'Bouvet Island', value: 35 },
  { countryCode: 'BR', regionCode: 'LATIN_AMERICA', title: 'Brazil', value: 36 },
  { countryCode: 'VG', regionCode: 'LATIN_AMERICA', title: 'British Virgin Islands', value: 242 },
  { countryCode: 'KY', regionCode: 'LATIN_AMERICA', title: 'Cayman Islands', value: 45 },
  { countryCode: 'CL', regionCode: 'LATIN_AMERICA', title: 'Chile', value: 48 },
  { countryCode: 'CO', regionCode: 'LATIN_AMERICA', title: 'Colombia', value: 52 },
  { countryCode: 'CK', regionCode: 'LATIN_AMERICA', title: 'Cook Islands', value: 56 },
  { countryCode: 'CR', regionCode: 'LATIN_AMERICA', title: 'Costa Rica', value: 57 },
  { countryCode: 'CU', regionCode: 'LATIN_AMERICA', title: 'Cuba', value: 60 },
  { countryCode: 'CW', regionCode: 'LATIN_AMERICA', title: 'Curaçao', value: 61 },
  { countryCode: 'DM', regionCode: 'LATIN_AMERICA', title: 'Dominica', value: 66 },
  { countryCode: 'DO', regionCode: 'LATIN_AMERICA', title: 'Dominican Republic', value: 67 },
  { countryCode: 'EC', regionCode: 'LATIN_AMERICA', title: 'Ecuador', value: 68 },
  { countryCode: 'SV', regionCode: 'LATIN_AMERICA', title: 'El Salvador', value: 70 },
  { countryCode: 'FK', regionCode: 'LATIN_AMERICA', title: 'Falkland Islands', value: 75 },
  { countryCode: 'GF', regionCode: 'LATIN_AMERICA', title: 'French Guiana', value: 80 },
  { countryCode: 'GD', regionCode: 'LATIN_AMERICA', title: 'Grenada', value: 91 },
  { countryCode: 'GP', regionCode: 'LATIN_AMERICA', title: 'Guadeloupe', value: 92 },
  { countryCode: 'GT', regionCode: 'LATIN_AMERICA', title: 'Guatemala', value: 94 },
  { countryCode: 'GY', regionCode: 'LATIN_AMERICA', title: 'Guyana', value: 98 },
  { countryCode: 'HT', regionCode: 'LATIN_AMERICA', title: 'Haiti', value: 99 },
  { countryCode: 'HN', regionCode: 'LATIN_AMERICA', title: 'Honduras', value: 102 },
  { countryCode: 'JM', regionCode: 'LATIN_AMERICA', title: 'Jamaica', value: 113 },
  { countryCode: 'MQ', regionCode: 'LATIN_AMERICA', title: 'Martinique', value: 142 },
  { countryCode: 'MX', regionCode: 'LATIN_AMERICA', title: 'Mexico', value: 146 },
  { countryCode: 'MS', regionCode: 'LATIN_AMERICA', title: 'Montserrat', value: 152 },
  { countryCode: 'NI', regionCode: 'LATIN_AMERICA', title: 'Nicaragua', value: 163 },
  { countryCode: 'PA', regionCode: 'LATIN_AMERICA', title: 'Panama', value: 174 },
  { countryCode: 'PY', regionCode: 'LATIN_AMERICA', title: 'Paraguay', value: 176 },
  { countryCode: 'PE', regionCode: 'LATIN_AMERICA', title: 'Peru', value: 177 },
  { countryCode: 'PR', regionCode: 'LATIN_AMERICA', title: 'Puerto Rico', value: 182 },
  { countryCode: 'BL', regionCode: 'LATIN_AMERICA', title: 'Saint Barthélemy', value: 188 },
  { countryCode: 'SH', regionCode: 'LATIN_AMERICA', title: 'Saint Helena', value: 189 },
  { countryCode: 'LC', regionCode: 'LATIN_AMERICA', title: 'Saint Lucia', value: 191 },
  { countryCode: 'MF', regionCode: 'LATIN_AMERICA', title: 'Saint Martin', value: 192 },
  {
    countryCode: 'PM',
    regionCode: 'LATIN_AMERICA',
    title: 'Saint Pierre and Miquelon',
    value: 193,
  },
  {
    countryCode: 'VC',
    regionCode: 'LATIN_AMERICA',
    title: 'Saint Vincent and the Grenadines',
    value: 194,
  },
  { countryCode: 'SX', regionCode: 'LATIN_AMERICA', title: 'Sint Maarten', value: 204 },
  {
    countryCode: 'GS',
    regionCode: 'LATIN_AMERICA',
    title: 'South Georgia and the South Sandwich Islands',
    value: 210,
  },
  { countryCode: 'KN', regionCode: 'LATIN_AMERICA', title: 'St Kitts and Nevis', value: 190 },
  { countryCode: 'SR', regionCode: 'LATIN_AMERICA', title: 'Suriname', value: 214 },
  { countryCode: 'TT', regionCode: 'LATIN_AMERICA', title: 'Trinidad and Tobago', value: 227 },
  { countryCode: 'TC', regionCode: 'LATIN_AMERICA', title: 'Turks and Caicos Islands', value: 231 },
  { countryCode: 'VI', regionCode: 'LATIN_AMERICA', title: 'U.S. Virgin Islands', value: 243 },
  { countryCode: 'UY', regionCode: 'LATIN_AMERICA', title: 'Uruguay', value: 237 },
  { countryCode: 'VE', regionCode: 'LATIN_AMERICA', title: 'Venezuela', value: 240 },
  // REST OF THE WORLD
  { nonEU: true, parentRegion: true, regionCode: 'ROW', title: 'Rest of the World', value: 18 },
  { countryCode: 'AF', regionCode: 'ROW', title: 'Afghanistan', value: 5 },
  { countryCode: 'AS', regionCode: 'ROW', title: 'American Samoa', value: 9 },
  { countryCode: 'BD', regionCode: 'ROW', title: 'Bangladesh', value: 23 },
  { countryCode: 'BT', regionCode: 'ROW', title: 'Bhutan', value: 30 },
  { countryCode: 'CC', regionCode: 'ROW', title: 'Cocos [Keeling] Islands', value: 51 },
  { countryCode: 'PF', regionCode: 'ROW', title: 'French Polynesia', value: 81 },
  { countryCode: 'GU', regionCode: 'ROW', title: 'Guam', value: 93 },
  { countryCode: 'IN', regionCode: 'ROW', title: 'India', value: 106 },
  { countryCode: 'KZ', regionCode: 'ROW', title: 'Kazakhstan', value: 117 },
  { countryCode: 'KI', regionCode: 'ROW', title: 'Kiribati', value: 119 },
  { countryCode: 'KG', regionCode: 'ROW', title: 'Kyrgyzstan', value: 123 },
  { countryCode: 'MH', regionCode: 'ROW', title: 'Marshall Islands', value: 141 },
  { countryCode: 'NR', regionCode: 'ROW', title: 'Nauru', value: 157 },
  { countryCode: 'NP', regionCode: 'ROW', title: 'Nepal', value: 158 },
  { countryCode: 'NC', regionCode: 'ROW', title: 'New Caledonia', value: 161 },
  { countryCode: 'NU', regionCode: 'ROW', title: 'Niue', value: 166 },
  { countryCode: 'NF', regionCode: 'ROW', title: 'Norfolk Island', value: 167 },
  { countryCode: 'MP', regionCode: 'ROW', title: 'Northern Mariana Islands', value: 168 },
  { countryCode: 'PK', regionCode: 'ROW', title: 'Pakistan', value: 171 },
  { countryCode: 'PW', regionCode: 'ROW', title: 'Palau', value: 172 },
  { countryCode: 'PG', regionCode: 'ROW', title: 'Papua New Guinea', value: 175 },
  { countryCode: 'PN', regionCode: 'ROW', title: 'Pitcairn', value: 179 },
  { countryCode: 'WS', regionCode: 'ROW', title: 'Samoa', value: 195 },
  { countryCode: 'SB', regionCode: 'ROW', title: 'Solomon Islands', value: 207 },
  { countryCode: 'LK', regionCode: 'ROW', title: 'Sri Lanka', value: 213 },
  { countryCode: 'TJ', regionCode: 'ROW', title: 'Tajikistan', value: 220 },
  { countryCode: 'TK', regionCode: 'ROW', title: 'Tokelau', value: 225 },
  { countryCode: 'TO', regionCode: 'ROW', title: 'Tonga', value: 226 },
  { countryCode: 'TM', regionCode: 'ROW', title: 'Turkmenistan', value: 230 },
  { countryCode: 'TV', regionCode: 'ROW', title: 'Tuvalu', value: 232 },
  { countryCode: 'UM', regionCode: 'ROW', title: 'U.S. Minor Outlying Islands', value: 236 },
  { countryCode: 'UZ', regionCode: 'ROW', title: 'Uzbekistan', value: 238 },
  { countryCode: 'VU', regionCode: 'ROW', title: 'Vanuatu', value: 239 },
  { countryCode: 'WF', regionCode: 'ROW', title: 'Wallis and Futuna', value: 244 },
  // SOUTHEAST ASIA
  {
    nonEU: true,
    parentRegion: true,
    regionCode: 'SOUTHEAST_ASIA',
    title: 'Southeast Asia',
    value: 13,
  },
  { countryCode: 'KH', regionCode: 'SOUTHEAST_ASIA', title: 'Cambodia', value: 42 },
  { countryCode: 'CX', regionCode: 'SOUTHEAST_ASIA', title: 'Christmas Island', value: 50 },
  { countryCode: 'TL', regionCode: 'SOUTHEAST_ASIA', title: 'Timor-leste', value: 223 },
  {
    countryCode: 'FM',
    regionCode: 'SOUTHEAST_ASIA',
    title: 'Federated States of Micronesia',
    value: 147,
  },
  { countryCode: 'FJ', regionCode: 'SOUTHEAST_ASIA', title: 'Fiji', value: 77 },
  { countryCode: 'ID', regionCode: 'SOUTHEAST_ASIA', title: 'Indonesia', value: 107 },
  {
    countryCode: 'LA',
    regionCode: 'SOUTHEAST_ASIA',
    title: "Lao People's Democratic Republic",
    value: 124,
  },
  { countryCode: 'MO', regionCode: 'SOUTHEAST_ASIA', title: 'Macao', value: 133 },
  { countryCode: 'MY', regionCode: 'SOUTHEAST_ASIA', title: 'Malaysia', value: 137 },
  { countryCode: 'MV', regionCode: 'SOUTHEAST_ASIA', title: 'Maldives', value: 138 },
  { countryCode: 'MM', regionCode: 'SOUTHEAST_ASIA', title: 'Myanmar', value: 155 },
  { countryCode: 'PH', regionCode: 'SOUTHEAST_ASIA', title: 'Philippines', value: 178 },
  { countryCode: 'SG', regionCode: 'SOUTHEAST_ASIA', title: 'Singapore', value: 203 },
  { countryCode: 'TH', regionCode: 'SOUTHEAST_ASIA', title: 'Thailand', value: 222 },
  { countryCode: 'VN', regionCode: 'SOUTHEAST_ASIA', title: 'Vietnam', value: 241 },
  // WESTERN EUROPE
  { parentRegion: true, regionCode: 'WESTERN_EUROPE', title: 'Western Europe', value: 10 },
  { countryCode: 'AX', regionCode: 'WESTERN_EUROPE', title: 'Åland Islands', value: 6 },
  { countryCode: 'AD', regionCode: 'WESTERN_EUROPE', title: 'Andorra', value: 10 },
  { countryCode: 'AT', regionCode: 'WESTERN_EUROPE', title: 'Austria', value: 19 },
  { countryCode: 'BE', regionCode: 'WESTERN_EUROPE', title: 'Belgium', value: 26 },
  { countryCode: 'HR', regionCode: 'WESTERN_EUROPE', title: 'Croatia', value: 59 },
  { countryCode: 'CY', regionCode: 'WESTERN_EUROPE', title: 'Cyprus', value: 62 },
  { countryCode: 'DK', regionCode: 'WESTERN_EUROPE', title: 'Denmark', value: 64 },
  { countryCode: 'FO', regionCode: 'WESTERN_EUROPE', title: 'Faroe Islands', value: 76 },
  { countryCode: 'FI', regionCode: 'WESTERN_EUROPE', title: 'Finland', value: 78 },
  { countryCode: 'FR', regionCode: 'WESTERN_EUROPE', title: 'France', value: 79 },
  { countryCode: 'DE', regionCode: 'WESTERN_EUROPE', title: 'Germany', value: 86 },
  { countryCode: 'GI', regionCode: 'WESTERN_EUROPE', title: 'Gibraltar', value: 88 },
  { countryCode: 'GR', regionCode: 'WESTERN_EUROPE', title: 'Greece', value: 89 },
  { countryCode: 'GL', regionCode: 'WESTERN_EUROPE', title: 'Greenland', value: 90 },
  { countryCode: 'GG', regionCode: 'WESTERN_EUROPE', title: 'Guernsey', value: 95 },
  { countryCode: 'IS', regionCode: 'WESTERN_EUROPE', title: 'Iceland', value: 105 },
  { countryCode: 'IE', regionCode: 'WESTERN_EUROPE', title: 'Ireland', value: 109 },
  { countryCode: 'IM', regionCode: 'WESTERN_EUROPE', title: 'Isle of Man', value: 110 },
  { countryCode: 'IT', regionCode: 'WESTERN_EUROPE', title: 'Italy', value: 112 },
  { countryCode: 'JE', regionCode: 'WESTERN_EUROPE', title: 'Jersey', value: 115 },
  { countryCode: 'LI', regionCode: 'WESTERN_EUROPE', title: 'Liechtenstein', value: 130 },
  { countryCode: 'LU', regionCode: 'WESTERN_EUROPE', title: 'Luxembourg', value: 132 },
  { countryCode: 'MT', regionCode: 'WESTERN_EUROPE', title: 'Malta', value: 140 },
  { countryCode: 'MC', regionCode: 'WESTERN_EUROPE', title: 'Monaco', value: 149 },
  { countryCode: 'NL', regionCode: 'WESTERN_EUROPE', title: 'Netherlands', value: 159 },
  { countryCode: 'NO', regionCode: 'WESTERN_EUROPE', title: 'Norway', value: 169 },
  { countryCode: 'PT', regionCode: 'WESTERN_EUROPE', title: 'Portugal', value: 181 },
  { countryCode: 'SM', regionCode: 'WESTERN_EUROPE', title: 'San Marino', value: 196 },
  { countryCode: 'ES', regionCode: 'WESTERN_EUROPE', title: 'Spain', value: 212 },
  { countryCode: 'SJ', regionCode: 'WESTERN_EUROPE', title: 'Svalbard and Jan Mayen', value: 215 },
  { countryCode: 'SE', regionCode: 'WESTERN_EUROPE', title: 'Sweden', value: 217 },
  { countryCode: 'CH', regionCode: 'WESTERN_EUROPE', title: 'Switzerland', value: 218 },
  {
    countryCode: 'GB',
    regionCode: 'WESTERN_EUROPE',
    title: 'United Kingdom',
    value: 3,
  },
  { countryCode: 'VA', regionCode: 'WESTERN_EUROPE', title: 'Vatican City', value: 101 },
];

export const getMixedRegionCountryObjFromCountryCode = (countryCode: string) => {
  return regionsAndCountriesSortedAlph.find(
    (locationObj: TODOFIXANY) => locationObj.countryCode === countryCode,
  );
};

export const getRegionFromLocationCode = (locationCode: number) => {
  return regionsAndCountriesSortedAlph.find(
    (locationObj: TODOFIXANY) =>
      locationObj.value === locationCode && (locationObj.parentRegion || locationObj.isAll),
  );
};

export const getCountryFromLocationCode = (locationCode: number) => {
  return regionsAndCountriesSortedAlph.find(
    (locationObj: TODOFIXANY) => locationObj.value === locationCode && !locationObj.parentRegion,
  );
};

// Mapped to:
// https://github.rbx.com/Roblox/ads/blob/master/protos/roblox/ads/shared/targeting/v2/targeting_criteria.proto#L1065
// except allNonEULocationsObj is an extra UI only requirement for EU DSA
// displaying order is based on larger regions
// https://roblox.slack.com/archives/C04RQDU6170/p1694451864139939
export const regions: RegionsFormInputObj[] = [
  allLocationsObj,
  allNonEULocationsObj,
  { regionCode: 'US', title: 'United States', value: 2 },
  { regionCode: 'CA', title: 'Canada', value: 3 },
  { regionCode: 'GB', title: 'United Kingdom', value: 4 },
  { regionCode: 'DE', title: 'Germany', value: 5 },
  { regionCode: 'FR', title: 'France', value: 6 },
  { regionCode: 'WESTERN_EUROPE', title: 'Rest of Western Europe', value: 10 },
  { regionCode: 'EASTERN_EUROPE', title: 'Eastern Europe', value: 11 },
  { regionCode: 'KR', title: 'South Korea', value: 7 },
  { regionCode: 'JP', title: 'Japan', value: 8 },
  { regionCode: 'EAST_ASIA', title: 'Rest of East Asia', value: 12 },
  { regionCode: 'SOUTHEAST_ASIA', title: 'Southeast Asia', value: 13 },
  { regionCode: 'MIDDLE_EAST', title: 'Middle East', value: 14 },
  { regionCode: 'BR', title: 'Brazil', value: 9 },
  { regionCode: 'LATIN_AMERICA', title: 'Rest of Latin America', value: 15 },
  { regionCode: 'AFRICA', title: 'Africa', value: 16 },
  { regionCode: 'ANZ', title: 'Australia and New Zealand', value: 17 },
  { regionCode: 'ROW', title: 'Rest of the World', value: 18 },
];

export const getRegionFromRegionCode = (locationCode: number) => {
  return regions.find((locationObj: TODOFIXANY) => locationObj.value === locationCode);
};

const allLanguagesObj = { langCode: 'ALL', title: 'All Languages', value: 1 };

// Mapped to: https://github.rbx.com/Roblox/ads/blob/26dd1ce78fabd5c9272dde4de4cd84622e2cb653/protos/roblox/ads/shared/targeting/v1/targeting_criteria.proto#L870
export const languages: LanguageFormInputObj[] = [
  allLanguagesObj,
  { langCode: 'EN', title: 'English', value: 2 },
  { langCode: 'ES', title: 'Spanish', value: 3 },
  { langCode: 'FR', title: 'French', value: 4 },
  { langCode: 'ID', title: 'Indonesian', value: 5 },
  { langCode: 'IT', title: 'Italian', value: 6 },
  { langCode: 'JA', title: 'Japanese', value: 7 },
  { langCode: 'KO', title: 'Korean', value: 8 },
  { langCode: 'RU', title: 'Russian', value: 9 },
  { langCode: 'TH', title: 'Thai', value: 10 },
  { langCode: 'TR', title: 'Turkish', value: 11 },
  { langCode: 'VI', title: 'Vietnamese', value: 12 },
  { langCode: 'PT', title: 'Portuguese', value: 13 },
  { langCode: 'DE', title: 'German', value: 14 },
  { langCode: 'ZH_HANS', title: 'Chinese (Simplified)', value: 15 },
  { langCode: 'ZH_HANT', title: 'Chinese (Traditional)', value: 16 },
  { langCode: 'BG', title: 'Bulgarian', value: 17 },
  { langCode: 'BN', title: 'Bengali', value: 18 },
  { langCode: 'CS', title: 'Czech', value: 19 },
  { langCode: 'DA', title: 'Danish', value: 20 },
  { langCode: 'EL', title: 'Greek', value: 21 },
  { langCode: 'ET', title: 'Estonian', value: 22 },
  { langCode: 'FI', title: 'Finnish', value: 23 },
  { langCode: 'HI', title: 'Hindi', value: 24 },
  { langCode: 'HR', title: 'Croatian', value: 25 },
  { langCode: 'HU', title: 'Hungarian', value: 26 },
  { langCode: 'KA', title: 'Georgian', value: 27 },
  { langCode: 'KK', title: 'Kazakh', value: 28 },
  { langCode: 'KM', title: 'Khmer', value: 29 },
  { langCode: 'LT', title: 'Lithuanian', value: 30 },
  { langCode: 'LV', title: 'Latvian', value: 31 },
  { langCode: 'MS', title: 'Malay', value: 32 },
  { langCode: 'MY', title: 'Burmese', value: 33 },
  { langCode: 'NB', title: 'Bokmal', value: 34 },
  { langCode: 'NL', title: 'Dutch', value: 35 },
  { langCode: 'FIL', title: 'Filipino', value: 36 },
  { langCode: 'PL', title: 'Polish', value: 37 },
  { langCode: 'RO', title: 'Romanian', value: 38 },
  { langCode: 'UK', title: 'Ukrainian', value: 39 },
  { langCode: 'SI', title: 'Sinhala', value: 40 },
  { langCode: 'SK', title: 'Slovak', value: 41 },
  { langCode: 'SL', title: 'Slovenian', value: 42 },
  { langCode: 'SQ', title: 'Albanian', value: 43 },
  { langCode: 'BS', title: 'Bosnian', value: 44 },
  { langCode: 'SR', title: 'Serbian', value: 45 },
  { langCode: 'SV', title: 'Swedish', value: 46 },
  { langCode: 'AR', title: 'Arabic', value: 47 },
];

export const getLanguageFromLanguageCode = (languageCode: number) => {
  return languages.find((languageObj: TODOFIXANY) => languageObj.value === languageCode);
};

export const allMinAges = [
  { title: '13', value: 13 },
  { title: '14', value: 14 },
  { title: '15', value: 15 },
  { title: '16', value: 16 },
  { title: '17', value: 17 },
  { title: '18', value: 18 },
  { title: '19', value: 19 },
  { title: '20', value: 20 },
  { title: '21', value: 21 },
  { title: '22', value: 22 },
  { title: '23', value: 23 },
  { title: '24', value: 24 },
  { title: '25', value: 25 },
  { title: '26', value: 26 },
  { title: '27', value: 27 },
  { title: '28', value: 28 },
  { title: '29', value: 29 },
  { title: '30', value: 30 },
  { title: '31', value: 31 },
  { title: '32', value: 32 },
  { title: '33', value: 33 },
  { title: '34', value: 34 },
  { title: '35', value: 35 },
  { title: '36', value: 36 },
  { title: '37', value: 37 },
  { title: '38', value: 38 },
  { title: '39', value: 39 },
  { title: '40', value: 40 },
  { title: '41', value: 41 },
  { title: '42', value: 42 },
  { title: '43', value: 43 },
  { title: '44', value: 44 },
  { title: '45', value: 45 },
  { title: '46', value: 46 },
  { title: '47', value: 47 },
  { title: '48', value: 48 },
  { title: '49', value: 49 },
  { title: '50', value: 50 },
  { title: '51', value: 51 },
  { title: '52', value: 52 },
  { title: '53', value: 53 },
  { title: '54', value: 54 },
  { title: '55', value: 55 },
  { title: '56', value: 56 },
  { title: '57', value: 57 },
  { title: '58', value: 58 },
  { title: '59', value: 59 },
  { title: '60', value: 60 },
  { title: '61', value: 61 },
  { title: '62', value: 62 },
  { title: '63', value: 63 },
  { title: '64', value: 64 },
];

export const allMaxAges = [...allMinAges, { title: '65+', value: 65 }];

export const devices: FormInputObj[] = [
  { label: 'All', value: DeviceType.DEVICE_TYPE_ALL },
  { label: 'Mobile', value: DeviceType.DEVICE_TYPE_PHONE },
  { label: 'Tablet', value: DeviceType.DEVICE_TYPE_TABLET },
  { label: 'Desktop', value: DeviceType.DEVICE_TYPE_COMPUTER },
  { label: 'Console', value: DeviceType.DEVICE_TYPE_CONSOLE },
];

export const u13AgeBucket: FormInputObj = {
  label: '5-12',
  value: AgeBucketType.AGE_BUCKET_TYPE_5_TO_12,
};

export const ageBuckets: FormInputObj[] = [
  { label: '13-17', value: AgeBucketType.AGE_BUCKET_TYPE_13_TO_17 },
  { label: '18-24', value: AgeBucketType.AGE_BUCKET_TYPE_18_TO_24 },
  { label: '25+', value: AgeBucketType.AGE_BUCKET_TYPE_25_PLUS },
];

/** Returns true when the 5-12 age bucket checkbox is applicable for the given ad format and feature flag. */
export const isU13TargetingApplicableForFormat = (
  adType: AdFormatType | string | undefined,
  isAge5To12TargetingEnabled: boolean,
): boolean =>
  isAge5To12TargetingEnabled &&
  (adType === AdFormatType.DISPLAY ||
    adType === AdFormatType.VIDEO ||
    adType === AdFormatType.PORTAL);

/** Returns the total number of age-bucket options shown in the UI for the given context. */
export const getApplicableAgeBucketCount = (isU13Applicable: boolean): number =>
  isU13Applicable ? ageBuckets.length + 1 : ageBuckets.length;

export const genders: FormInputObj[] = [
  { label: 'All', value: Gender.GENDER_ANY },
  { label: 'Female', value: Gender.GENDER_FEMALE },
  { label: 'Male', value: Gender.GENDER_MALE },
];

export const AllGenresObj: GenreFormInputObj = {
  deprecated: false,
  description: '',
  title: 'Label.AllGenres',
  value: 1,
};

export const getGenreStringFromProtoVal = (protoVal: number) => {
  return [...Genres, ...NewGenres].find(
    (genreObj: GenreFormInputObj) => genreObj.value === protoVal,
  );
};
