import { makeStyles } from '@rbx/ui';

const useChangelogTabStyles = makeStyles()((theme) => ({
  container: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minWidth: 0,
  },
  filtersSection: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto',
    alignItems: 'center',
    columnGap: 16,
    alignSelf: 'stretch',
    width: '100%',
    marginTop: 0,
    marginBottom: 20,
    [theme.breakpoints.down('Medium')]: {
      position: 'sticky',
      top: 48,
      zIndex: 9,
      background: theme.palette.surface[0],
      marginBottom: 8,
      boxShadow: `0 -8px 0 0 ${theme.palette.surface[0]}, 0 8px 0 0 ${theme.palette.surface[0]}`,
    },
  },
  filterDropdownWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flex: '1 1 auto',
    minWidth: 0,
  },
  filterDropdownButton: {
    display: 'inline-flex',
    padding: 0,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
  },
  filterDropdownMenu: {
    display: 'flex',
    minWidth: 118,
    width: 'max-content',
    padding: 4,
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 2,
    position: 'absolute',
    left: 0,
    top: 28,
    borderRadius: 8,
    border: `1px solid ${theme.palette.surface.outline}`,
    background: theme.palette.surface[200],
    boxShadow:
      '0 2px 4px -0.5px rgba(4, 4, 8, 0.25), 0 10px 20px -0.75px rgba(4, 4, 8, 0.25), 0 16px 32px -1px rgba(4, 4, 8, 0.25), 0 48px 56px -1.5px rgba(4, 4, 8, 0.25)',
    zIndex: 1,
  },
  filterDropdownMenuItem: {
    display: 'flex',
    padding: '4px 12px',
    alignItems: 'center',
    justifyContent: 'space-between',
    whiteSpace: 'nowrap',
    gap: 12,
    alignSelf: 'stretch',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: theme.palette.content.standard,
    fontSize: '12px',
    lineHeight: '140%',
    '&:hover': {
      backgroundColor: theme.palette.states.hover,
    },
  },
  filterDropdownMenuIcon: {
    color: theme.palette.content.standard,
  },
  searchContainer: {
    display: 'flex',
    width: 311,
    minWidth: 311,
    maxWidth: 311,
    height: '32px',
    minHeight: '32px',
    maxHeight: '32px',
    padding: '0 var(--Padding-Medium, 12px)',
    alignItems: 'center',
    gap: 'var(--Gap-Small, 8px)',
    alignSelf: 'stretch',
    borderRadius: 16,
    border: `1px solid ${theme.palette.surface.outline}`,
    background: theme.palette.surface[100],
    marginLeft: 'auto',
    flexShrink: 0,
    [theme.breakpoints.down('Medium')]: {
      display: 'none',
    },
  },
  searchIcon: {
    width: 16,
    height: 16,
  },
  searchButton: {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 0,
    border: 'none',
    background: 'transparent',
    cursor: 'pointer',
    color: 'inherit',
    '&:disabled': {
      cursor: 'default',
      opacity: 0.6,
    },
  },
  searchInput: {
    flex: 1,
    width: '100%',
    alignSelf: 'stretch',
    border: 'none',
    background: 'transparent',
    outline: 'none',
    color: theme.palette.content.standard,
    fontSize: 14,
    fontFamily: '"Builder Sans"',
    '&::placeholder': {
      color: theme.palette.content.muted,
    },
  },
  changelogTitle: {
    color: theme.palette.content.standard,
    fontSize: 28,
    fontWeight: 700,
    lineHeight: '120%',
    letterSpacing: '-0.28px',
    alignSelf: 'stretch',
  },
  timeline: {
    display: 'flex',
    flexDirection: 'column',
  },
  dateCell: {
    display: 'flex',
    padding: '20px 0 0',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 12,
    flex: '0 0 156px',
    width: 156,
    [theme.breakpoints.down('Medium')]: {
      display: 'none',
    },
  },
  mobileDateRow: {
    display: 'none',
    alignItems: 'flex-start',
    gap: 12,
    padding: 0,
    alignSelf: 'stretch',
    [theme.breakpoints.down('Medium')]: {
      display: 'flex',
      width: '100%',
      maxWidth: theme.breakpoints.values.Medium,
      position: 'sticky',
      top: 88,
      zIndex: 8,
      background: theme.palette.surface[0],
      paddingTop: 12,
      paddingBottom: 8,
    },
  },
  mobileDateInColumn: {
    display: 'none',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    margin: 0,
    alignSelf: 'stretch',
    color: theme.palette.content.standard,
    fontWeight: 700,
    [theme.breakpoints.down('Medium')]: {
      display: 'block',
    },
  },
  mobileDateContentWrapper: {
    flex: 1,
    minWidth: 0,
    width: '100%',
    boxSizing: 'border-box',
    paddingLeft: 0,
    [theme.breakpoints.down('Medium')]: {
      paddingLeft: 0,
    },
  },
  mobilePinnedDate: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },

  dateSpacer: {
    visibility: 'hidden',
    height: 0,
  },
  pinnedDate: {
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  dateText: {
    color: theme.palette.content.standard,
    fontWeight: 700,
  },
  pinnedLabelText: {
    color: theme.palette.content.muted,
    fontSize: 12,
    fontWeight: 600,
  },
  timelineIndicator: {
    display: 'flex',
    paddingTop: 20,
    flexDirection: 'column',
    alignItems: 'center',
    gap: 0,
    flex: '0 0 24px',
    width: 24,
    minWidth: 24,
    maxWidth: 24,
    alignSelf: 'stretch',
    [theme.breakpoints.down('Medium')]: {
      display: 'none',
    },
  },
  timelineLineTop: {
    display: 'none',
  },
  timelineDot: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    color: theme.palette.content.muted,
    flexShrink: 0,
    width: 16,
    height: 16,
  },
  pinnedTimelineIcon: {
    display: 'flex',
    flexShrink: 0,
    width: 16,
    height: 16,
  },
  timelineLineBottom: {
    display: 'flex',
    flex: '1 0 0',
    alignSelf: 'stretch',
    marginBottom: -20,
    position: 'relative',
    '&::before': {
      content: '""',
      width: 0,
      position: 'absolute',
      left: '50%',
      transform: 'translateX(-50%)',
      top: 0,
      bottom: 0,
      height: '100%',
      borderLeft:
        theme.palette.mode === 'dark'
          ? '1.5px solid rgba(208, 217, 251, 0.16)'
          : '1.5px solid rgba(32, 34, 39, 0.16)',
    },
  },
  postsColumn: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    gap: 0,
    flex: 1,
    minWidth: 0,
    width: '100%',
    height: '100%',
  },
  postRow: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    padding: 0,
    alignSelf: 'stretch',
    [theme.breakpoints.down('Medium')]: {
      width: '100%',
      maxWidth: theme.breakpoints.values.Medium,
    },
  },
  postContentWrapper: {
    flex: 1,
    minWidth: 0,
    paddingLeft: 60,
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    alignSelf: 'stretch',
    gap: 0,
    width: '100%',
    [theme.breakpoints.down('Medium')]: {
      paddingLeft: 0,
      '& > *': {
        paddingLeft: 0,
        marginLeft: 0,
      },
    },
  },
}));

export default useChangelogTabStyles;
