import type { FunctionComponent } from 'react';
import React, { useEffect, useRef, useState } from 'react';
import { Badge, Button as FoundationButton } from '@rbx/foundation-ui';
import { useTranslation, withTranslation } from '@rbx/intl';
import { Button, Grid, Typography, NoSSR, Link } from '@rbx/ui';
import { useAuthentication } from '@modules/authentication/providers';
import { IXPLayers } from '@modules/clients/ixpExperiments';
import { downloadStudioDirectDownloadEventModel } from '@modules/eventStream/constants/eventConstants';
import { useEventTrackerProvider } from '@modules/eventStream/eventTrackerProvider';
import unifiedLoggerClient from '@modules/eventStream/unifiedLoggerClient';
import {
  HOMEPAGE_ONBOARDING_RESET_SETTING_VALUE,
  HOMEPAGE_ONBOARDING_BANNER_SETTING_TYPE,
} from '@modules/home/constants/onboardingStepsConstants';
import {
  createYourPlace,
  UniverseDescriptionTranslationKey,
} from '@modules/home/utils/createYourPlaceUtils';
import { useQueryParams, useStudio, EStudioTaskType } from '@modules/miscellaneous/hooks';
import useIXPParameters from '@modules/miscellaneous/hooks/useIXPParameters';
import { TranslationNamespace } from '@modules/miscellaneous/localization';
import { creatorHub, studio } from '@modules/miscellaneous/urls';
import { useCreateOrUpdateGenericCreatorSettings } from '@modules/react-query/creatorSettings';
import useUploadAssetForPlaceMutation from '../../../miscellaneous/hooks/useUploadAssetForPlaceMutation';
import useUploadAutoGeneratedIconMutation from '../../../miscellaneous/hooks/useUploadAutoGeneratedPlaceIconMutation';
import { backDropPath } from '../constants/assetConstants';
import useStarterPlace from '../hooks/useStarterPlace';
import { captureLandingPageEvent } from '../utils/eventUtils';
import IncompatibleCallToAction from './IncompatibleCallToAction';
import useStudioStyles from './StudioV2.styles';

const StudioV2: FunctionComponent = () => {
  const { open, isCompatible: isStudioSupported, dialog } = useStudio();
  const { enableStarterPlace, starterPlaceTemplateId, isFetched } = useStarterPlace();
  const { trackerClient } = useEventTrackerProvider();
  const { translate, translateHTML } = useTranslation();
  const studioDownloadURL = studio.getDownloadUrl();
  const [{ directDownload }] = useQueryParams(['directDownload']);
  const parsedDirectDownload = Boolean(directDownload);
  const { user } = useAuthentication();
  const userId = user?.id;
  const { uploadAssetForPlaceAsync } = useUploadAssetForPlaceMutation();
  const { uploadAutoGeneratedPlaceIconAsync } = useUploadAutoGeneratedIconMutation();
  const { mutateAsync: updateSettings } = useCreateOrUpdateGenericCreatorSettings();
  const [isCreatePlaceLoading, setIsCreatePlaceLoading] = useState(false);
  const {
    params: { enableAudiencesReplacement },
  } = useIXPParameters(IXPLayers.CreatorHubCreationsPermission);

  const shouldShowCreatePlace = !isStudioSupported && isFetched && enableStarterPlace;

  // Log when user is in the starter place experiment but on a desktop device
  // where Studio is supported — they won't see the starter place UI, so the
  // experiment exposure may be tainted for this user.
  // enableStarterPlace is what IXP thinks the user should be seeing
  // isStudioSupported determines what the user actually sees (ie, a starter place button or not)
  const hasLoggedDesktopExposureRef = useRef(false);
  useEffect(() => {
    if (
      isStudioSupported &&
      enableStarterPlace &&
      isFetched &&
      !hasLoggedDesktopExposureRef.current
    ) {
      hasLoggedDesktopExposureRef.current = true;
      unifiedLoggerClient.logImpressionEvent({
        eventName: 'starterPlaceDesktopExperimentExposure',
        parameters: {
          isStudioSupported: String(isStudioSupported),
          enableStarterPlace: String(enableStarterPlace),
        },
      });
    }
  }, [isStudioSupported, enableStarterPlace, isFetched]);

  const {
    classes: {
      root,
      backgroundImage,
      content,
      titleContainer,
      title,
      bodyContainer,
      buttonLarge,
      buttonsContainer,
      link,
    },
  } = useStudioStyles();

  const onClickCreatePlaceButton = () => {
    if (isCreatePlaceLoading || !shouldShowCreatePlace) {
      return;
    }

    setIsCreatePlaceLoading(true);
    captureLandingPageEvent('clickCreatePlaceButton');

    // Reset the onboarding banner on Home if the user clicks the Create Place button
    void updateSettings({
      userId: user?.id,
      setting: HOMEPAGE_ONBOARDING_BANNER_SETTING_TYPE,
      settingValue: HOMEPAGE_ONBOARDING_RESET_SETTING_VALUE,
    });

    void createYourPlace({
      starterPlaceTemplateId,
      userId,
      uploadAssetForPlaceAsync,
      uploadAutoGeneratedPlaceIconAsync,
      placeDescription: translate(UniverseDescriptionTranslationKey, {
        studioSetupLink: creatorHub.docs.getSettingUpStudioUrl(),
      }),
      onFailure: () => {
        // TODO lhoward 2026-01-13: Properly handle failure (user message, etc)
        setIsCreatePlaceLoading(false);
      },
      ...(enableAudiencesReplacement ? { enableAudiencesReplacement: true } : {}),
    });
  };

  return (
    <Grid className={root} container>
      <Grid container justifyContent='center'>
        <img className={backgroundImage} src={backDropPath} alt={translate('Label.Experiences')} />
        <Grid className={content} container direction='column' wrap='nowrap' alignItems='center'>
          <div
            className='dark-theme bg-surface-100 stroke-thin stroke-emphasis radius-medium padding-large flex flex-col medium:flex-row medium:items-center gap-medium'
            style={{ maxWidth: 780, width: '100%', boxSizing: 'border-box' }}>
            <div className='flex flex-col gap-xsmall' style={{ flex: '1 1 0%', minWidth: 0 }}>
              <div className='flex items-center gap-small flex-wrap'>
                <Badge label='New' variant='Contrast' />
                <span className='text-title-medium content-emphasis'>
                  Build on Roblox and reach millions
                </span>
              </div>
              <span className='text-body-medium content-default'>
                Two new programs to help you turn your vision into a launch-ready game.
              </span>
            </div>
            <FoundationButton
              className='shrink-0'
              variant='Standard'
              size='Small'
              onClick={() => {
                window.location.href = '/build';
              }}>
              Learn more
            </FoundationButton>
          </div>
          <Grid className={titleContainer}>
            <Typography className={title} variant='h1' component='h1' align='center'>
              {translate('Heading.MakeAnythingV2')}
            </Typography>
          </Grid>
          <NoSSR>
            <Grid className={bodyContainer} container direction='column' alignItems='center'>
              {shouldShowCreatePlace ? (
                <Typography variant='body2' color='secondary' align='center'>
                  {translateHTML('Description.StarterPlaceAndCreatorHub', [
                    {
                      opening: 'createLinkStart',
                      closing: 'createLinkEnd',
                      content: (chunks: React.ReactNode) => (
                        <Link className={link} href='/'>
                          {chunks}
                        </Link>
                      ),
                    },
                  ])}
                </Typography>
              ) : (
                <>
                  <Typography variant='body2' color='secondary' align='center'>
                    {translate('Description.EverythingYouNeed')}
                  </Typography>
                  <Typography variant='body2' color='secondary' align='center'>
                    {translate('Description.JoinGlobalCommunity')}
                  </Typography>
                </>
              )}
            </Grid>
            <Grid className={buttonsContainer} container direction='column'>
              {isStudioSupported &&
                (parsedDirectDownload ? (
                  <Button
                    component='a'
                    fullWidth
                    className={buttonLarge}
                    color='primary'
                    variant='contained'
                    size='large'
                    href={studioDownloadURL ?? ''}
                    target='_blank'
                    onClick={() => {
                      trackerClient.sendEvent(downloadStudioDirectDownloadEventModel());
                    }}>
                    {translate('Action.DownloadStudio')}
                  </Button>
                ) : (
                  <Button
                    fullWidth
                    className={buttonLarge}
                    color='primary'
                    variant='contained'
                    size='large'
                    onClick={() => {
                      open({
                        task: EStudioTaskType.Default,
                      });
                      captureLandingPageEvent('clickStartCreating');
                    }}>
                    {translate('Action.StartCreating')}
                  </Button>
                ))}
              {!isStudioSupported && (
                <IncompatibleCallToAction shouldShowCreatePlace={shouldShowCreatePlace} />
              )}
              {shouldShowCreatePlace && (
                <Button
                  fullWidth
                  className={buttonLarge}
                  color='primary'
                  variant='outlined'
                  size='large'
                  loading={isCreatePlaceLoading}
                  onClick={onClickCreatePlaceButton}>
                  {translate('Action.StartCreating')}
                </Button>
              )}
            </Grid>
          </NoSSR>
        </Grid>
      </Grid>
      {dialog}
    </Grid>
  );
};

export default withTranslation(StudioV2, [
  TranslationNamespace.Creations,
  TranslationNamespace.Landing,
]);
