import { ReturnPolicy, Thumbnail2d, ThumbnailTypes } from '@rbx/thumbnails';
import {
  Grid,
  Link,
  Avatar,
  TableCell,
  TableRow,
  ThumbUpIcon,
  PeopleIcon,
  AddIcon,
  RemoveIcon,
} from '@rbx/ui';
import { translationKey } from '@modules/analytics-translations/wrapperFunctions';
import type { ComparisonChipSpec } from '@modules/charts-generic/charts/ComparisonChip';
import MetricValue from '@modules/charts-generic/components/MetricValue/MetricValue';
import {
  wholePercentageFormattingSpec,
  integerFormattingSpec,
} from '@modules/charts-generic/constants/analyticsNumberFormattingSpec';
import SubtitleStat from '@modules/experience-analytics-shared/components/SubtitleStat/SubtitleStat';
import { useAnalyticsWatchlist } from '@modules/experience-analytics-shared/context/AnalyticsWatchlistProvider';
import useRAQIV2TranslationDependencies from '@modules/experience-analytics-shared/hooks/useRAQIV2TranslationDependencies';
import { IconButtonWithTooltip } from '@modules/miscellaneous/components';
import { TranslationNamespace } from '@modules/miscellaneous/localization';
import { creatorHub } from '@modules/miscellaneous/urls';
import type { ExperiencesTableMetricKeys } from './ExperiencesTableMetrics';
import {
  ExperiencesTableMetricColumnsOrder,
  ExperiencesTableMetricToFormattingSpec,
} from './ExperiencesTableMetrics';
import useExperiencesTableRowStyles from './ExperiencesTableRow.styles';

const { dashboard } = creatorHub;
export type MetricValue = {
  value: number | null;
  comparisonChipSpec: ComparisonChipSpec | null;
};

export type ExperiencesTableRowSpec = {
  universeId: number;
  title: string;
  likeRatio: number | null;
  playing: number | null;
  metrics: Record<ExperiencesTableMetricKeys, MetricValue>;
};

const ExperiencesTableRow = ({
  universeId,
  title,
  likeRatio,
  playing,
  metrics,
}: ExperiencesTableRowSpec) => {
  const { translate } = useRAQIV2TranslationDependencies();
  const {
    watchlistContains,
    addItem: addWatchlistItem,
    removeItem: removeWatchlistItem,
  } = useAnalyticsWatchlist();

  const {
    classes: {
      thumbnailContainer,
      thumbnailBackground,
      rowHoverBackground,
      experienceTitle,
      watchlistControl,
      watchlistControlCell,
      statsMargin,
      statsItemMargin,
    },
  } = useExperiencesTableRowStyles();

  const stats = [
    {
      key: 'ratio',
      Icon: ThumbUpIcon,
      value: likeRatio != null ? likeRatio / 100 : null,
      formatting: wholePercentageFormattingSpec,
    },
    {
      key: 'playing',
      Icon: PeopleIcon,
      value: playing,
      formatting: integerFormattingSpec,
    },
  ].map(({ key, Icon, value, formatting }) => (
    <Grid key={key} item className={statsItemMargin}>
      <SubtitleStat Icon={Icon} value={value} formattingSpec={formatting} />
    </Grid>
  ));

  const metricsCells = ExperiencesTableMetricColumnsOrder.map((metric) => {
    const metricsValue = metrics[metric];
    const formattingSpec = ExperiencesTableMetricToFormattingSpec[metric];

    return (
      <TableCell key={metric}>
        <MetricValue
          value={metricsValue.value}
          analyticsFormattingSpec={formattingSpec}
          comparisonChipSpec={metricsValue.comparisonChipSpec ?? undefined}
          justifyContent='flex-end'
        />
      </TableCell>
    );
  });

  const watchlistControlButton = watchlistContains(universeId.toString()) ? (
    <IconButtonWithTooltip
      className={watchlistControl}
      tooltipMsg={translate(
        translationKey('Description.RemoveFromWatchlist', TranslationNamespace.Analytics),
      )}
      icon={<RemoveIcon />}
      onClick={() => removeWatchlistItem(universeId.toString())}
    />
  ) : (
    <IconButtonWithTooltip
      className={watchlistControl}
      tooltipMsg={translate(
        translationKey('Description.AddToWatchlist', TranslationNamespace.Analytics),
      )}
      icon={<AddIcon />}
      onClick={() => addWatchlistItem(universeId.toString())}
    />
  );

  return (
    <TableRow className={rowHoverBackground}>
      <TableCell>
        <Grid container direction='row' alignItems='center' wrap='nowrap'>
          <Grid item>
            <Avatar variant='rounded' alt='avatar' className={thumbnailContainer}>
              <Thumbnail2d
                targetId={universeId}
                type={ThumbnailTypes.gameIcon}
                imgClassName={thumbnailBackground}
                alt=''
                returnPolicy={ReturnPolicy.AutoGenerated}
                includeBackground={false}
              />
            </Avatar>
          </Grid>
          <Grid item>
            <Grid container direction='column'>
              <Grid item>
                <Link
                  href={dashboard.getExperienceOverviewUrl(universeId)}
                  className={experienceTitle}>
                  {title}
                </Link>
              </Grid>
              <Grid item className={statsMargin}>
                <Grid container direction='row'>
                  {stats}
                </Grid>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
      </TableCell>
      <TableCell align='left' className={watchlistControlCell}>
        {watchlistControlButton}
      </TableCell>
      {metricsCells}
    </TableRow>
  );
};

export default ExperiencesTableRow;
