/** Pixel widths for IP / creator agreements table columns (header and row alignment). */

export const IP_AGREEMENTS_TABLE_CREATION_COL_WIDTH_PX = 280;
export const IP_AGREEMENTS_TABLE_LICENSE_COL_WIDTH_PX = 280;
export const IP_AGREEMENTS_TABLE_IP_FAMILY_COL_WIDTH_PX = 180;
export const IP_AGREEMENTS_TABLE_LICENSE_TYPE_COL_WIDTH_PX = 150;
export const IP_AGREEMENTS_TABLE_DURATION_COL_WIDTH_PX = 210;
export const IP_AGREEMENTS_TABLE_REVENUE_SHARE_COL_WIDTH_PX = 150;
export const IP_AGREEMENTS_TABLE_REVENUE_SHARE_TIMING_COL_WIDTH_PX = 180;
export const IP_AGREEMENTS_TABLE_LIFETIME_VISITS_RANGE_COL_WIDTH_PX = 180;
export const IP_AGREEMENTS_TABLE_STATUS_COL_WIDTH_PX = 180;
export const IP_AGREEMENTS_TABLE_LAST_UPDATED_COL_WIDTH_PX = 150;
