import { ClaimContentContentTypeEnum } from '@rbx/clients/rightsV1';
import { ThumbnailTypes } from '@rbx/thumbnails';

const contentTypeToThumbnailType = (contentType: ClaimContentContentTypeEnum): ThumbnailTypes => {
  switch (contentType) {
    case ClaimContentContentTypeEnum.Asset:
      return ThumbnailTypes.assetThumbnail;
    case ClaimContentContentTypeEnum.Bundle:
      return ThumbnailTypes.bundleThumbnail;
    default:
      return ThumbnailTypes.autoGeneratedPlaceThumbnail;
  }
};

export default contentTypeToThumbnailType;
