import React, { FunctionComponent, useCallback } from 'react';
import { ReturnPolicy, Thumbnail2d, ThumbnailTypes } from '@rbx/thumbnails';
import { gamesClient, RecommendedGameDetail } from '@modules/clients';
import { Carousel } from '@modules/miscellaneous/common/components';
import { useQuery } from '@tanstack/react-query';
import { Grid, makeStyles, Typography } from '@rbx/ui';
import { Link, urls } from '@modules/miscellaneous/common';
import { TranslationNamespace } from '@modules/miscellaneous/localization';
import { translationKey } from '@modules/analytics-translations';
import {
  useUniverseResource,
  useCurrentBenchmarkTypeIsSimilarityForExperiencesList,
  RAQIV2SectionTitle,
  OnboardingFeatureKey,
  OnboardingStepKey,
} from '@modules/experience-analytics-shared';

const MAX_SIMILAR_EXPERIENCES_PAGES = 3;

const fetchSimilarExperiencesPages = async (
  universeId: number,
  remainingPages: number,
  paginationKey?: string,
  results: RecommendedGameDetail[] = [],
): Promise<RecommendedGameDetail[]> => {
  if (remainingPages === 0) return results;

  try {
    const response = await gamesClient.getGameRecommendations(universeId, paginationKey);
    let newResults = results;
    if (response.games && response.games.length > 0) {
      newResults = [...results, ...response.games];
    }
    if (!response.nextPaginationKey) return newResults;
    return fetchSimilarExperiencesPages(
      universeId,
      remainingPages - 1,
      response.nextPaginationKey,
      newResults,
    );
  } catch {
    return [];
  }
};

const useSimilarExperiences = (
  universeId: number,
  isSimilarBenchmark: boolean = false,
  maxPages: number = MAX_SIMILAR_EXPERIENCES_PAGES,
) => {
  const select = useCallback(
    (
      universeDetails: RecommendedGameDetail[],
    ): Array<{
      universeId: number;
      universeName: string;
      placeId: number;
    }> => {
      const uniqueUniverseIds = new Set<number>();

      if (universeDetails.length === 0) {
        return [];
      }
      return universeDetails
        .filter(
          (game) =>
            game.universeId &&
            game.name &&
            game.placeId &&
            !uniqueUniverseIds.has(game.universeId) &&
            uniqueUniverseIds.add(game.universeId),
        )
        .map((game) => ({
          universeId: game.universeId!,
          universeName: game.name!,
          placeId: game.placeId!,
        }));
    },
    [],
  );

  return useQuery({
    queryKey: ['get-similar-experiences', universeId],
    queryFn: async () => fetchSimilarExperiencesPages(universeId, maxPages),
    select,
    enabled: isSimilarBenchmark,
  });
};

const useStyles = makeStyles()((theme) => ({
  thumbnailContainerClass: {
    position: 'relative',
    cursor: 'pointer',
    display: 'flex',
  },
  cardContainer: {
    ...theme.border.radius.medium,
    overflow: 'hidden',
    backgroundColor: theme.palette.surface[100],
    width: '220px',
  },
  nameContainer: {
    padding: '12px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  mainContainer: {
    width: '100%',
    marginTop: 24,
  },
}));

const SimilarExperienceTile: FunctionComponent<{
  universeId: number;
  universeName: string;
  placeId: number;
}> = ({ universeId, universeName, placeId }) => {
  const {
    classes: { thumbnailContainerClass, cardContainer, nameContainer },
  } = useStyles();

  return (
    <Grid item className={cardContainer}>
      <Link href={urls.www.getGameDetailsUrl(placeId)} target='_blank'>
        <Thumbnail2d
          alt={universeName}
          targetId={universeId}
          containerClass={thumbnailContainerClass}
          type={ThumbnailTypes.universeThumbnail}
          returnPolicy={ReturnPolicy.AutoGenerated}
        />
      </Link>
      <Typography variant='captionHeader' component='div' className={nameContainer}>
        {universeName}
      </Typography>
    </Grid>
  );
};

const SimilarExperiencesList: FunctionComponent = () => {
  const {
    classes: { mainContainer },
  } = useStyles();
  const { id: universeId } = useUniverseResource();
  const isSimilarBenchmark = useCurrentBenchmarkTypeIsSimilarityForExperiencesList();

  const {
    data: similarExperiencesDetails,
    isLoading,
    isError,
  } = useSimilarExperiences(universeId, isSimilarBenchmark);

  const noSimilarExperiences = !similarExperiencesDetails || similarExperiencesDetails.length === 0;
  if (isError || isLoading || noSimilarExperiences || !isSimilarBenchmark) {
    return null;
  }

  return (
    <Grid container item XSmall={12}>
      <RAQIV2SectionTitle
        titleKey={translationKey('Title.YourSimilarExperiences', TranslationNamespace.Analytics)}
        tooltipKey={translationKey(
          'Description.YourSimilarExperiences',
          TranslationNamespace.Analytics,
        )}
        onboardingTipsConfig={{
          featureKey: OnboardingFeatureKey.CreatorHubAnalyticsAcquisitionRfy,
          stepKey: OnboardingStepKey.SimilarExperienceSectionTitle,
        }}
      />
      <div className={mainContainer}>
        <Carousel>
          {similarExperiencesDetails?.map((experience) => (
            <SimilarExperienceTile key={experience.universeId} {...experience} />
          ))}
        </Carousel>
      </div>
    </Grid>
  );
};

export default SimilarExperiencesList;
