import { useMemo, useState } from 'react';
import type { ProductIdentifier } from '@rbx/client-price-experimentation-api/v1';
import { useTranslation } from '@rbx/intl';
import { Button, CircularProgress, SearchIcon, MenuItem, Select } from '@rbx/ui';
import DebouncedTextField from '@modules/charts-generic/charts/DebouncedTextField';
import type { Product } from '../../types/product';
import useProductTableStyles from './ProductTable.styles';
import ProductTableBase from './ProductTableBase';

interface ProductTableProps {
  universeId: number;
  noSelect?: boolean;
  showOptimizedPrice?: boolean;
  disabled?: boolean;
  loading?: boolean;
  products: Product[];
  // Function to convert product identifier to a string key used by the checked Set
  // Suggest using something like product.productType + '#' + product.productId
  // Make sure productIdentifierToKey doesn't change between renders; use useCallback if necessary
  productIdentifierToKey: (product: ProductIdentifier) => string;
  // Holds the keys of the checked products; keys generated by productIdentifierToKey
  checkedProducts?: Set<string>;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>, checkedProducts: Set<string>) => void;
  rowsPerPageOptions?: number[];
  defaultRowsPerPage?: number;
}

enum ProductTypeFilter {
  ShowAll = 'Show all product types',
  GamePass = 'GamePass',
  DeveloperProduct = 'DeveloperProduct',
}

const productTypeFilterValues = new Set<string>(Object.values(ProductTypeFilter));

function isProductTypeFilter(value: unknown): value is ProductTypeFilter {
  return typeof value === 'string' && productTypeFilterValues.has(value);
}

const ProductTable = ({
  universeId,
  noSelect,
  showOptimizedPrice,
  disabled,
  loading,
  products,
  productIdentifierToKey,
  checkedProducts,
  onChange,
  rowsPerPageOptions,
  defaultRowsPerPage,
}: ProductTableProps) => {
  const { translate } = useTranslation();
  const { classes } = useProductTableStyles();
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedType, setSelectedType] = useState<ProductTypeFilter>(ProductTypeFilter.ShowAll);

  const tableProducts = useMemo(() => {
    const filteredProducts = products.filter((product) => {
      const matchesSearchTerm = product.name.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesType =
        selectedType === ProductTypeFilter.ShowAll || product.productType === selectedType;
      return matchesSearchTerm && matchesType;
    });
    return filteredProducts;
  }, [products, searchTerm, selectedType]);

  const onChangeAll = (event: React.ChangeEvent<HTMLInputElement>, allChecked: boolean) => {
    if (onChange) {
      const newCheckedProducts = new Set(checkedProducts);
      if (allChecked) {
        tableProducts.forEach((product) => newCheckedProducts.add(productIdentifierToKey(product)));
      } else {
        tableProducts.forEach((product) =>
          newCheckedProducts.delete(productIdentifierToKey(product)),
        );
      }
      onChange(event, newCheckedProducts);
    }
  };

  const onChangeSingle = (
    event: React.ChangeEvent<HTMLInputElement>,
    product: ProductIdentifier,
    checked: boolean,
  ) => {
    if (onChange) {
      const newCheckedProducts = new Set(checkedProducts);
      if (checked) {
        newCheckedProducts.add(productIdentifierToKey(product));
      } else {
        newCheckedProducts.delete(productIdentifierToKey(product));
      }
      onChange(event, newCheckedProducts);
    }
  };

  return (
    <div>
      <div className={classes.searchContainer}>
        <DebouncedTextField
          id='product-table-search'
          // Make label empty so it doesn't fly up the text field
          // Use aria label for accessibility instead
          label=''
          aria-label={translate('Label.SearchTable')}
          placeholder={translate('Label.SearchTable')}
          size='small'
          InputProps={{
            startAdornment: <SearchIcon className={classes.searchIcon} />,
            type: 'search',
          }}
          value={searchTerm}
          onDebouncedChange={setSearchTerm}
          debounceTime={100}
        />
        <Select
          onChange={(e) => {
            if (isProductTypeFilter(e.target.value)) {
              setSelectedType(e.target.value);
            }
          }}
          margin='none'
          size='small'
          value={selectedType}
          inputProps={{ 'aria-label': translate('Label.SelectProductType') }}
          variant='outlined'>
          <MenuItem value={ProductTypeFilter.ShowAll}>
            {translate('Label.ShowAllProductTypes')}
          </MenuItem>
          <MenuItem value={ProductTypeFilter.GamePass}>{translate('Label.Passes')}</MenuItem>
          <MenuItem value={ProductTypeFilter.DeveloperProduct}>
            {translate('Label.DeveloperProducts')}
          </MenuItem>
        </Select>
        <Button
          size='large'
          variant='text'
          color='secondary'
          onClick={() => setSearchTerm('')}
          disabled={!searchTerm}>
          {translate('Action.ResetSearch')}
        </Button>
      </div>
      {loading ? (
        <CircularProgress />
      ) : (
        <ProductTableBase
          universeId={universeId}
          products={tableProducts}
          noSelect={noSelect}
          showOptimizedPrice={showOptimizedPrice}
          disabled={disabled}
          checkedProducts={checkedProducts}
          productIdentifierToKey={productIdentifierToKey}
          onChangeAll={onChangeAll}
          onChange={onChangeSingle}
          rowsPerPageOptions={rowsPerPageOptions}
          defaultRowsPerPage={defaultRowsPerPage}
          numSelected={checkedProducts?.size ?? 0}
          numTotal={products.length}
        />
      )}
    </div>
  );
};

export default ProductTable;
