name: Go Build

on:
  push:
    branches:
      - "master"
    paths:
      - "src/**"
      - ".github/workflows/**"

env:
  PROJECT_NAME: 'next-pages-router-crawler'

permissions:
  contents: write

jobs:
  lint:
    name: Go lint
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP BUILD]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup the Golang environment with version 1.25.x
        uses: actions/setup-go@v7
        with:
          go-version: 1.25.x

      - name: Run lint
        working-directory: ./src
        run: go mod tidy && go mod vendor && go vet ./...


  build:
    name: Build
    if: "!contains(toJSON(github.event.commits.*.message), '[SKIP BUILD]')"
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v7

      - name: Setup the Golang environment with version 1.25.x
        uses: actions/setup-go@v7
        with:
          go-version: 1.25.x

      - name: Run the build-release make target
        run: make build-release

      - name: Create zip file
        run: mkdir -p ${GITHUB_WORKSPACE}/build/ && cd bin/release/linux/x64 && zip -r ${GITHUB_WORKSPACE}/build/${{ env.PROJECT_NAME }}.zip *

      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.PROJECT_NAME }}
          retention-days: 1
          path: |
            build/${{ env.PROJECT_NAME }}.zip
  
        
  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'master' }}

    strategy:
      fail-fast: true

    steps:
    - name: Download  Artifacts
      uses: actions/download-artifact@v7
      with:
        path: build

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: build-${{github.run_id}}
        generate_release_notes: true
        draft: false
        prerelease: ${{ github.ref_name != 'master' }}
        files: |
          build/*.zip