name: Publish output to branch

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

# Allow pushing to the target branch without requiring a personal access token
permissions:
  contents: write

jobs:
  publish:
    # If the URL and BRANCH vars isn't empty only
    if: ${{ vars.URL != '' && vars.BRANCH != '' }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup the Golang environment with version 1.25.x
        uses: actions/setup-go@v7
        with:
          go-version: 1.25.x
          cache-dependency-path: "src/go.mod"

      - name: Run the build-release make target
        run: make build-release

      - name: Run crawler
        run: ./bin/release/linux/x64/next-pages-router-crawler --url "${{ vars.URL }}" --pulse --clear-cache --clear-output

      - name: Prepare and push dist to target repo
        env:
          TARGET_BRANCH: ${{ vars.BRANCH }}
        run: |
          set -euo pipefail

          # Ensure output exists
          if [ ! -d "$GITHUB_WORKSPACE/.output" ]; then
            echo "Error: .output/ not found. Make sure generating step produced a .output folder." >&2
            ls -la
            exit 1
          fi

          # Checkout repo
          git clone --depth 1 "https://github.com/${{ github.repository }}.git" "$GITHUB_WORKSPACE/.tmp"
          cd "$GITHUB_WORKSPACE/.tmp"
          
          # Checkout if exists or create a new empty branch with no history
          git fetch origin "${TARGET_BRANCH}" || true
          if git rev-parse --verify "origin/${TARGET_BRANCH}" >/dev/null 2>&1
          then
            git checkout "origin/${TARGET_BRANCH}"
          else
            git checkout --orphan "${TARGET_BRANCH}"
          fi

          # Remove tracked files (leave .git directory intact)
          git rm -rf . || true

          # Copy dist contents into the root of the target repo
          cp -a "$GITHUB_WORKSPACE/.output/${TARGET_BRANCH}/." . || true

          # Only commit & push if something changed
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(output): update from $GITHUB_SHA"
            git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" "HEAD:${TARGET_BRANCH}" --force
            echo "Pushed updated output to ${{ github.repository }}:${TARGET_BRANCH}"
          else
            echo "No changes in output; nothing to commit"
          fi
